### ISSUE TITLE
Improve pre-evaluation of function calls

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1052]
* **Query:**

```xquery
declare function local:a() { local:b#1(1) };
declare function local:b($a) { $a };
local:a()
```

* **Optimized:**
```xquery
declare function local:a() { local:b#1(1) }; 
local:a()
```

* **Desirable:** `1`

Reported by Jean-Marc: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg05379.html

**Comment by ChristianGruen** [comment]
Pre-evaluation works if the function declarations are swapped:

```xquery
declare function local:b($a) { $a };
declare function local:a() { local:b#1(1) };
local:a()
```

**Comment by LeoWoerteler** [comment]
The `FuncLit` class does double duty, representing functions that cannot be resolved during parsing as well as built-in functions that are *focus dependent* (e.g. `position#0`, `name#0`). As the latter cannot be inlined, the former won't be either. The best way to fix this would be to represent both cases differently and resolve the first one to a *function item* in `QueryParser#finish(...)`.
