### ISSUE TITLE
Messy latest stable WAR file

### ISSUE THREAD

**Issue by kristiank** [BaseXdb/basex#1060]
Hello!

Background: I have a functioning install of the latest official release, but because of the dba and other features (mainly users.xml), so I wanted to try version 8.0.

So I downloaded the latest stable from [here](http://files.basex.org/releases/latest/BaseX80-20150118.150705.war) and deployed it in Tomcat 7.0.52.

Many issues arised:

* When un-commenting the ``<context-param>`` in WEB-INF/web.xml, it turns out the web.xml is malformed and contains several opening elements of ``<context-param>`` without matching ending elements. I erased the opening elements and get the servlet started.

* When opening [my localhost](http://localhost:8080/BaseX80-20150118.150705/) I noticed the graphics and style is missing -- turns out the whole static folder is missing in the war file! I copy the two files from my old 7.9 installation and the start-page looks fine.

* When opening the [dba](http://localhost:8080/BaseX80-20150118.150705/dba) I get a "HTTP Status 404 - No function found that matches the request." message.

Probably I should change my workflow and download the latest code from git and compile it, but that would require a too steep learning curve. Hopefully a new latest stable can be generated by the BaseX team instead. Thank you!

**Comment by ChristianGruen** [comment]
Thanks for the helpful hints. Our aim is to make Version 8.0 as easily usable as 7.9.

**Comment by kristiank** [comment]
I will try using Git and Eclipse. Your documentation seems to make it less steep than I thought.

**Comment by kristiank** [comment]
... but wait, if I simply do an automated build from the latest code, shouldn't I get the same result as your latest stable has?

**Comment by ChristianGruen** [comment]
> ... but wait, if I simply do an automated build from the latest code, shouldn't I get the same result as your latest stable has?

Yes, it should work out like this.

I have fixed Issue 1. Regarding Issue 2, the new `rest.xqm` only includes a redirection to DBA (but maybe I will reinclude the old start page). I would be interested what's the reason for Issue 3.

**Comment by ChristianGruen** [comment]
The start page, and the static folder, is now reincluded in the distributions. On Issue 3: Did you manage to successfully start DBA? If no, do you have some clue what could be the problem?

**Comment by kristiank** [comment]
I got it partly working by adding an initial ``/`` to the rest:path declarations in the dba/util.xqm module. It then complains that the ``/dba/databases resource`` is not available. But then it allready has changed the url basepath into purely ``http://localhost:8080/dba/databases`` instead of ``http://localhost:8080/BaseX80-20150118.150705/dba/databases``.

**Comment by kristiank** [comment]
Good morning.
I believe it is only the ``rest:redirect('dba/databases')`` that doesn't work for me. Accessing with an absolute url to http://localhost:port/dba/databases works just fine for me. I now deleted the initial ``/`` in the rest:paths I mentioned earlier.

**Comment by kristiank** [comment]
Please notice I did quite a rewrite of the last message. Sorry, will write more clean the first time in the future.

**Comment by kristiank** [comment]
I don't know if this might be relevant, but when I try to add buttons for extended functionality of the DBA, I don't see any changes reflected in the browser.

For example in the file ``dba/database/databases.xqm`` I add a second line like this:
``
let $buttons := (
              html:button('create-db', 'Create…'),
              html:button('import-special', 'Import…'),
              html:button('optimize-all', 'Optimize'),
              html:button('drop-db', 'Drop', true())
            )
``

No extra button shows up in the browser. I have tried restarting the BaseX servlet.

**Comment by ChristianGruen** [comment]
> I don't know if this might be relevant, but when I try to add buttons for extended functionality
> of the DBA, I don't see any changes reflected in the browser.

Personally, I haven't tried BaseX with Tomcat so far, so I don't know if it caches the files somewhere. Maybe you can find out more about that?

Editing the xqm works perfectly if you start the BaseX HTTP Server on command line, as described in our [documentation](http://docs.basex.org/wiki/Web_Application).

**Comment by ChristianGruen** [comment]
I'm closing this for now. If you have more comments, feel free to open this again.
