### ISSUE TITLE
html:parse missing spaces around tags

### ISSUE THREAD

**Issue by ScalaWilliam** [BaseXdb/basex#1069]
```xml
<rest:query xmlns:rest="http://basex.org/rest">
<rest:text><![CDATA[
declare option output:method 'html';
html:parse('<p>This is <strong>an</strong> article.</p>', map{"method":'html'})
  ]]></rest:text>
</rest:query>
```

Output:
```html
<html>
  <body>
    <p>This is<strong>an</strong>article.</p>
  </body>
</html>
```

Expected:
```html
<html>
  <body>
    <p>This is <strong>an</strong> article.</p>
  </body>
</html>
```

If both 'output methods' were not set, I'd still expect those spaces to be there.

Version: 8.0 beta 997d480. Didn't see any relevant commits and issues since, so posting this as an issue. Use case: storing HTML as a string, then mixing it up with other HTML generated in XQuery.

**Comment by ScalaWilliam** [comment]
Would be nice to have an option to get the contents of body straight away as well

**Comment by ScalaWilliam** [comment]
I tried most of the options available at the docs here http://home.ccil.org/~cowan/tagsoup/

**Comment by ChristianGruen** [comment]
[Fixed](https://github.com/BaseXdb/basex/commit/2e1941754f0099847908529e20bcc7c3ae58efc5), thanks (a new snapshot is currently being uploaded).

> Would be nice to have an option to get the contents of body straight away as well

If you only want to have the body of the HTML document returned, it's probably best to simply use `html:parse(....)//body`. Or do you mean something different?

**Comment by ScalaWilliam** [comment]
I want the contents of the body. It is, of course, trivial. e.g.
```html
<p>This is<strong>an</strong>article.</p>
```

Thank you Christian!
