### ISSUE TITLE
Locking Database Resources

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1083]
It would be nice to extend locking support in BaseX. The current implementation on resource level suffers from the following shortcomings:
- Locking is only possible with WebDAV
- Only exclusive locks are supported (should be extended to shared locks)
- No XQuery functions exist to explicitly lock and unlock resources
- Locked resources can still be accessed and updated by other APIs

Along with standard locking information (containing `token id`, `owner`, `depth`, `type` (exclusive/shared), `timeout`), it should be possible to store custom locking data. See https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg05804.html for more details.

**Comment by FranceBaril** [comment]
Short term, I see a need for all listed items except maybe the shared lock. As long a read access is not blocked by the write lock, we can manage. Long term, it might be interesting to consider locking mechanisms that allow developers to implement collaborative authoring. For example, having the ability to request locks at the element level. Related reading: http://www.ic.unicamp.br/~wainer/old/criwg/32.pdf.

**Comment by erdalkaraca** [comment]
Having locks at resource level would be fine.

**Comment by ChristianGruen** [comment]
Discarded in favor of other features.
