### ISSUE TITLE
Service mode loses system property information?

### ISSUE THREAD

**Issue by davidmathei** [BaseXdb/basex#1092]
When I start the server (8.0.2) with
````java -cp <omitted> -Dorg.basex.path=/path/to/config/and/data org.basex.BaseXServer````
it picks up the .basex file on that location just fine.

If I add the service - flag
 ````java -cp <...> -Dorg.basex.path=/path/to/config/and/data org.basex.BaseXServer -S```` 
it seems that the restart of the server in another process loses the system property. The "ping" signals an error. ("Can't communicate with the server", there is indeed a different port specified in the alternative .basex file) When I look at the ```ps``` command output for that process, it shows something like 
 ````java -cp <...> -D/path/to/config/and/data org.basex.BaseXServer -D -S````

It seems like start() in Utils.java does not copy the key of the property.

After digging a bit around in the code it looks like
````if(k.startsWith(Prop.DBPREFIX)) sl.add("-D" + k + "=" + o.getValue());```` would solve that problem?

(https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/util/Util.java#L265)

**Comment by ChristianGruen** [comment]
I think it solves the problem ;) Thanks for your pull request.
