### ISSUE TITLE
basex at maven central

### ISSUE THREAD

**Issue by physikerwelt** [BaseXdb/basex#1099]
basex at maven central seems outdated
http://search.maven.org/#artifactdetails|org.basex|basex|7.3.1|jar
I was using version 7.9 for my developments. This version seems to be quite stable.

**Comment by ChristianGruen** [comment]
It would be nice to have every version of BaseX deployed to the central Maven repository, but we may need to find out how this can be done. Suggestions are welcome.

**Comment by ChristianGruen** [comment]
Guides:
* http://maven.apache.org/guides/mini/guide-central-repository-upload.html
* http://lkrnac.net/blog/2014/03/deploy-to-maven-central/

**Comment by physikerwelt** [comment]
Yes. It's not too difficult. Beginning from gpg 1.6 you can also store an encrypted gpg key password.
If it helps here is my pom as reference https://github.com/physikerwelt/MathMLQueryGenerator/blob/master/pom.xml

**Comment by ChristianGruen** [comment]
Thanks for the feedback! Is there any chance to simply upload our repository files (http://files.basex.org/maven/org/basex/) to the central repository?

**Comment by jitpack-io** [comment]
Btw, it's also easy to get the latest version of BaseX from the JitPack.io:  https://jitpack.io/#BaseXdb/basex/8.0.3

It builds the project for you so doesn't require uploading : )

**Comment by ChristianGruen** [comment]
@jitpack-io : Thanks for the hint. Building the project is no problem for us; what I'd ideally like to have is an automatic synchronisation of our own maven repository to maven central. Do you have any ideas how we could achieve this?

**Comment by jitpack-io** [comment]
It's possible but you'd need to contact them directly http://central.sonatype.org/pages/producers.html#large-organizationsforges-repository-sync

**Comment by ChristianGruen** [comment]
Thanks, this is helpful!

**Comment by ChristianGruen** [comment]
Closing this (it seems it’s hardly possible to find a solution that’s both simple and free…).

**Comment by physikerwelt** [comment]
Is #1489 the attempt to fix this issue? I would still appreciate if this was fixed since I'm seeing problems to download files from files.basex.org from time to time, which means that I have to restart my quite long running maven jobs.

**Comment by micheee** [comment]
Hi @physikerwelt 

this should fix the issue yes. You might want to give it a try, @dirkk and @jagrutkosti set this up with maven central.

Regarding the download issues with files.basex.org I can look into that :)

**Comment by physikerwelt** [comment]
@ChristianGruen unfortunately I don't know what caused the temporary problems to connect to files.basex.org.  What is the artifact name for maven central? Following my link above I can only find a very old version. See http://repo1.maven.org/maven2/org/basex/basex/

**Comment by dirkk** [comment]
@physikerwelt Sorry, there still are some issues doing the actual release deploy to Maven Central. I am working on fixing it. I'll ping you if it works. Artifact names will be the same.

**Comment by micheee** [comment]
Hi @physikerwelt ,

seems weird; the files are hosted with jweiland, so I would not expect difficulties on a regular basis.

At least I can not remember having seen this message…

I just added files.basex.org to our internal monitoring scripts, I'll check it is up every 5 minutes and see if there is a problem on our side!

Thanks for reporting!
