### ISSUE TITLE
Version 8.0, authentication has changed

### ISSUE THREAD

**Issue by Cristiancatalan** [BaseXdb/basex#1100]
Well, sorry if this is not the right place. 
After a long time thinking why it doesn't connect with the version 8 of BaseX, I saw the authentication has changed. 
Before the right code was updated , I write here what worked for me (at least!). I have changed two lines in baseXclient.php

// receive timestamp
$realm_nonce = split(":",$this->readString());
// send username and hashed password/timestamp
$md5 = hash("md5", hash("md5", ($user.':'.$realm_nonce[0].':'.$pw)).$realm_nonce[1]);

Info about the new authentication metod (they say "it's trivial", but It's necessary!!)
Hope this could help.

Info about the Authentication:
http://docs.basex.org/wiki/Server_Protocol#Authentication

**Comment by ChristianGruen** [comment]
Thanks for the hint. Isn't this already covered in the [current version](https://github.com/BaseXdb/basex/blob/master/basex-api/src/main/php/BaseXClient.php#L21-L31) of the PHP binding?

**Comment by ChristianGruen** [comment]
Closing this… Feel free to reopen the issue if you think I oversaw something.
