### ISSUE TITLE
Limit on number of files

### ISSUE THREAD

**Issue by baarsrj** [BaseXdb/basex#1102]
It appears BaseX only can handle one directory. But there is a limit on the number of files per directory (if not by the OS, at least by usability).
Could this limitation be removed by considering the directory set as the root directory of a file structure to be indexed and used?

**Comment by dirkk** [comment]
I am not sure what you mean by "one directory". BaseX is a database system and as such you can have unlimited databases with each holding documents within many directories.
Anyway, we do not use this issue tracker for discussion, but for bug-tracking only. So I am going to close this, but you are more than welcome to ask the question on our mailing list: https://mailman.uni-konstanz.de/mailman/listinfo/basex-talk
