### ISSUE TITLE
BaseX 8.0.2 hangs on restful database creation

### ISSUE THREAD

**Issue by VincentBiragnet** [BaseXdb/basex#1103]
Consider a preexisting empty `foo` database (created via basexclient `create database foo`).

File body.xml contains:

    <query xmlns='http://basex.org/rest'><text>
    	declare variable $base as xs:string external;
    	db:add($base, &lt;foo&gt;&lt;/foo&gt;, 'foo.xml')
    </text><variable name='base' type='xs:string' value='foo'/></query>

 Using the following curl command freezes BaseX server:

    curl -X POST -i -H "Authorization: Basic YWRtaW46YWRtaW4=" -d @body.xml http://localhost:8984/rest/foo

Note that BaseX works as expected if either:
* no variable is passed in the body.xml
* the URL is http://localhost:8984/rest

This used to work in BaseX 7.9.

**Comment by ChristianGruen** [comment]
Thanks for the bug report. The fix will be available in 8.0.3 (to be released today).
