### ISSUE TITLE
Replace first document with another namespaced one

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1112]
If the first document in the database is replaced with another document that contains namespaces, we may end up with the exception `Insertion at beginning of populated table.`:

**Start**: `basex bug.bxs`

**Command script** (bug.bxs):

```
create db db
replace a.xml <a/>
replace b.xml <b/>
replace a.xml <a xmlns:b='c'/>
```

**Comment by LeoWoerteler** [comment]
Is namespace support planned for BaseX 9? :-P

**Comment by ChristianGruen** [comment]
Maybe partially ;)

**Comment by ChristianGruen** [comment]
Clean solution, dirty location:

https://github.com/BaseXdb/basex/commit/8193559037b198dde54180313b9f2a3d77c1dbfd#diff-db7dd2c1909a4c546f991d17da7935c2L325
https://github.com/BaseXdb/basex/commit/8193559037b198dde54180313b9f2a3d77c1dbfd#diff-158eb835a48973de3cf994d5b4fcfaabL45
