### ISSUE TITLE
Don't load .DS_Store (or probably any \.* file) in repo

### ISSUE THREAD

**Issue by drmacro** [BaseXdb/basex#1122]
On OS X, putting a file into the initially-empty configured REPO directory causes a .DS_Store file to be created.

Doing a repo list command then shows the .DS_Store file in the list of loaded modules.

This file should be ignored by the module loader. Probably appropriate to ignore all hidden files.

**Comment by ChristianGruen** [comment]
Sounds reasonable; thanks for the hint.

**Comment by ChristianGruen** [comment]
A new snapshot will be available in appr. 5 min.
