### ISSUE TITLE
Check existence of all directories configured in .basex and report on server startup

### ISSUE THREAD

**Issue by drmacro** [BaseXdb/basex#1123]
E.g., check that WEBPATH exists and report if it does not on basexhttp startup.

I am capable of implementing a fix for this and am happy to do so as soon as I have a bit of time to focus on it. Obviously not a critical issue but it would have saved me a bit of spinning my wheels.

**Comment by ChristianGruen** [comment]
In various use cases, if only WebDAV or REST is used, it does not matter if the specified WEBPATH exists. But we could possibly raise this warning when the RESTXQ servlet is used for the first time (the [RestXqServlet.java](https://github.com/BaseXdb/basex/blob/master/basex-api/src/main/java/org/basex/http/restxq/RestXqServlet.java) could be extended to overwrite `init(ServletConfig)`).

**Comment by ChristianGruen** [comment]
Closed for now; feel free to reopen it.
