### ISSUE TITLE
Failure on attempt to replace XML with no DTD when DTD = true

### ISSUE THREAD

**Issue by drmacro** [BaseXdb/basex#1125]
Using 8.1 on my machine (OS X 10.10.3), this command reliably fails:

~~~~
basexclient -c 'CHECK dfst_dfst-sample-project_develop; SET DTD true;
REPLACE dfst/metadata.xml
<dfst_metadata><gitstate><branch>develop</branch><commit>2df2f9674f7e8a5d43
865411b193f76b19e9565d</commit></gitstate></dfst_metadata>' -U admin -P
admin -p 1984 -n localhost
"
"..." (Line 1): Premature end of file.
~~~~

And this succeeds:

~~~~
basexclient -c 'CHECK dfst_dfst-sample-project_develop; SET DTD false;
REPLACE dfst/metadata.xml
<dfst_metadata><gitstate><branch>develop</branch><commit>2df2f9674f7e8a5d43
865411b193f76b19e9565d</commit></gitstate></dfst_metadata>' -U admin -P
admin -p 1984 -n localhost
~~~~

Likewise, attempts to parse a non-XML file as XML fails with the same error before SKIPCORRUPT = true processing can kick.

Christian reports he cannot reproduce the error, which suggests the problem is specific to something in my local environment. But the failure must be in the DTD-aware parsing process.

I will attempt to debug the code and see if I can find where the error is occurring and why.

**Comment by ChristianGruen** [comment]
I would be interested to know if the command still fails when further reducing the example? E.g., does the following command also fail?

```
basexclient -c "CHECK db; SET DTD true; REPLACE doc.xml <a/>" -U admin -P admin -p 1984 -n localhost
```

I am asking because there is not a single DTD reference in the XML snippet we had been looking so far.

**Comment by ChristianGruen** [comment]
I also tested this on a Linux machine; no failure again.

Can you really reproduce this with a Vanilla instance of our ZIP distribution?  Did you specify the command in a single line or (as it looks like in your bug report) does it stretch over multiple lines?

**Comment by drmacro** [comment]
Here's what I get:

Contrext01:rsuite_nab ekimber$ basexclient -c "CHECK db; SET DTD true; REPLACE doc.xml <a/>" -U admin -P admin -p 1984 -n localhost
"..." (Line 1): Premature end of file.
Contrext01:rsuite_nab ekimber$ 

Contrext01:rsuite_nab ekimber$ basexhttp -v
BaseX 8.1 [HTTP]
Usage: basexhttp [-dehlnpPsSUz] [stop]
  stop      Stop running server
  -d        Activate debugging mode
  -e<port>  Set event port
  -h<port>  Set port of HTTP server
  -l        Start in local mode
  -n<name>  Set host name of database server
  -p<port>  Set port of database server
  -P<pass>  Specify user password
  -s<port>  Specify port to stop HTTP server
  -S        Start as service
  -U<name>  Specify user name
  -z        Suppress logging
Contrext01:rsuite_nab ekimber$ 

Contrext01:rsuite_nab ekimber$ basexclient -v
BaseX 8.1 [Client]
Try help to get more information.

> get
Global options:
AUTHMETHOD: Basic
DBPATH: /Users/ekimber/BaseXData
DEBUG: false
EVENTPORT: 1985
GLOBALLOCK: false
HOST: localhost
HTTPLOCAL: false
IGNORECERT: false
KEEPALIVE: 600
LANG: English
LANGKEYS: false
LOG: true
LOGMSGMAXLEN: 1000
NONPROXYHOSTS: 
PARALLEL: 8
PASSWORD: admin
PORT: 1984
PROXYHOST: 
PROXYPORT: 0
REPOPATH: /Users/ekimber/workspace-dfst/dfst-linkmgmt-basex/modules
RESTPATH: 
RESTXQPATH: 
SERVERHOST: 
SERVERPORT: 1984
STOPPORT: 8985
TIMEOUT: 30
USER: admin
WEBPATH: /Users/ekimber/workspace-dfst/dfst-linkmgmt-basex/webapp

Local options:
ADDARCHIVES: true
ADDCACHE: false
ADDRAW: false
ATTRINDEX: true
AUTOFLUSH: true
AUTOOPTIMIZE: false
BINDINGS: 
CACHEQUERY: false
CASESENS: false
CATFILE: /Applications/oxygen/frameworks/dita/DITA-OT/catalog-dita.xml
CHECKSTRINGS: true
CHOP: false
COMPPLAN: true
CREATEFILTER: *.xml
CREATEONLY: false
CSVPARSER: 
DEFAULTDB: false
DIACRITICS: false
DOTCOMPACT: false
DOTPLAN: false
DTD: true
EXPORTER: 
FORCECREATE: false
FTINDEX: false
FTINDEXSPLITSIZE: 0
HTMLPARSER: 
INDEXSPLITSIZE: 0
INLINELIMIT: 100
INTPARSE: false
JSONPARSER: 
LANGUAGE: en
LSERROR: 0
MAINMEM: false
MAXCATS: 100
MAXHITS: -1
MAXLEN: 96
MAXSTAT: 30
MIXUPDATES: false
PARSER: xml
QUERYINFO: false
QUERYPATH: 
RUNQUERY: true
RUNS: 1
SERIALIZE: true
SERIALIZER: 
SKIPCORRUPT: true
STEMMING: false
STOPWORDS: 
STRIPNS: false
TAILCALLS: 256
TEXTINDEX: true
TEXTPARSER: 
UPDINDEX: false
WRITEBACK: false
XINCLUDE: true
XMLPLAN: false

As far as I know I'm using the out-of-the-box Zip dist of 8.1.0.

**Comment by drmacro** [comment]
And with DTD = false:

Contrext01:rsuite_nab ekimber$ basexclient -c "CHECK db; SET DTD false; REPLACE doc.xml <a/>" -U admin -P admin -p 1984 -n localhost
Contrext01:rsuite_nab ekimber$ 

So DTD = true is the variable. Why is another question.

I suspect either a Java version issue or some very subtle bug:

Contrext01:rsuite_nab ekimber$ java -version
java version "1.7.0_65"
Java(TM) SE Runtime Environment (build 1.7.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

**Comment by ChristianGruen** [comment]
Yes, it might indeed be related to something else than BaseX, because I have no chance reproducing it on either Windows or Linux. So I need to bug you with some more questions:

1. The values of the options seem to indicate that it might not be a completely fresh BaseX instance you are working with. Could you please try to download and unzip the latest version, start the contained `basexserver` script and run your script with the contained `basexclient` script?

2. Does the bug also occur when using `CREATE db db` instead of `CHECK db`?

3. Does the bug also occur with the standalone version of BaseX?

```
basex -c "CHECK db; SET DTD true; REPLACE doc.xml <a/>"
```

4. What happens if you change the order of the arguments?...

```
basexclient -U admin -P admin -p 1984 -n localhost -c "CHECK db; SET DTD true; REPLACE doc.xml <a/>"
```

5. What happens if you drop them?

```
basexclient -c "CHECK db; SET DTD true; REPLACE doc.xml <a/>"
```

**Comment by ChristianGruen** [comment]
Usually, we only add confirmed bugs to our GitHub issue list, so I decided to close for this for now. We can surely reopen it once we have an example that works for us as well.
