### ISSUE TITLE
Storage, XQuery: Token index for attribute values

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1130]
* Token index for attribute values
* Optimize `contains-token(@..., '...')` requests to sth. similar to `index:token(...)`.

**Comment by frederik-elwert** [comment]
I think this is a very important feature, since many XML dialects allow for whitespace separated lists of values in attributes, `@html:class` being probably a prime example.

In a recent application, I also came across this, but I think my use case is a bit special, so I thought I would mention it.

I have a stand-off XML file that contains tokens and sentences:

```xml
<textCorpus>
<tokens>
  <token ID="t1">one</token>
  <token ID="t2">two</token>
</tokens>
<sentences>
  <sentence ID="s1" tokenIDs="t1 t2"/>
</sentences>
</textCorpus>
```

Now I have a sequence of token IDs that I get by some filtering and want to get a list of sentences that contain these tokens. I am using this query:

```xquery
let $sentences := $doc//sentence[tokenize(@tokenIDs) = $token_ids]
```

I mention this because here I would not benefit from an optimized `contains-token()`, since that only tests for one given string, not a sequence of values. I don’t know if there is a good way of taking this kind of usage into account when implementing attribute token indexes.

**Comment by ChristianGruen** [comment]
@frederik-elwert: I think your use case **would** be covered by the optimization of `contains-token()`, because its argument is indeed tokenized (see [here](http://docs.basex.org/wiki/XQuery_3.1#fn:contains-token) or [here](http://www.w3.org/TR/xpath-functions-31/#func-contains-token)). But maybe I got you wrong?

**Comment by ChristianGruen** [comment]
To complement this: I may need to check the details, but I believe we’ll also be able to rewrite `tokenize()` for index access.

**Comment by frederik-elwert** [comment]
@ChristianGruen: As far as I understand (and what a quick test confirms), only the first argument is tokenized. However, I want to compare the tokenized value (in this case of `@tokenIDs`) against a *sequence* of values (in this case `$token_ids`). `contains-token()` accepts a sequence as its first argument, but not as the second one.

But index based tokenize() would indeed solve the issue, I guess.

**Comment by ChristianGruen** [comment]
I got it; thanks for the clarification! You are right, this would need to be written as `...[contains-token(...) or contains-token(...)]`. I think we’ll be able to rewrite both types of queries.

**Comment by ChristianGruen** [comment]
This is what still needs to be done:

**Index Creation**
* [x] Use and extend existing value index builders
* [x] Additionally store positions of distinct tokens
* [x] Support for disk- and main-memory-based index structures

**Commands & Options**
* [x] New commands: `CREATE INDEX`, `DROP INDEX`
* [x] New options: `TOKENINDEX`, `TOKENINCLUDE`

**Querying**
* [ ] Rewrite paths to token index access:<br/>`...[contains-token(node, string)]`; `...[tokenize(node) = string]`;
* [x] Introduce new functions: `db:token`, `index:tokens`
* [x] Consider token index when optimizing database

**Interfaces**
* [x] GUI: Include token index in Create and Properties dialog
* [ ] DBA: Include token index in Create and Optimize dialog

**Wiki**
* [x] Options, Commands, Indexes, Database Module, Index Module
* [ ] Indexes: update rewriting examples

**Comment by JensErat** [comment]
If you didn't tackle it,

* [ ] Support for updating disk- and main memory indexes

is to be added to the queue.

**Comment by ChristianGruen** [comment]
Bug, updatable token index:

```xml
<commands>
  <set option='updindex'>true</set>
  <set option='tokenindex'>true</set>
  <create-db name='test'/>
  <add path='a.xml'>
    <html id="id0" id2="id1" idref="id2"/>
  </add>
  <close/>
  <xquery>index:tokens('test')</xquery>
</commands>
```

**Comment by ChristianGruen** [comment]
Thanks to the great commitment of @JensErat, the token index now got realized, including incremental updates and main-memory updates!
