### ISSUE TITLE
XQuery: calling non-deterministic functions

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1137]
Code should be evaluated:

```xquery
let $f := function () { prof:sleep(1000) }
return ($f(), $f())
```

**Comment by ChristianGruen** [comment]
The code of the XQuery example is now evaluated, but the general problem remains: Function items are deterministic, even if the function bodies are non-deterministic. It's only the function call that makes the expression non-deterministic.

**Comment by LeoWoerteler** [comment]
Pragma around the call?

```xquery
let $f := function () { prof:sleep(1000) }
return ((# basex:nondet #) { $f() }, (# basex:nondet #) { $f() })
```

**Comment by ChristianGruen** [comment]
True; may be better than trust & pray.
