### ISSUE TITLE
[DBA] Settings route not working

### ISSUE THREAD

**Issue by ab34** [BaseXdb/basex#1141]
In the DBA dashboard, the "settings" route freezes the server each time it is clicked on. No result is displayed, the page just seems to wait indefinitely blocking the whole application until one stops the server completely.

All the other routes work fine (until one clicks on the "settings" URL).

Tested on windows 8, 64 bits.

**Comment by ChristianGruen** [comment]
Thanks. The problem has been fixed in the latest 8.2 snapshot.

**Comment by ab34** [comment]
Just tried the latest 8.2 snapshot (beta-5140059), from the main website, but unfortunately this time, the whole dba server does not work anymore. Here the server response when browsing to *localhost:8984/dba*:
```
HTTP ERROR 404

Problem accessing /dba. Reason:

    No function found that matches the request.
Powered by Jetty://
```

In the server shell, there is a line saying:
```
No JSP support for /, did not find apache.org.jasper.servlet.JspServlet
```

It may be related to the issue.

**Comment by ChristianGruen** [comment]
It works on my machine. Maybe you have started BaseX from a directory that has its own `.basex(home)` file.

**Comment by ab34** [comment]
I'm using the downloaded Zip version of BaseX, and starts it from the bin folder with the `basexhttp.bat` file.

It seems to work (excepted the setting route) in 8.1 but not in 8.2 anymore.

I do not have eclipse on my machine, just the JRE installed from Oracle.

**Comment by ChristianGruen** [comment]
I just did exactly the same. Maybe an old BaseX process is still running? Could you please try it again and compare the behavior of [BaseX 8.1.1](http://files.basex.org/releases/8.1.1/BaseX811.zip) and the [latest snapshot](http://files.basex.org/releases/latest/BaseX82-20150513.165304.zip)? If 8.1.1 works and the 8.2 snapshot doesn't, could you run the snapshot with the `-d` flag and copy and paste the command-line output?

**Comment by ab34** [comment]
Thank you sir. That is fixed by cleaning up environment variables. 

I confirm that 8.2 solves the issues exposed in this thread.
