### ISSUE TITLE
Process Module: BXPR9999 error on native commands

### ISSUE THREAD

**Issue by ab34** [BaseXdb/basex#1142]
Process Module Functions raise a [BXPR9999](http://docs.basex.org/wiki/Process_Module#Errors) error on native commands invocation on Windows:

Query:
```xquery
try {
  proc:system("dir","C:\")
} catch * {
  'Error [' || $err:code || ']: ' || $err:description
}
```
Result:
```bash
Error [BXPR9999]: Cannot run program "dir": CreateProcess error=2, Le fichier spécifié est introuvable
```

It says that *"The specified file can not be found"*. 

The functions seem to work as expected with an absolute path :
```xquery
proc:execute("C:\MinGW\msys\1.0\bin\dir.exe","C:\")
proc:system("C:\MinGW\msys\1.0\bin\dir.exe","C:\")
```

**Comment by ChristianGruen** [comment]
Your query works on my system (Win 8.1, 64bit, German). I guess it's due to your environment?

**Comment by ab34** [comment]
You're right, thanks. JRE was not in my environment path variables.

**Comment by ChristianGruen** [comment]
FYI… Please only open issues if an error has already been confirmed, of if there is no doubt about it. Otherwise, better write to our mailing list. Thanks for your contributions.

**Comment by ab34** [comment]
Sorry for the disturbance. It was not clear in the documentation that JRE should be in the path for the process module to work.

**Comment by ab34** [comment]
For people finding themselves with the same bug: it appears that putting the JRE in the environment PATH does not solve the issue. 

This has to do with some native windows commands like "dir", "date", and the "echo" command, and also the java command:

```xquery
proc:system("java","--version")
```

It does not return anything.

But the following commands work just fine:

```xquery
proc:system("node","--version")
proc:system("mkdir","C:\test1\")
proc:system("ipconfig")
```

As it may not be directly related to BaseX repo, I close the issue for now, but will update it if ever I find an explanation.

**Comment by ab34** [comment]
I have reproduced the bug in a fresh windows server 2012 machine.

Steps: 
1) Installing the JRE and putting it in the environment path
2) Downloading BaseX and opening the GUI or the DBA
3) Trying native windows command in a query like:
```
proc:system("dir","C:\")
```

**Comment by ChristianGruen** [comment]
I doubt it's something we can solve in BaseX, as we are using the standard Java approach to call external commands. See [ProcFn](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/func/proc/ProcFn.java) and [ProcSystem](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/func/proc/ProcSystem.java) for more information. Suggestions how to "fix" this are welcome.

**Comment by ab34** [comment]
It may be a Java oddity on windows with shell commands. Will look at it and see I find something. Thanks again.

**Comment by ab34** [comment]
Passing the cmd executable as first argument may solve the issue:

```xquery
proc:execute("cmd",'/C dir "C:\"')
```

No UTF-8 support from stdout though, but that is another story. The main issue is closed.
