### ISSUE TITLE
Html Viewer for queries

### ISSUE THREAD

**Issue by puraminy** [BaseXdb/basex#1158]
I am trying to use BaseX for filtering and processing some HTML documents, it shows the source of HTML as the output of queries. I wish it was shown as a rendered HTML too.

Is there any packages for that?

**Comment by ChristianGruen** [comment]
Thanks for your question. I'd like to redirect you to our [basex-talk](http://basex.org/open-source/) mailing list, because we only use the GitHub issue tracker for confirmed bugs and features requests. Thanks.
