### ISSUE TITLE
XQuery: No promotion type error

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1164]
The following query should raise a promotion type error (XPTY0004):

```xquery
function($string) {
  function($int as xs:integer) { 'OUTPUT' }($string)
}('INPUT')
```

**Comment by LeoWoerteler** [comment]
I think this is actually allowed because the spec says that for unused arguments only the occurrence must be checked. After inlining the resulting expression is:
```xquery
let $string := 'INPUT'
return (
  let $int := basex:coerce-to-int($string)
  return 'OUTPUT'
)
```
Since both `let` bindings are unused, they are then dropped.

**Comment by ChristianGruen** [comment]
Even better… Thanks,
