### ISSUE TITLE
Option to include archive file name in document path when creating database

### ISSUE THREAD

**Issue by vincentml** [BaseXdb/basex#1169]
I am using the option "Parse files in archives" when creating databases in the GUI. The source files that I have are organized such that the publication is identified by the file name of the .zip file. The XML files contained within the archive do not have the publication as part of their file name. In the database that is created, the db:path() of each document identifies the path and file name within the archive .zip, but not the name of the archive .zip itself which has the publication name. When browsing a database via webdav or the visualizations in the GUI it would be helpful to have the name of the archive .zip be included in the document path.

For example, currently the create database function will import a document with a path:

articles/article1.xml

Including the archive file name in the path will make the path be:

publication.zip/articles/article1.xml

For compatibility this probably should be an option that can be enabled when needed. In the GUI this option might be placed near the current Parse files in archives checkbox.

[ ] Parse files in archives
[ ] Include archive file name in document path

This new option would be a convenience feature.

**Comment by ChristianGruen** [comment]
Documentation: http://docs.basex.org/wiki/Options#ARCHIVENAME

**Comment by ChristianGruen** [comment]
…available in the [latest snapshot](http://files.basex.org/releases/latest/).
