### ISSUE TITLE
Bug in fn:unparsed-text-lines (8.2.3)

### ISSUE THREAD

**Issue by xokomola** [BaseXdb/basex#1181]
When calling `fn:unparsed-text-lines` with an empty-sequence as first argument there is an NPE.

According to the spec this should simply return with the empty sequence as the signature is this:

    fn:unparsed-text-lines($href as xs:string?) as xs:string* 
    fn:unparsed-text-lines($href as xs:string?, $encoding as xs:string) as xs:string*

Similar functions already behave like this: e.g. `fn:unparsed-text(())` will return ().

**Comment by ChristianGruen** [comment]
Fixed, thanks.
