### ISSUE TITLE
Where clause is rewritten to non-equivalent position predicate

### ISSUE THREAD

**Issue by dirkk** [BaseXdb/basex#1189]
As [reported on the mailing list](https://mailman.uni-konstanz.de/pipermail/basex-talk/2015-September/009523.html):

The query

```
declare context item := document {
  <a>
    <b>
      <c d="1"></c>
    </b>
    <b>
      <c d="2"></c>
    </b>
    <b>
      <c d="3"></c>
    </b>
  </a>
};

for $c at $pos in //b/c
where $pos < 2
return data($c/@d)
```

return `1 2 3`, but should only return `1`. This is due to the query being rewritten to

    for $c_0 in document-node()()/descendant::b/c[position() = 1] return data($c_0/@d)

by the optimizer, which seems to be not equivalent.

**Comment by ChristianGruen** [comment]
Thanks for the observation. Here is yet another example for the buggy optimization:

```xquery
  for $a at $p in (<a/>,<b/>)/.
  where $p < 2
  return $a
```

**Comment by LukasK** [comment]
Maybe it helps with fixing - the following code returns the expected result (switched '<' for 'lt'):

```xquery
for $a at $p in (<a/>,<b/>)/.
where $p lt 2
return $a
```
