### ISSUE TITLE
make basex 64 bits

### ISSUE THREAD

**Issue by innovimax** [BaseXdb/basex#1193]

**Comment by ChristianGruen** [comment]
More details? ;)

**Comment by ChristianGruen** [comment]
As BaseX is based on Java, it supports 64 bit architectures. I have closed this issue, because we need more information to tackle it (ideally directed to the mailing list).

**Comment by innovimax** [comment]
Sorry I wasn't clear at all
Today there is a 32 bits limitation on the number of nodes allowed in the database it is very limiting

**Comment by ChristianGruen** [comment]
I see. I have updated the title and extended the information of #902 (if we decided to increase the limits, we'll look at all current limitations, including the maximum number of nodes per database and the number of namespaces).
