### ISSUE TITLE
Wrong error message "Duplicate declaration of prefix"

### ISSUE THREAD

**Issue by gsf-greece** [BaseXdb/basex#1200]
I don't know if it is related to #1194 but after the update to 8.3 I've noticed when I have declared a namespace in the editor and there are other errors in the script, I only get a false error "Duplicate declaration of prefix 'X'" where X is the prefix for the namespace I declared. 
This happens even if the namespace is not a duplicate. The only way to make it go away and run the script is to fix the real errors, but the editor won't let you know what they are, until you start typing something in the editor again.

**Comment by ChristianGruen** [comment]
I tried to reproduce it, but it doesn't seem to be the case for all queries… Could you please attach a little example?

![editor](https://cloud.githubusercontent.com/assets/196589/10079878/c7119b3c-62ec-11e5-89dd-daee939d51f6.png)

**Comment by gsf-greece** [comment]
Sure, sorry for not providing more info but I was exhausted at the time I made that issue. You have to press run to see the message. So for example if someone gives you a large xquery script and you click run, you will just see the duplicate namespace error.

![basex-bug](https://cloud.githubusercontent.com/assets/6191600/10081081/f17a27ea-62fb-11e5-8163-3258e750200e.PNG)

**Comment by ChristianGruen** [comment]
Confirmed, thanks!

**Comment by ChristianGruen** [comment]
The issue has been fixed in the [http://files.basex.org/releases/latest/](latest snapshot).
