### ISSUE TITLE
Python examples not working

### ISSUE THREAD

**Issue by TobiasGleissner** [BaseXdb/basex#1201]
Python examples in basex/basex-api/src/main/python are not working. 
The Examples get an Access Denied Exception

I suppose the BaseXClient.py is not up-to-date because the examples are working with the python 3 BaseXClient on python2.

**Comment by ChristianGruen** [comment]
That's true; only the Python 3 drivers have been updated so far (see text and links at http://docs.basex.org/wiki/Clients). Would be you be interesting in updating the code snippets?

**Comment by TobiasGleissner** [comment]
I didn't see this, sorry. I don't feel qualified (yet) in updating the
code snippets. Anyway if I find time I'll certainly try.
