### ISSUE TITLE
castable returns wrong result

### ISSUE THREAD

**Issue by gsf-greece** [BaseXdb/basex#1206]
Hello, I'm having some trouble with castable in basex editor. If let's say I have an XML file
`<Elements>`
  `<element>5.234,8</element>`
  `<element>3</element>`
`</Elements>`

And I try to do `//element[1] castable as xs:double` I get true. However this should be false, and `data(//element[1]) castable as xs:double` returns false.  (by the way saxon returns false)

This happens at least in 8.2.3 and latest beta.

**Comment by ChristianGruen** [comment]
Yes, looks like a bug. Thanks for the report.

```xml
<commands>
  <create-db name='x'>
    <x>a</x>
  </create-db>
  <xquery>
    /x castable as xs:double 
  </xquery>
  <close/>
</commands>
```

**Comment by ChristianGruen** [comment]
A new [snapshot](http://files.basex.org/releases/latest) is available.

**Comment by gsf-greece** [comment]
Thank you very much!
