### ISSUE TITLE
map and array's Effective boolean value not defined

### ISSUE THREAD

**Issue by james-jw** [BaseXdb/basex#1208]
I would assume the following would return true:

```xquery
boolean(map {})
```
However it throws an exception: <code>err:FORG0006</code> Effective boolean value not defined for map(*): map { }. Same goes for array:

```xquery
boolean(array {})
```

Is this correct? In most other functional languages such as javascript this would report true. I am trying to find in the XQuery 3.1 spec where the effective value is defined with no luck. Its not even mentioned as implementation specific or not. 

Thanks for your work on BaseX is excellent!

**Comment by LeoWoerteler** [comment]
Do you mean `exists(map {})`? It is not clear to me what the boolean equivalent of a map is. Is an empty map `true` or `false`? What about `map { false(): false() }`?

The XQuery standard is [very clear about this case](http://www.w3.org/TR/xquery-30/#id-ebv) and BaseX implements it correctly.

If you have general questions about XQuery, the `xquery-talk` and `basex-talk` mailing lists are a good starting point. This issue tracker should only be used to report actual bugs and glitches of BaseX.

**Comment by james-jw** [comment]
I am taking a hint from javascript. An object regardless of contents is true. This goes for an array too. 

So your example: map { false(): false() } is true. False in my mind would be the absence of a value. You could also think of it like: (map { }) where its a sequence of 1 map... and thus true() as well.

I read that section in the spec but its not clear where array or map are noted. Thanks for your time.
