### ISSUE TITLE
Inconsistent URI serialization

### ISSUE THREAD

**Issue by VincentBiragnet** [BaseXdb/basex#1215]
Consider the following query
```xquery
resolve-uri("file:///b.xml"),
resolve-uri("a.xml","file:///b.xml")
```
the result is
``` 
file:///b.xml
file:/a.xml
```
It would be nice if both results had the same number of slashes.

**Comment by ChristianGruen** [comment]
This is due to bugs in the Java classes (it can also be observed with other Java query processors like Saxon). I’ve merged this with another issues (#928), which I’ve just reopened.

**Comment by ChristianGruen** [comment]
URI validation (#928) has been fixed. As this issue still needs to be resolved, I’ve reopened it.

**Comment by ChristianGruen** [comment]
One more surprise: `resolve-uri("a.xml","file://b.xml")` yields `file://b.xmla.xml`. eXist-db returns the same result, Saxon returns `file://b.xml/a.xml`, Zorba raises `FORG0002`.
