### ISSUE TITLE
SAXSerializer emits qname instead of local name in contentHandler.endElement()

### ISSUE THREAD

**Issue by ksclarke** [BaseXdb/basex#1226]
At https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/io/serial/SAXSerializer.java#L200

    final String name = string(elem.string());
    contentHandler.endElement("", name, name);

The qualified name (for an element that has a qualified name) comes out as the local name via the contentHandler.endElement call (and no uri is output, just an empty string).

This is different from the startElement (https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/io/serial/SAXSerializer.java#L183) where the local name and qname are handled correctly:

    final String uri = string(namespaces.get(elem.prefix()));
    final String lname = string(elem.local());
    final String rname = string(elem.string());
    contentHandler.startElement(uri, lname, rname, attrs);

**Comment by ChristianGruen** [comment]
Completely true. Thanks for the code pointers. Could you please check the new version? A [new snapshot](http://files.basex.org/releases/latest/) is available, too.

**Comment by ksclarke** [comment]
Yes, that's better. Thanks!
