### ISSUE TITLE
db:rename does not always work for binary files or paths to binary files

### ISSUE THREAD

**Issue by ewrayjohnson** [BaseXdb/basex#1227]
Example Files:

folder1/file1.png
folder4/folder5/file6.png

db:rename('db', 'folder1', 'folder2/folder3')  (: fails - but reports success :)
db:rename('db', 'folder5/folder6', 'folder7') (: works :)

**Comment by ChristianGruen** [comment]
Thanks. A new snapshot is available in a few minutes.
