### ISSUE TITLE
Java Binding: Improve camel case rewrite

### ISSUE THREAD

**Issue by dirkk** [BaseXdb/basex#1230]
Currently, if you want to call a Java function (via the Java bindings) which is named:

    X.getPDFName()

you will have to call it using

    X:get-p-d-f-name()

It would be more convenient to use the much more expected

    X:get-pdf-name()

instead.

**Comment by ChristianGruen** [comment]
Problem: We would need to check through numerous alternatives, or completely ignore case when matching the functions:

```
getPdfName:
• getPDFName
• getPdfName
• getPdfNAME
• getPDFNAME
…
```
