### ISSUE TITLE
geo:buffer fails

### ISSUE THREAD

**Issue by james-jw** [BaseXdb/basex#1245]
The following example from the website does not appear to work

```xquery
import module namespace geo = "http://expath.org/ns/geo";
declare namespace gml='http://www.opengis.net/gml';
let $Polygon:= <gml:Polygon>
                   <gml:outerBoundaryIs>
                      <gml:LinearRing><gml:coordinates>10,10 20,10 30,40 20,40 10,10</gml:coordinates></gml:LinearRing>
                   </gml:outerBoundaryIs>
               </gml:Polygon>
                             
return geo:buffer($Polygon, 3)
```

```xquery
let $Point := 
<gml:Point xmlns:gml="http://www.opengis.net/gml">
  <gml:coordinates>-86.77590599999999 32.63144109090909</gml:coordinates>
</gml:Point>
return geo:buffer($Point, 1)
```

I cannot seem to get this function to work ever. The error is always:
``
[FORG0006] Invalid arguments: buffer(ANode, Dbl) expected, buffer(element(), xs:decimal) found.
``

**Comment by ChristianGruen** [comment]
I have [fixed the example](http://docs.basex.org/wiki/Geo_Module#geo:buffer), the second argument is now of type `xs:double`. The code has been updated as well: other numbers will implicitly be cast to doubles. Thanks.
