### ISSUE TITLE
geo module genereated geometries not operable in future geo calls

### ISSUE THREAD

**Issue by james-jw** [BaseXdb/basex#1246]
For example:

```xquery
let $Polygon:= <gml:Polygon>
                   <gml:outerBoundaryIs>
                      <gml:LinearRing><gml:coordinates>10,10 20,10 30,40 20,40 10,10</gml:coordinates></gml:LinearRing>
                   </gml:outerBoundaryIs>
               </gml:Polygon>
                             
return geo:buffer($Polygon, xs:double(3)) 
        => geo:envelope()
```

Or for example:
```xquery
let $env := geo:envelope($Polygon)
return
   geo:intersection($env, $Polygon)
```

In all cases this error is returned:
``
[FORG0006] element() expected, document-node() found: document-node 
``

**Comment by ChristianGruen** [comment]
Wow. It seems it hasn’t been tested for a while now. I revised all functions that are supposed to return element instead of document node, and I hope it’s working now. The new snapshop is [online](http://files.basex.org/releases/latest/).

**Comment by james-jw** [comment]
Thanks for the quick fix!
