### ISSUE TITLE
xquery:eval cannot return maps or arrays?

### ISSUE THREAD

**Issue by james-jw** [BaseXdb/basex#1270]
Maybe this is not supposed to be supported, but this does not work as I would expect:

```xquery
xquery:eval('map { "test": "test" }')
```

The error is ``Items of type map(*) have no string representation``

Same goes arrays.

**Comment by ChristianGruen** [comment]
It should work with BaseX 8.4. Maybe you tried an older version?

**Comment by james-jw** [comment]
Yeah, sorry that server was still on 8.3.1. 

Ill be more careful next time to make sure I am using the latest.
Cheers

**Comment by ChristianGruen** [comment]
No problem!
