### ISSUE TITLE
Option for path to settings

### ISSUE THREAD

**Issue by croizier** [BaseXdb/basex#1282]
For now, settings live in the .basex file, which itself lives in the basex folder, so you can not configure a new version of BaseX without modifying its content.

We would like to put data in a separate folder, and update the BaseX engine just by unzipping the archive that you provide on the web. For this to work, we need a `-b` option to tell ``basexhttp`` where it can find the file that replaces its own .basex file (which gets ignored):` $BASEX/bin/basexhttp -b $CONF/basex.txt `.

**Comment by ChristianGruen** [comment]
Did you already try to set the system property `org.basex.path` to `$CONF`? You’ll need to rename `basex.txt` to `.basex`, though. See http://docs.basex.org/wiki/Configuration#Home_Directory for more details.

**Comment by croizier** [comment]
Setting `org.basex.path` works fine. Thanks.
