### ISSUE TITLE
file:path-to-native() on windows network

### ISSUE THREAD

**Issue by apb2006** [BaseXdb/basex#1288]
For a local file, as expected:
````
"C:\tmp\aa.html"
=>file:path-to-uri()=>trace()
=>file:path-to-native()=>trace()
````
Evaluating:
xs:anyURI("file:///C:/tmp/aa.html")
"C:\tmp\aa.html"

For a network file `file:path-to-native` fails
````
"\\ODROID-JESSIE\sda1\readme.txt"
=>file:path-to-uri()=>trace()
=>file:path-to-native()=>trace()
````
Evaluating:
xs:anyURI("file://ODROID-JESSIE/sda1/readme.txt")
[file:not-found] 'C:\ODROID-JESSIE\sda1\readme.txt' does not exist.
file://ODROID-JESSIE/sda1/readme.txt

**Comment by ChristianGruen** [comment]
I’m not sure if we can easily fix that, because the Java code we use for resolving the path is [very simple](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/func/file/FilePathToNative.java#L18):

* The input is rewritten to a file path: `return Paths.get(IOUrl.isFileURL(path) ? IOUrl.toFile(path) : path);`
* This Java path will be rewritten to a "real path" (and here I assume the error occurs): `path.toRealPath();`
* A slash will be appended to the resulting path if it’s a directory.

Could you check for us what is returned by the following Java code?

```java
import java.nio.file.*;

public class NetworkPaths {
  public static void main(String... args) throws Exception {
    String string = "\\\\ODROID-JESSIE\\sda1\\readme.txt";

    Path path = Paths.get(string);
    System.out.println("Path: " + path);

    try {
      System.out.println("Native path: " + path.toRealPath());
    } catch(Exception ex) {
      System.err.println(ex);
    }
    try {
      System.out.println("Native path (no links): " + path.toRealPath(LinkOption.NOFOLLOW_LINKS));
    } catch(Exception ex) {
      System.err.println(ex);
    }
  }
}
```

**Comment by ChristianGruen** [comment]
I’m pretty sure I’ve found a solution, so I’ve already closed your issues. Feel free to test the [new snapshot](http://files.basex.org/releases/latest/) (available in a few minutes) and reopen the issue if I overlooked something.

**Comment by apb2006** [comment]
Thanks, sorry not able to test at the moment. Will take a look next week.

**Comment by apb2006** [comment]
We seem to be down a familiar rabbit hole...

````
"\\ODROID-JESSIE\sda1\readme.txt"
=>file:path-to-uri()=>trace()
=>file:path-to-native()=>trace()
````
gives:
````
Improper use? Potential bug? Your feedback is welcome:
Contact: basex-talk@mailman.uni-konstanz.de
Version: BaseX 8.5 beta e56ef2d
Java: Oracle Corporation, 1.8.0_91
OS: Windows 10, amd64
Stack Trace: 
java.lang.IllegalArgumentException: URI has an authority component
	at java.io.File.<init>(Unknown Source)
	at org.basex.io.IOFile.<init>(IOFile.java:60)
	at org.basex.io.IOUrl.toFile(IOUrl.java:131)
	at org.basex.query.func.StandardFunc.toPath(StandardFunc.java:212)
	at org.basex.query.func.StandardFunc.toPath(StandardFunc.java:201)
	at org.basex.query.func.file.FilePathToNative.item(FilePathToNative.java:18)
	at org.basex.query.func.file.FileFn.item(FileFn.java:25)
	at org.basex.query.func.file.FilePathToNative.item(FilePathToNative.java:1)
	at org.basex.query.expr.ParseExpr.iter(ParseExpr.java:44)
	at org.basex.query.MainModule.iter(MainModule.java:119)
	at org.basex.query.QueryContext.iter(QueryContext.java:342)
	at org.basex.query.QueryContext.cache(QueryContext.java:642)
	at org.basex.query.QueryProcessor.cache(QueryProcessor.java:114)
	at org.basex.core.cmd.AQuery.query(AQuery.java:84)
	at org.basex.core.cmd.XQuery.run(XQuery.java:22)
	at org.basex.core.Command.run(Command.java:398)
	at org.basex.core.Command.execute(Command.java:100)
	at org.basex.gui.GUI.exec(GUI.java:469)
	at org.basex.gui.GUI.access$4(GUI.java:422)
	at org.basex.gui.GUI$7.run(GUI.java:411)
Query:
file:path-to-native("file://ODROID-JESSIE/sda1/readme.txt")
Query plan:
<QueryPlan compiled="true">
  <FilePathToNative name="path-to-native(path)">
    <Str value="file://ODROID-JESSIE/sda1/readme.txt" type="xs:string"/>
  </FilePathToNative>
</QueryPlan>
````
This 
`file:path-to-native("file:////ODROID-JESSIE/sda1/readme.txt")`
Gives the answer I was looking for 
`\\ODROID-JESSIE\sda1\readme.txt`
http://stackoverflow.com/a/1878071/3210344

But maybe this is a cant fix issue.

**Comment by apb2006** [comment]
The code sample output is:
````
Path: \\ODROID-JESSIE\sda1\readme.txt
Native path: \\ODROID-JESSIE\sda1\readme.txt
Native path (no links): \\ODROID-JESSIE\sda1\readme.txt
````

**Comment by ChristianGruen** [comment]
Thanks for doing some research. Indeed it’s the java.io.File class that cannot cope with conventional network paths. I’m now using java.nio.Paths for all File Module URI conversions. The new snapshot is being uploaded.

**Comment by apb2006** [comment]
Works for me. Thanks
