### ISSUE TITLE
how can i remove some issue

### ISSUE THREAD

**Issue by liujie15838028035** [BaseXdb/basex#1291]
when i use github , i want to remove some issue , how can i remove it ?

**Comment by ChristianGruen** [comment]
That’s not possible; you need to close it.

**Comment by liujie15838028035** [comment]
for example, issue1 and issue2   are the same feature , i have create it .
how can i merge it.

**Comment by ChristianGruen** [comment]
As far as I know, you cannot merge issues. – Please direct questions like this to the GitHub team; it’s not really to BaseX. Thanks.
