### ISSUE TITLE
basexhttp reports success even though it fails to start

### ISSUE THREAD

**Issue by gioele** [BaseXdb/basex#1294]
When `basexhttp` is asked to start as a service (`-S` option) it will always reports that it has successfully started even when a failure happened, for example port 8984 is already occupied by another process.

Launching `basexhttp` without the `-S` option will correctly report that the port is already in use  and the correct exit status code will be returned to the shell.

BaseX 8.4.3 running on RHEL 6.

## How to reproduce

1. Run an application that binds port 1984 or port 8984 (for example another instance of BaseX, but any application will do).
2. Launch BaseX using `basexhttp -S`.

### Actual result

    $ ./bin/basexhttp -S
    HTTP Server was started (port: 8984).
    $ echo $?
    0

### Expected result

    $ ./bin/basexhttp -S
    java.io.IOException: Server is running or permission was denied (port: 1984).
    […]
    HTTP Server is running or permission was denied (port: 8984).
    $ echo $?
    1

**Comment by ChristianGruen** [comment]
As the BaseX server is run in a different JVM, it’s not that easy to find out in a given time if the process has succeeded or will fail; but I revised the current solution, and I would like to hear your feedback on the [latest snapshot](http://files.basex.org/releases/latest/).
