### ISSUE TITLE
No error is logged if the data directory is unreadable

### ISSUE THREAD

**Issue by gioele** [BaseXdb/basex#1295]
No error nor warning will be logged in case the `data/` directory is not readable by the server process, for example because the daemon has been started under a user that is not the owner of the `data` directory.

This happens when the server has been started in service mode (`-S` option).

It would be nice if BaseX could log this kind of common but nasty to debug problems.

This problem occurs with BaseX 8.4.4 on RHEL6.

**Comment by ChristianGruen** [comment]
Out of interest: What happens in your case if the server is started normally (without -S)?

If you use Linux, and if you want to catch stdout/stderr output, the better alternative for -S is to start the server as an ordinary background process.

**Comment by ChristianGruen** [comment]
I don’t find a good answer on where we should log output that’s generated by in service mode, so I’m closing this for now. Using a background process, or [YAJSW](http://docs.basex.org/wiki/YAJSW), will give you more options.
