### ISSUE TITLE
Map: remove and check values

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1297]
Our current map implementation might not be as 100% immutable as it should be:

**Query:**

```xquery
let $map := map { 'A_': (), 'B@': (), 'C!': () }
return (
  map:remove($map, 'A_'),
  map:remove($map, 'B@')
)
```

**Result:**

```xquery
map { "B@": (), "C!": () }
map { "C!": (), "C!": () }
```

It’s always the second result that’s buggy, even if the two `map:remove` calls are swapped.

**Comment by ChristianGruen** [comment]
…all three strings have the same hash code (2110).

**Comment by ChristianGruen** [comment]
No bug of the map core code, as expected… Instead, [Array#delete](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/util/Array.java#L115-L119) modifies the existing array before copying it. Sigh.

**Comment by LeoWoerteler** [comment]
Phew, I was already worried...
