### ISSUE TITLE
Documentation: Upgrade to latest MediaWiki

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1303]
Our Wiki should be updated to the latest version (which provides better rendering support for mobile devices, etc).

Details: https://www.mediawiki.org/wiki/Manual:Upgrading/de

**Comment by micheee** [comment]
I think I could do that  👍

**Comment by ChristianGruen** [comment]
Any volunteer? ;)

**Comment by micheee** [comment]
@mgaerber, sounds like a good idea :)

I thought of migrating our documentation to hugo and have it stored alongside our sources.

That way we could keep a connection between our releases and the documentation, I'd be happy to do it in LwDita, care to join me maybe in the beginning of August?


I think the part that involves most manual work will be converting media-wiki markup to markdown/lwdita... ;) I already started it once or twice, but never endured until the end! :)

**Comment by mgaerber** [comment]
Yes, we'd like to support this. The (very good) current documentation is one of basex USPs.

With LwDita, there's now a standard mapping from Markdown to html or xml [1]. You can mix them together, too [2].

For the output generation, there are several options: From Jekyll, Hugo to DITA-OT.

[1] http://docs.oasis-open.org/dita/LwDITA/v1.0/cn01/LwDITA-v1.0-cn01.html#concept_ig4_cfb_dy
[2] https://github.com/dita-users/demo-project/blob/master/clever-tank/source/allgemeines/r_garantie.md

**Comment by micheee** [comment]
=> cool, I'll add that to our agenda, might finally be a reason for us to come and see your new offices? 👍

**Comment by ChristianGruen** [comment]
March 2020, JWeiland will discontinue support for PHP 5. We’ll need to upgrade or look for an alternative. I’d still vote for an upgrade, and pursue possible alternatives in parallel.

**Comment by ChristianGruen** [comment]
Documentation was upgraded in 2020.
