### ISSUE TITLE
JTS library version

### ISSUE THREAD

**Issue by gsf-greece** [BaseXdb/basex#1305]
I noticed BaseX is using JTS version 1.13. While I was searching stuff about Geo data processing, I noticed that JTS version 1.14 has been released for some time, but it has a different artifact id. I don't know if you were aware of this so I made a ticket about this
The artifacts can be found here: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.vividsolutions%22

**Comment by gsf-greece** [comment]
I can also see there is another GIS java library http://geotools.org/
I wonder if it can be used from BaseX in the future. I have some XML files that use gml3 and It would be nice to be able to use BaseX to read and calculate data using the BaseX Geo Module.

**Comment by ChristianGruen** [comment]
> I noticed that JTS version 1.14 has been released for some time, but it has a different artifact id.

Thanks for the hint to JTS 1.14. I remember we have some issues with previous updates of the JTS suite. Have you already gathered some experiences with the latest version? Did you find some info what has been changed in that version?

> I wonder if it can be used from BaseX in the future.

I assume it could be, but we would need to find someone who is interested in integrating it. And as I see, the library is pretty large (70 mb), so it wouldn’t make too much sense to include it in our  regular releases.

**Comment by gsf-greece** [comment]
Hi Christian, I don't have any experience with the latest version. I only started looking at the Geo Module yesterday. I was just looking if the latest version supported GML 3 and I noticed there is a new version. I've attached the changelog.
[forbasex.zip](https://github.com/BaseXdb/basex/files/321767/forbasex.zip)

About GeoTools, I could fork BaseX and try to implement it myself, but I'm not sure that will work.

**Comment by ChristianGruen** [comment]
Thanks for the change logs. Looks good so far; I think I’ll give it a try soon.

And thanks for the offer to have a look at GeoTools. We could possibly provide an external GeoTools package, similar to the http://files.basex.org/modules/org/basex/modules/Hello/HelloWorld.jar package. Please have a look at our documentation for more examples: http://docs.basex.org/wiki/Repository#Packaging. More questions are welcome.

**Comment by ChristianGruen** [comment]
I finally had a look at your issue again, and I saw that Version 1.14 of the JTS core library is apparently not available in the maven repository: http://repo1.maven.org/maven2/com/vividsolutions/jts/.

Talking about GeoTools… Did you have a second look at BaseX and the library?

**Comment by ChristianGruen** [comment]
So true ;) Should be working now (37291aa552a8fdb295a48a4d46b51ba64c703634). – I’ll close this issue for now, feel free to reopen it!

**Comment by ChristianGruen** [comment]
Sigh… I turned out that some of our JUnit tests are now failing with JTS 1.14, so I’ve just downgraded to 1.13 again.
