### ISSUE TITLE
GML parsing exception error code include hash code

### ISSUE THREAD

**Issue by gsf-greece** [BaseXdb/basex#1306]
I was playing around with the Geo Module and I noticed this output when a parsing error occurs. I don't know if this is intentional or not. It's not something important, but I thought I should report it

    import module namespace geo = "http://expath.org/ns/geo";
    declare namespace gml = "http://www.opengis.net/gml";

    let $x := <gml:Point><gml:coordinates>a</gml:coordinates></gml:Point>
    return
    try { geo:is-simple($x) } catch * { $err:code || " " || $err:description}

Outputs [B@7eb167f9:GEO0002 Parsing GML 2.0: java.lang.NumberFormatException: For input string: "a"

**Comment by ChristianGruen** [comment]
Thanks for the hint; the output has been [fixed](7e83c5d249bcabbc77a4bb5966c8bc207499d28f).

```
experrs:GEO204d Parsing GML 2.0: java.lang.NumberFormatException: For input string: "a"
```
