### ISSUE TITLE
how can i use maven dependency your basex-core

### ISSUE THREAD

**Issue by liujie15838028035** [BaseXdb/basex#1307]
how can i use maven dependency your basex-core ?
what should i do in maven pom.xml?

**Comment by dirkk** [comment]
We do use the issue tracker only for tracking bugs and feature request, not for support tickets. Please use our mailing list at https://mailman.uni-konstanz.de/mailman/listinfo/basex-talk for questions like these, we and many of our users are happy to help there!

Nonetheless, you should find the answer to your question in our documentation at http://docs.basex.org/wiki/Maven

**Comment by liujie15838028035** [comment]
@dirkk  , thanks ,  i see  http://docs.basex.org/wiki/Maven
Artifacts

You can easily embed BaseX into your own Maven projects by adding the following XML snippets to your pom.xml file:
<repositories>
  <repository>
    <id>basex</id>
    <name>BaseX Maven Repository</name>
    <url>http://files.basex.org/maven</url>
  </repository>
</repositories>
BaseX Main Package
	
<dependency>
  <groupId>org.basex</groupId>
  <artifactId>basex</artifactId>
  <version>7.6</version>
</dependency>

i know how to  dependency your basex-core it . 

if i have a project on github , named xx-core,  how can i dependency it in other project, what should i do in pom.xml?
