### ISSUE TITLE
Performance: TrieList.put() can avoid copying the keys array if the key already exists

### ISSUE THREAD

**Issue by mcoblenz** [BaseXdb/basex#1310]
If the key to be replaced in the trie already exists, put() does this:

`return new TrieList(h, keys.clone(), vs);`

But there's no need to clone keys here because it's immutable. It's safe to share it. Of course, values still has to be copied.

**Comment by ChristianGruen** [comment]
Sounds absolutely reasonable. I’m assigning this to @LeoWoerteler as well, our blessed TrieList implementor (→ https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/value/map/TrieList.java#L95).
