### ISSUE TITLE
Centralized Jobs Handling

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1314]
BaseX Jobs (commands, queries, RESTXQ requests) will be organized centrally. This way, all running jobs can be listed, monitored and gracefully stopped. The [Async Module](https://github.com/BaseXdb/basex/issues/1272) will be split up and replaced with a Jobs Module:

**Refactorings**

* [x] move Async functions to Jobs Module
* [x] update namespace URIs, error codes, tests
* [x] move `async:fork-join` to `xquery:fork-join`
* [x] rename `jobs:ids` to `jobs:list`

**Core**

* [x] include commands that are still on the queue

**Functions**

* [x] `jobs:current`: returns id of current job
* [x] `jobs:list-details`: job info: id, type, timestamp, user, …?
* [x] `jobs:schedule`: set caching default to `false` or `0` ?
* [x] Support for scheduled jobs (start time, delay, interval)

**Options**

* [x] `ASYNCTIMEOUT` → `CACHETIMEOUT`

**Commands**

* [x] `JOBS [list | kill | result]` ?

**DBA**

* [x] list running jobs in table
* [x] allow killing of jobs

**Documentation:**
* [x] move Async Module to http://docs.basex.org/wiki/Jobs_Module
* [x] add new functions and examples
* [x] `ASYNCTIMEOUT` → `CACHETIMEOUT`

**Tests:**
* [x] Functions
* [x] Commands

More suggestions are welcome.

**Comment by apb2006** [comment]
It appears `jobs:list-details()`  only lists running/queued jobs. I had expected,  and can see uses for, this to include those shown in `jobs:results()` as well.

**Comment by ChristianGruen** [comment]
Thanks for the hint. I think I could add them as well.

**Comment by ChristianGruen** [comment]
After some more thoughts, I’m not sure if I’ll really going to merge jobs and job results. Internally, I’m handling them separatedly, and I would need to additionally cache information on the original jobs until the results will be retrieved by someone. But it’s probably confusing to retrieve a result with the id of a job that doesn’t exist anymore. Hm.

**Comment by apb2006** [comment]
The uses I had in mind are:
1. I would like to associate some application level metadata with a job. As list-details gives access to the query I could put this in structured comments within the XQuery. Any alternative might be  a new jobs:schedule option {,"tag:"my metadata"} and some method to read this with the results
2. I would like to know the execution time of a completed query.

**Comment by ChristianGruen** [comment]
I have now merged the ids of `jobs:results` into `jobs:list-details` (see http://docs.basex.org/wiki/Jobs_Module). `jobs:list-details` will additionally list all scheduled jobs.

The new snapshot is online in 10 minutes; feedback is welcome!
