### ISSUE TITLE
Improve release note?

### ISSUE THREAD

**Issue by jameshnsears** [BaseXdb/basex#1318]
When a new version of basex comes out should the "release note" mention compatibility with data from a prior release?

For example "http://basex.org/about-us/news/newsdetails/basex-85-the-summer-edition/8065ee07f07470312c7b62af2321f27e/" mentions nothing about what I should do with data from 8.4.4.

It would be nice to easily know if I have to rebuild a prior version database against the latest version.

**Comment by ChristianGruen** [comment]
Hi; the latest version will only (possibly) change with major updates. We haven’t planned any changes in the database layout for BaseX 9.0, but if we do, we’ll let you know.
