### ISSUE TITLE
xquery:eval no longer works in dba in BaseX 8.5

### ISSUE THREAD

**Issue by vincentml** [BaseXdb/basex#1319]
Thanks for the new version of BaseX! After upgrading I am finding that some queries that previously worked in DBA now generate an error “[bxerr:BXXQ0005] Nested query evaluation is not allowed.”

For example, go to the Queries screen in DBA and run `xquery:eval("1 + 3")`. Under 8.4.4 this returns the expected result `4`. Under 8.5 I am seeing the error message “[bxerr:BXXQ0005] Nested query evaluation is not allowed.”

Previously I could use string concatenation to construct a query and then evaluate it with xquery:eval. In some cases the query completes much faster this way. Based on previous advice on the mailing list that when a database is referenced directly BaseX can do more optimizations than when the database is referenced by a variable, I am writing queries like this to query from multiple databases:

for $db in db:list()
let $q := "db:open('" || $db || "')/…"
return xquery:eval($q)

After looking around, this problem might be related to issue #1298 and [this commit](https://github.com/BaseXdb/basex/commit/e600098a6e85c265f1c35b15ccdb33eb75c92fbc).

Would it cause any problems to allow 3 nested query evaluations instead of 2?

**Comment by ChristianGruen** [comment]
You found the relevant commit and issue… I think it should be safe to allow a higher number of nested calls. 8.5.1 will be due next week.
