### ISSUE TITLE
Schema Validation

### ISSUE THREAD

**Issue by gsf-greece** [BaseXdb/basex#1324]
I have an issue with BaseX Schema validation. This happens at least in all versions from 8.4.4 to 8.5.1

This happens with or without XercesImpl.jar inside the classpath. **Some times**, when BaseX tries to validate a file, I get an error like this:

`[bxerr:BXVA0002] Validation could not be started: Resource "\GB_D_ModelledAssessmentMethods_corrupt2\GB_D_ModelledAssessmentMethods_corrupt2.xml (The system cannot find the path specified)" not found.`
The first directory, is just a "copy" of the XML file name, it doesn't really exists. So something is duplicating it, I don't know if it's BaseX or Xerces that have this bug.

The function I use to validate XML files is:
`let $validationResult := validate:xsd-report(doc($source_url))`
while $source_url is an xs:string external variable that I pass as an argument to the validating function.

After I restarted BaseX the error is gone, and validation works on the same file.

This has been reproduced on Windows with BaseXGUI, and on Linux using Docker image of basexhttp

**Comment by ChristianGruen** [comment]
> So something is duplicating it, I don't know if it's BaseX or Xerces that have this bug.

Definitely difficult to reproduce for us. Could you please provide us with a self-contained example and reopen the bug? Thanks in advance.

**Comment by apb2006** [comment]
Can you try
`let $validationResult := validate:xsd-report($source_url)`
instead of:
`let $validationResult := validate:xsd-report(doc($source_url))`

And if so does it make any difference?

**Comment by gsf-greece** [comment]
Thanks for taking a look into this. At the moment I think of this issue as having two states, one when is working normally and one when it is on stuck state. I'm "lucky" enough to have my production system in a stuck state. When in stuck state, If I change validate:xsd-report(doc($source_url)) to validate:xsd-report($source_url), my scripts run fine. If I change it back to validate:xsd-report(doc($source_url)), they stop running again.
The error message is a URL that does not exist for example: '[bxerr:BXVA0002] Validation could not be started: Resource "http://cdrtest.eionet.europa.eu/lu/eu/aqd/b/envv49nmg/LU_DataFlowB_2014_Correction_corruptB30_B34.xmlLU_DataFlowB_2014_Correction_corruptB30_B34.xml" not found.
This URL does not exist, for some reason the file name has been duplicated by something.

I don't know if this has to do with any "special" characters in the URL.
The reason I'm using doc($source_url) is to keep the validation from downloading the file more times than necessary(usually 1). I don't know if it is the best approach.

Unfortunately I can't reproduce this issue it on demand, it's happening at rare occasions.  
My production environment is "stuck" at this stage at the moment. And while I know about this issue for 3-4 days, it only happened on my BaseX GUI today. I restared the GUI and it was working fine again. 
I've been reading the code for the past couple of hours, and I think it has something to do with the read() method in this file:

https://github.com/BaseXdb/basex/blob/b8c1ae7738664aa3912ade783b8a01a0a2285d25/basex-core/src/main/java/org/basex/query/func/validate/ValidateFn.java
