### ISSUE TITLE
User Management: Add custom section

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1325]
All BaseX users are stored in the `users.xml` configuration file. This file could be extended by a custom `info` section. Example:

```xml
<users>
  <user name="john" permission="read">
    <password algorithm="digest">
      <hash>...</hash>
    </password>
    <password algorithm="salted-sha256">
      <salt>...</salt>
      <hash>...</hash>
    </password>
    <info>
      <name>John Smith</name>
      <group>editor</group>
    </info>
  </user>
  <info>
    <groups>
      <group>editor</group>
      <group>author</group>
    </groups>
    <user name="john" group="editor">
      <name>John O’Neil</name>
    </user>
  </info>
</users>
```

The User Module could be enhanced by two simple functions:

**Retrieve/update custom information:**

```xquery
user:info() as element(info),
user:update-info($info as element(info)) as empty-sequence()
```

Custom user information can then be maintained as follows:

```xquery
(: Create user :)
let $user := 'jack', $pw := 'pw', $group = 'editor', $name = 'Jack Jackson'
return (
  user:create($user, $pw),
  user:update-info(user:info() update
    insert node <user name='jack' group='{ $group }'>{ $name }</user> into .
  )
)
```

```xquery
(: Update user group :)
let $user := 'jack', $group = 'writer'
return (
  user:drop($user),
  user:update-info(user:info() update
    replace value of node user[@name='jack']/@group with $group
  )
)
```

```xquery
(: Delete user :)
let $user := 'jack'
return (
  user:drop($user),
  user:update-info(user:info() update delete node user[@name='jack'])
)
```

**Comment by mgaerber** [comment]
`<info>` would be a nice addition.

I was also thinking about adding a `<groups>` element to have a place for storing group names. Could be either:
`<groups>
   <group name="manager">
        <user name="john">
   </group>
</groups>`

or by adding the group to user/info.

**Comment by ChristianGruen** [comment]
I have revised my initial comment. Instead of adding 3-5 new functions, I now tend to add two simple functions for reading and writing the custom info element.

**Comment by ChristianGruen** [comment]
Done…
* http://docs.basex.org/wiki/User_Module#user:update-info
* http://docs.basex.org/wiki/User_Module#user:info
