### ISSUE TITLE
User Module: Check password

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1326]
Add function to simplify password checks:

**Signatures**:

```xquery
user:check($name as xs:string, $password as xs:string) as empty-sequence(),
```

**Summary**: Checks if a user with the specified $name and $password exists.

**Errors**:

* `user:unknown`: User does not exist
* `user:password`: Wrong password was specified

**Details**:

The following XQuery function is equivalent:

```xquery
declare function user:check($name as xs:string, $password as xs:string) {
  let $pw := user:list-details($name)/password[@algorithm = 'salted-sha256']
  let $hash := lower-case(string(xs:hexBinary(hash:sha256($pw/salt || $password))))
  where $pw/hash != $hash
  return error(xs:QName('user:password'), 'Wrong password: ' || $password || '.')
};
```

**Comment by mgaerber** [comment]
+1 check would be useful, also a function that returns what my (personal) rights are for a resource, e.g. `check-rights($db)` that I can use with being admin user

**Comment by ChristianGruen** [comment]
> returns what my (personal) rights are for a resource

Thanks. What would you expect the function to return exactly?

**Comment by ChristianGruen** [comment]
@mgaerber: Maybe we could modify `user:list-details`: If called by non-admins, the output could be limited to the current user. Would this help?

**Comment by mgaerber** [comment]
Yes, this would do the trick. The result would then be a list of (my) global and local permissions, correct?

**Comment by ChristianGruen** [comment]
> The result would then be a list of (my) global and local permissions, correct?

Right. The output can looks like this:

```xml
<user name="user" permission="none">
  <password algorithm="digest">
    <hash>851aeb08df60160cd656ae9963b277f7</hash>
  </password>
  <password algorithm="salted-sha256">
    <salt>0193382589214601</salt>
    <hash>1d172754e4a2413910de454a4b92739a100e977d7b7dce846d624787112fb7b9</hash>
  </password>
  <database pattern="f*" permission="write"/>
</user>
```

Documentation:
* http://docs.basex.org/wiki/User_Module#user:check
* http://docs.basex.org/wiki/User_Module#user:list-details
