### ISSUE TITLE
Jobs Module: Assign custom Job IDs

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1331]
Example:

```xquery
jobs:eval("db:optimize('db')", (), map { 'id': 'optimize-database' })
```

**Comment by micheee** [comment]
I'd suggest the following details:

- [ ] Assigning IDs should be optional, a new ID should be generated otherwise
- [ ] Trying to assign an duplicate ID will throw an error()

**Comment by ChristianGruen** [comment]
Perfect, this is what I had in mind as well!

**Comment by ChristianGruen** [comment]
http://docs.basex.org/wiki/Jobs_Module#jobs:eval
