### ISSUE TITLE
Python API no attribute Session

### ISSUE THREAD

**Issue by MortalCatalyst** [BaseXdb/basex#1342]
Following the querybind example I impoort the BaseXClient and then need to connect the session

`# create session
session = BaseXClient.Session('localhost', 1984, 'admin', 'admin')`

When I attempt to connect the session error returned that BaseXClient has no attribute Session

 session = BaseXClient.Session('localhost', 1984, 'admin', 'admin')

```bash
AttributeErrorTraceback (most recent call last)
<ipython-input-6-272a3e1022b0> in <module>()
----> 1 session = BaseXClient.Session('localhost', 1984, 'admin', 'admin')

AttributeError: module 'BaseXClient' has no attribute 'Session'
```

and system info included

```bash
Sayth@renshaw-laptop ~
λ python
Python 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import BaseXClient
>>> session = BaseXClient.Session('localhost', 1984, 'admin', 'admin')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'BaseXClient' has no attribute 'Session'
>>>
```

**Comment by ChristianGruen** [comment]
This may help: http://stackoverflow.com/questions/11403932/python-attributeerror-module-object-has-no-attribute-serial

Please only open issues if your observation has been confirmed as a bug on the mailing list.

**Comment by MortalCatalyst** [comment]
That doesn't resolve the issue though

```python
>>> from BaseXClient import Session
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Session'
```

**Comment by ChristianGruen** [comment]
I know that the binding is used a lot in the wild. Are you sure it’s a bug in our python binding? Then I’d be happy if you could propose how to fix it.

**Comment by MortalCatalyst** [comment]
I sure hope it isn't will try it on fedora, this is windows and failed on 2 different prompts and run as a script, but then windows can do that.

**Comment by MortalCatalyst** [comment]
Yes not sure tried it on Fedora 24 with 2.7 and 3.5 and it cannot import Session

```bash
>>> import BaseXClient
>>> from BaseXClient import Session
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Session
```

**Comment by MortalCatalyst** [comment]
Yes no able to fix this not sure why it is failing really.

**Comment by jacobborisov** [comment]
@MortalCatalyst try to use following import statement:

`from BaseXClient import BaseXClient`

**Comment by bcholfin** [comment]
The example material and PyPi page should be updated to reflect jacobborisov's solution, which worked for me.

**Comment by ChristianGruen** [comment]
@bcholfin: Would you be willing to send a little pull request?

**Comment by jonathanrobie** [comment]
The examples work as written if you run them from the source directory because they import `BaseXClient.py`.  They fail if you run them from any other place - you can verify this by simply renaming `BaseXClient.py` to `foo.py`.

If you make jacobborisov's change, which is correct, then it fails if you run the file from the source directory.  That messes up people who work with the source, and it might mess up your testing environment.

I imagine there is a standard solution for this in Pythonland ...

**Comment by ChristianGruen** [comment]
Jonathan, thanks a lot for your response.

**Comment by jtauber** [comment]
Part of the confusion is if you pip install `BaseXClient` you have a **package** called `BaseXClient` with a **module** inside it called `BaseXClient`. If you're _inside_ the source tree `import BaseXClient` is importing the **module** (in the file `BaseXClient.py`) not the package.

One way to solve the problem would be to move `BaseXClient.py` into a `BaseXClient` directory (with a `__init__.py` in it to make it a package. That way, from the directory with the examples, `import BaseXClient` would import the package, just like it does when pip install.

**Comment by jonathanrobie** [comment]
Is this about right?

https://github.com/BaseXdb/basex/pull/1524

**Comment by jonathanrobie** [comment]
The last comment contains a pull request that fixes this bug.  Let me know if you need anything else from me.

**Comment by ChristianGruen** [comment]
Your pull request was just fine; I’ve merged it now.
