### ISSUE TITLE
GUI Module not Found: http://exquery.org/ns/request"

### ISSUE THREAD

**Issue by james-jw** [BaseXdb/basex#1348]
For some reason importing this namespace causes the GUI to fail validation and report an error. Otherwise everthing works great!

Module Not Found: "http://exquery.org/ns/request"

```sql
import module namespace request = "http://exquery.org/ns/request";
```

I am using Windows 7

**Comment by dirkk** [comment]
Is the `basex-api.jar` included in your library path? This module is packaged there.

Also, I am not sure why you want to use the request module in a GUI context. It will require a servlet context and is (from what I can see, but our users often do stuff we didn't foresee) only useful in a web context.

**Comment by james-jw** [comment]
The actual code is only ever run during restxq responses however sometimes while editing in the GUI it obfuscates the real issues in the script and just reports the response one as being invalid instead of the real issue.

I found the issue was it wasn't in my class path like you stated.  If I leverage the basexgui.bat file while on a windows machine, it loads everything just fine!

Thanks for the help!
