### ISSUE TITLE
"Chop whitespaces" option when adding resource in DBA

### ISSUE THREAD

**Issue by kloor** [BaseXdb/basex#1350]
There is a checkbox in the DBA when adding a resource that is labelled "Chop whitespaces". This checkbox seems to have no impact. If the CHOP option in my .basex file is left to the default of true, XML files will always have whitespace nodes removed. If I change the CHOP option in my .basex file to false, XML files will always have whitespace nodes preserved.

**Comment by ChristianGruen** [comment]
Thanks for the hint; the issue has been fixed.
