### ISSUE TITLE
ADD / DELETE /REPLACE files via DBA

### ISSUE THREAD

**Issue by mingarao** [BaseXdb/basex#1355]
- The ADD command via dba/ doesn't allow to add a new "file" with the same name as a "file" already in base (though it should be possible according to the doc). Bug ?
- The DELETE command via dba/ removes **_all_** "files" with the same name, not only the one whiches checkbox is checked. Bug ?
- It would be nice to also have the REPLACE command via dba/ but as soon as the first two points above are fixed, this third one is no emergency anymore :)

**Comment by ChristianGruen** [comment]
Hi Maud! This is a tricky one (although it sounds so simple ;)… With the BaseX database commands and functions, it is currently not possible to indicate *which* resource with a specific name should be deleted. Maybe I should group all resources grouped by their file name, such that it is more obvious what will happen if an entry is deleted? Would this help?

In a future version of BaseX, I would like to merge the ADD and REPLACE commands and disallow the existence of more than one resource with the same name. This is mostly the reason for the current inconsistencies…

**Comment by mingarao** [comment]
Hi Christian :)
Yes I think that if, in the DBA, the ADD command replaces the file (or files) with the same file name as the one being added, it is fine.
The problem for us is to upload resources in DB currently used by researchers. In the actual situation, we always have a few seconds with a resource missing, because we must delete it before we can add the new version. Not so bad on test webapps but scary on prod webapps ;)
Another idea would be to be able to plug the DB on a git repo of the XML sources, but I didn't explore this lead so far and I think I won't be able to explore it alone :)

**Comment by ChristianGruen** [comment]
Maud, thanks for the description of your use case! I think I will replace the functionality of the ADD button with REPLACE. This will also be in alignment with our future plans (…to disallow multiple documents with the same name), and it should solve your problem as well.

**Comment by ChristianGruen** [comment]
Maud, some good news: If you choose a document in the Database panel, you can replace this resource already in the current version. The button is located on the right side of the page. Does this help?

**Comment by ChristianGruen** [comment]
I think I’m closing this for now… Maud, please reopen it if the REPLACE button does not do what it is supposed to do!
