### ISSUE TITLE
Connecting to PostgreSQL from BaseX XQuery (Pg driver class is not picked up)

### ISSUE THREAD

**Issue by wsdookadr** [BaseXdb/basex#1356]
Hi,

I was looking at #1341 and the [BaseX SQL docs](http://docs.basex.org/wiki/SQL_Module) , I think this is a very useful/nice feature. 
What I was trying to do is very similar actually, except I wanted to connect to PostgreSQL from XQuery in BaseX. So I downloaded the [Pg driver from here](https://jdbc.postgresql.org/download.html).

Then I tried something like `java -cp ./postgresql-9.4.1211.jre7.jar -jar BaseX853.jar`
and tried to run this XQuery:

    sql:init("org.postgresql.Driver"),
    let $conn := sql:connect("jdbc:postgresql://localhost:5432/news")
    return ""

And I get this error:

    [bxerr:BXSQ0007] Could not initialize supplied driver: 'org.postgresql.Driver'

Now this may be a mistake on my side, maybe a misuse of classpath. But I've tried this different ways, once using the `-cp` switch, then using the `CLASSPATH` env variable, and still got the error.

The Pg driver class is not being picked up. How can I connect to a Pg database from BaseX?

**Comment by ChristianGruen** [comment]
Do you get some helpful output if you activate debugging (`-d` on command line, or `SET DEBUG on` as command)?

**Comment by wsdookadr** [comment]
@ChristianGruen yeah, I tried that now and got this in the terminal

    [bxerr:BXSQ0007] Could not initialize supplied driver: 'org.postgresql.Driver'
            at org.basex.core.Command.execute(Command.java:100)
            at org.basex.gui.GUI.exec(GUI.java:478)
            at org.basex.gui.GUI.access$400(GUI.java:43)
            at org.basex.gui.GUI$7.run(GUI.java:420)
    Caused by: org.basex.query.QueryException: Could not initialize supplied driver: 'org.postgresql.Driver'
            at org.basex.query.QueryError.get(QueryError.java:1360)
            at org.basex.query.func.sql.SqlInit.item(SqlInit.java:22)
            at org.basex.query.expr.ParseExpr.iter(ParseExpr.java:44)
            at org.basex.query.QueryContext.iter(QueryContext.java:399)
            at org.basex.query.expr.List$1.next(List.java:134)
            at org.basex.query.MainModule$1.next(MainModule.java:121)
            at org.basex.query.QueryContext.cache(QueryContext.java:652)
            at org.basex.query.QueryProcessor.cache(QueryProcessor.java:114)
            at org.basex.core.cmd.AQuery.query(AQuery.java:88)
            at org.basex.core.cmd.XQuery.run(XQuery.java:22)
            at org.basex.core.Command.run(Command.java:253)
            at org.basex.core.Command.execute(Command.java:99)
            ... 3 more

**Comment by wsdookadr** [comment]
Forgot to mention, even though the BaseX jar I'm using suggests it's 8.5.3, I'm actually using 8.5.4 beta 8d90b66 which is after #1341 got closed.

**Comment by ChristianGruen** [comment]
Thanks for the hint. – Our SQL wrapper is fairly straightforward; could you possibly try to build a simple Java class, inspired by https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/func/sql/SqlConnect.java, that allows you to successfully connect to the driver, and pass it on to us?

**Comment by wsdookadr** [comment]
Ok, I skimmed through `SqlConnect.java`. Most JDBC guides I found are recommending to check the availability of the JDBC class before attempting to use it. So I modified SqlConnect to do the same
by adding this statement before all the others in the `try` block.

      Class.forName("org.postgresql.Driver");

After retrying the XQuery, the following exception is thrown:

    java.lang.ClassNotFoundException: org.postgresql.Driver
        [..]
        at java.lang.Class.forName(Class.java:264)
        at org.basex.query.func.sql.SqlConnect.item(SqlConnect.java:34)

Then I tried a host of different ways to make it load the Pg driver jar:
- passing `-Djava.library.path=/path/to/the/pg.jar`
- passing `-Djdbc.drivers=org.postgresql.Driver` (as suggested in [the Pg JDBC manual](https://jdbc.postgresql.org/documentation/94/load.html))
- passing the classpath with both `-cp` or `-classpath` or the env variable `CLASSPATH`

That did not work.

Then I wrote a small sample Java program that would connect to a PostgreSQL database, and this works and throws no exceptions:

    import java.sql.*;

    public class pgTest {
        public static void main(String[] args) {
            try {
                Class<?> clazz = Class.forName("org.postgresql.Driver");
                DriverManager.registerDriver((Driver)clazz.newInstance());
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/news?user=user&password=test1");
                conn.close();
            } catch(Exception e) {
                e.printStackTrace();
            };
            System.out.println("test");
        }
    }

I've compiled and ran this with `javac pgTest.java  ; java pgTest`

I am not sure how to transition/transfer this to `SqlConnect.java` but the only difference is that I am using `Class.forName` to acquire the class object and then I also register it. Other than that, it's also using the `DriverManager` just like `SqlConnect` is.

**Comment by wsdookadr** [comment]
Ok, problem solved, my bad. I was running BaseX like this:

    java -cp /path/to/pgdriver.jar -jar /path/to/BaseX.jar

Just talked to [https://github.com/emilburzo](@emilburzo) who points out that I should have run

    java -cp /path/to/pgdriver.jar:/path/to/BaseX.jar org.basex.BaseXGUI

This solved the problem

**Comment by ChristianGruen** [comment]
:) Thanks again, good to know.
