### ISSUE TITLE
following:: axis overruns into next document in collection

### ISSUE THREAD

**Issue by AndrewSales** [BaseXdb/basex#1374]
If I have two documents, a.xml and b.xml, in a database, each of whose content is `<a/>`,
`(//a)[last()]/preceding::a`
returns the empty sequence, as I would expect.

However, 
`(//a)[1]/following::a`
returns `<a/>` from the **next** document in the collection.

I'm running BaseX 8.5.2 on Windows 7.

**Comment by ChristianGruen** [comment]
Confirmed. Here’s a little script to reproduce the bug:

```xml
<commands>
  <create-db name='test'/>
  <add path='a.xml'><a/></add>
  <add path='b.xml'><a/></add>
  <xquery>(//a)[1]/following::a</xquery>
</commands>
```

Thanks for the report.
