### ISSUE TITLE
GUI: Feature Requests

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1378]
Based on https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg08800.html, all intermingled:

**Project window**
* [x] Add recent locations button, similar to the editor (recent files)

**Editor window**
* [x] Use scrollable run of tabs rather than multi row see http://docs.oracle.com/javase/7/docs/technotes/guides/swing/1.4/tabbedPane.html. Ideally with dropdownlist to select any item as with Eclipse, Firefox etc.
* [x] More tab close options. E.g "close all", "close others"
* [ ] Named, saveable, and loadable sets of external variables defined under the $x button of the Editor window would be nice.
* [ ] Configurable "dump the output to a file" (rather than using file:write in the query) would be nice, too; development is not always at a place where file:write is straightforward.

**Query info window**
* [x] Very useful but typically, at any one time, I am only interested in a particular section from: Compiling,Optimized Query,Query,Result,Timing,Query plan. 
* [x] Maybe checkbox config for which are shown or links to sections or tabs for sections

**Map/tree/folder windows**
* [ ] All these views are rooted at a document. There are times when I would like a collection based root here, as shown on database>properties>resources

**Comment by gsf-greece** [comment]
These suggestions are very good, I would also love to see closing tabs by using middle mouse click.

**Comment by ChristianGruen** [comment]
Finally some feedback: Changing the tab policy (by adding `tabs.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);`) seems to trigger a Java bug:

```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:643)
	at java.util.ArrayList.add(ArrayList.java:455)
	at javax.swing.JTabbedPane.insertTab(JTabbedPane.java:718)
	at javax.swing.JTabbedPane.add(JTabbedPane.java:858)
	at org.basex.gui.layout.BaseXTabs.add(BaseXTabs.java:35)
	at org.basex.gui.view.editor.EditorView.addTab(EditorView.java:1021)
	at org.basex.gui.view.editor.EditorView.<init>(EditorView.java:141)
	at org.basex.gui.GUI.<init>(GUI.java:257)
```

This looks similar to https://java.net/jira/browse/ULCCLOSEABLETABBEDPANE-5

**Comment by artiee** [comment]
Another thing for the External variables (behind "$x" -button): it would be great to have a resizeable window (to check longer values), and if the "Context item:" was a (resizeable) text-area. Now pasting XML to "Context item:" is difficult to edit.

**Comment by ChristianGruen** [comment]
@artiee: Done (see [latest snapshot](http://files.basex.org/releases/latest/)). I have additionally moved the action to the menu, and added a shortcut.
@apb2006: Sorry for queuing the GUI requests; I’ll definitely tackle some of them soon.

**Comment by ChristianGruen** [comment]
@apb2006, @sofiageo: I’ve realized various of the feature suggestions, so I’ll be closing this issue. Comments:

* I did some experiments with the `file:write`, but this turned out to be trickier than I expected, so I decided to stick with the status quo. The best way to test query output is to run the query and click on the SAVE button in the result view.
* External variable sets may be included in a future version of BaseX.
* Limiting the visualizations to collections is hard to implement, too.

Testing feedback is welcome: http://files.basex.org/releases/latest/

**Comment by sofiageo** [comment]
Everything looks good!

**Comment by apb2006** [comment]
Thanks for this. Some comments:
Great for the project history.
I find the single row tabs in the editor much better however the downside at the moment is that the +"new" is sometimes obsured. I wonder if it might be better on the toolbar?
I do like the Eclipse tab implementation that shows the total number of windows with a dropdown list, in alphabetical order, and omits the scroll buttons entirely.
>Limiting the visualizations to collections is hard to implement, too.
I thought it might be. I think it would be interesting to present collection based information (not the visualizations) in the web (DBA?) interface.

**Comment by ChristianGruen** [comment]
> I find the single row tabs in the editor much better however the downside at the moment is that the +"new" is sometimes obsured. I wonder if it might be better on the toolbar?

I’ve now added a button for creating new tabs.

> I do like the Eclipse tab implementation that shows the total number of windows with a dropdown list, in alphabetical order, and omits the scroll buttons entirely.

True. I gave it a quick shot, but it would take some more time I guess (in particular because the Swing rendering also depends on the corresponding Look and Feel).

> I think it would be interesting to present collection based information (not the visualizations) in the web (DBA?) interface.

I agree it would… Right now, it’s mostly a performance issue, because we want to keep the DBA fast even for databases with millions of documents. But I’ll keep your request in mind.
