### ISSUE TITLE
[DBA] Drop User Links fails in IE 11

### ISSUE THREAD

**Issue by micheee** [BaseXdb/basex#1385]
The link called when selecting a user via checkbox in:

> http://localhost:8984/dba/jobs-users?info=Dropped%20users%3A%201

Redirects to:
> http://localhost:8984/dba/Drop?name=foo&redirect=jobs-users

Can't reproduce on my machine (yet) but saw it happen repeatedly on a client’s machine.

**Comment by ChristianGruen** [comment]
Thanks. If you have some more hints, that would be great (which BaseX version are you using? What was the user name? Was the user currently active/logged in?)

**Comment by ChristianGruen** [comment]
Browsers tried so far: Edge, IE 11, Chrome, Firefox, Opera (old & new).

**Comment by ChristianGruen** [comment]
IE 11, Development Console (F12):

![image](https://cloud.githubusercontent.com/assets/196589/20297458/f08bcb14-ab10-11e6-9426-c7ad731f8bb2.png)

**Comment by ChristianGruen** [comment]
Closed for now (seems to be difficult to reproduce…).
