### ISSUE TITLE
DBA: Remove support for remote connections

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1399]
The DBA allows for both local and remote connections. While this is handy, various optimizations cannot be performed. Most strikingly, all databases will be locked in many cases although none of them are touched.

This is why remote query processing will be removed in BaseX 8.6. It may be reintroduced in a later version, or we could offer two versions. Obviously, the existing DBA 8.5 code can still be used in future.

**Comment by eptx** [comment]
This may be problematic for us as we need remote admin ability. But locking all DBs is not good so I need to understand better.

Erik Peterson | President | 281-804-9023 | ep@ardec.com<mailto:ep@ardec.com>
Ardec Business and Technology Management

_____________________________
