### ISSUE TITLE
XSLT module: Catalog Resolver for Saxon

### ISSUE THREAD

**Issue by gimsieke** [BaseXdb/basex#1405]
We are increasingly using xslt:transform() and now we ran into an issue where we imported another stylesheet by some abstract URI, i.e., an URI that only resolves by means of a catalog resolver and an XML catalog.
It seems as if no URI resolver is set on the [TransformerFactory](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/func/xslt/XsltTransform.java#L97). It should probably pass the URI resolver that is present in the context, which should use the catalog file(s) specified in the CATFILE option or in the xml.catalog.files system property.
The URI resolver should probably also be set when running a transformation so that file names passed to doc() can be resolved.
And making it available to Saxon will probably also make it available to Java’s XSLT 1 processor since they use the same interface.
Please let me know whether I should provide a small test set (catalog, stylesheet 1, imported stylesheet, xquery invocation).

**Comment by ChristianGruen** [comment]
Hi Gerrit. Yes, an [MCVE](http://stackoverflow.com/help/mcve) would be welcome. If you already had some Java code in mind how to do this.. Even better ;) As you‘ve already stated, for now, the catalog resolver is only applied to our own XML parser.

**Comment by ChristianGruen** [comment]
Hi Gerrit, so you have some examples for us? Cheers, Christian

**Comment by gimsieke** [comment]
No, I was too busy, and still am. But will do so in due time.

**Comment by ChristianGruen** [comment]
Closing this for now (feel free to reopen it).

**Comment by gimsieke** [comment]
I prepared an example. 
[2017-03-14_Issue1405.zip](https://github.com/BaseXdb/basex/files/842738/2017-03-14_Issue1405.zip)
After unzipping attached file, set the CATFILE option to the full path to `2017-03-14_Issue1405/xmlcatalog/catalog.xml`.
You can verify that the catalog will be used for System Identifier resolution when you create a DB from `2017-03-14_Issue1405/test.xml`.
Then open `2017-03-14_Issue1405/test.xq` and execute it. It won’t resolve `doc('http://transpect.io/test/test.xml')` which is the same URI as in the DOCTYPE declaration of `test.xml`. The difference is probably that for DOCTYPE resolution the `rewriteSystem` instruction in `2017-03-14_Issue1405/xmlcatalog/catalog.xml` will be used while for your `doc()` implementation, no catalog will be used. The `rewriteURI` instruction of the catalog should be taken into account here, I think.
If you comment out the first `doc('http://transpect.io/test/test.xml')`, `xslt:transform()` will throw an IO error for `http://transpect.io/test/lib/imported.xsl` that is imported by `2017-03-14_Issue1405/importing.xsl`. This may probably be alleviated by passing the catalog resolver object (if available) to `TransformerFactory.setURIResolver()`, as described in this [2004 article](https://www.xml.com/pub/a/2004/03/03/catalogs.html). Then hopefully it will also use the catalog’s `rewriteURI` instruction for `doc()` calls within the XSLT transformation, for `xsl:include`, and for `xsl:import` instructions.
So I think that of the (at least) 3 use cases for a catalog, namely 1) DOCTYPE resolution via `rewriteSystem`, 2) resolving URIs in your XQuery implementation, and 3) passing the catalog resolver to a JAXP XSLT processor, you only implemented 1) so far.
If you absolutely don’t have time to look into this, I will give it a try (or as @mkraetke who has recently quite gotten into Java programming…).

**Comment by ChristianGruen** [comment]
Thanks, Gerrit. You are completely right: Currently, `CATFILE` will only be considered if XML files are parsed.

2. If XQuery is evaluated via Java, a URI resolver can be [assigned to the QueryProcessor](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/QueryProcessor.java#L219). Maybe a resolver could be implemented for resolving catalogs (possibly even based on the Apache CatalogResolver).
3. For XSLT, I tried to set a URI resolver. Detection seems to work, but only partially. I have written a simple Java class, which is based on your example ZIP file: [XsltTransformWithCatalog.java](https://gist.github.com/ChristianGruen/4b5a6020a8dc763a253f3c657c1a2501). I guess that there’s only litte left to get it running. Maybe Martin (@mkraetke) has some time to look at this? [xml-resolver-1.2.jar](http://central.maven.org/maven2/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar) (which is e. g. included in the full distribution of BaseX) must be added to the classpath.

**Comment by gimsieke** [comment]
I hope that we’ll find time to look into the Java class next week.
In the meantime, I might have discovered another spot where the catalog resolver isn’t used: When processing XIncludes.

**Comment by ChristianGruen** [comment]
Thanks! Looking forward. Further questions will be welcome.

**Comment by ChristianGruen** [comment]
Hi @gimsieke, hi @mkraetke, just asking… Did you have some time to look at the Java code?

**Comment by gimsieke** [comment]
No, we didn’t. Things have been (and continue to be) insanely busy. So far, we worked around the catalog resolution problem by duplicating and modifying the affected XSLT files so that they only contain `xsl:import`s by relative file system paths.

**Comment by ChristianGruen** [comment]
Resolved: https://mailman.uni-konstanz.de/pipermail/basex-talk/2019-March/014177.html

Feel free to close the issue if everything works as expected.

**Comment by ChristianGruen** [comment]
Closing this… Feel free to reopen this if the solution does not work as expected.
