### ISSUE TITLE
Dockerfile web.xml

### ISSUE THREAD

**Issue by micheee** [BaseXdb/basex#1406]
`web.xml` is copied to image…

https://github.com/BaseXdb/basex/blob/master/Dockerfile#L9 
```
    cp -r /usr/src/basex/basex-api/src/main/webapp/WEB-INF /srv

```

…but ultimately ignored

```
⇒  docker run basex/basexhttp
/srv/.basex: writing new configuration file.
DEBUG: true
Creating /srv/BaseXWeb/WEB-INF/web.xml
Creating /srv/BaseXWeb/WEB-INF/jetty.xml
```

Am I missing something or could line 9 be removed?

**Comment by JensErat** [comment]
Just tried what will happens if you remove the statement:

```
org.basex.core.BaseXException: /srv/src/main/webapp/WEB-INF/web.xml not found.
	at org.basex.BaseXHTTP.locate(BaseXHTTP.java:226)
	at org.basex.BaseXHTTP.initJetty(BaseXHTTP.java:192)
	at org.basex.BaseXHTTP.<init>(BaseXHTTP.java:75)
	at org.basex.BaseXHTTP.main(BaseXHTTP.java:52)
/srv/src/main/webapp/WEB-INF/web.xml not found.
```

So although this seems superfluous, the file is indeed required. Can anybody with deeper insight on the web server explain what's going on?

**Comment by ChristianGruen** [comment]
Someone should definitely give me more insight into Docker… ;). I can only speculate what’s going on here: If there is no `.basex*` file in the [BaseX Home Directory](http://docs.basex.org/wiki/Configuration#Home_Directory), a default configuration is generated, which includes the creation of a `.basex` file and – in the case of BaseXHTTP – the creation of the minimum set of web applications required to start the web server.

So either `WEB-INF` should be copied to `/srv/BaseXWeb`, or a `.basexhome` should be defined somewhere else?

**Comment by micheee** [comment]
Won't resolve, not a bug™️
