### ISSUE TITLE
Question: org.basex.api.client.*

### ISSUE THREAD

**Issue by tsiselskyi** [BaseXdb/basex#1407]
Hi all, have a question. I try to use **org.basex.api.client.*** with some kind of “microservice” from WildFly Swarm, in particular with JAX-RS implementation; and everything works just fine, but as a dependency service node must include basex-core.jar with a-a-all classes, when, in fact, I use just two of them:
```java
import javax.ws.rs.*;
import javax.ws.rs.core.*;

import org.basex.api.client.ClientQuery;
import org.basex.api.client.ClientSession;

@Path("/a")
public class AService {

  @GET
  @Path("/{id}")
  @Produces("application/json")
  public Response get(@PathParam("id") int id) {
    try {
         ...
```
Maybe somewhere exists fork or “refactored” version of BaseX with two kind of archive _BaseX-Server.jar_ (without GUI  and Client) and _BaseX-Connectivity.jar_ - something like jdbc with XQuery builder/validation.
Thanks.

PS: RestXQ with Jetty is awesome, not a question; but not suitable in my case.

**Comment by ChristianGruen** [comment]
We cannot offer a version of BaseX that only contains the ClientSession and ClientQuery classes. As you may have seen, these classes reference various other classes of the project.

However, the [BaseXClient class in the examples directory of the project](https://github.com/BaseXdb/basex/blob/master/basex-examples/src/main/java/org/basex/examples/api/BaseXClient.java) is sufficient to communicate with the BaseX server. In the same directory, you will find some more examples how this class can be used (see also http://docs.basex.org/wiki/Clients).

PS: This repository is mainly used reporting obvious bugs and discussing details of feature requests. For further questions, please write to our basex-talk mailing list.

**Comment by tsiselskyi** [comment]
Thanks  for response, but I don't asking you to wrap up all “client” code into two classes :) I mean separated archives for Server and Client. 
![Hex](https://cdn.rawgit.com/tsiselskyi/repo/master/img/nodes.svg)
Project's repository has many forks and maybe one of them has such kind of “structure” - that is a question, but anyway thanks.   

PS: This is same kind of feature request – two archive – for Server & Clent.

**Comment by ChristianGruen** [comment]
As the client can be boiled down to a single class, we have no plans to make it available as a single JAR file. However, we had some thoughts if we shouldn’t remove the GUI components from the server distribution, as it introduces X dependencies on Linux systems.

**Comment by tsiselskyi** [comment]
> As the client can be boiled down to a single class, we have no plans to make it available as a single JAR file.

Several additional utilities would be helpful :) write code for them, in any case, it is necessary; but in principle, yes - that's sufficient. Sory for disturbing.

**Comment by dirkk** [comment]
You are more than welcome to add this feature with all the utilities you seem necessary yourself. BaseX ist open source and everyone is invited to add stuff to it. If the code and resulting feature is useful to a general public we might add it to the upstream repository. However, given what you describe here I don't see much use for it given that one simple class (as Christian said) can do the feature you requested and it was never requested before.

**Comment by tsiselskyi** [comment]
> one simple class (as Christian said) can do the feature you

Agree, as Christian said, that is sufficient to communicate with the BaseX server - so, your app successfully connected to server and what's next?

- you need build or load some queries from some kind of repository(maybe watch for changes), pass some request parameters to “string literals” in appropriate/secure way, validate resulting “text” as correct XQuery code, without disturbing server with such trivial tasks.

GET ~/something/a/b/c
```xquery 
xQueryBulder(“db:open('~1', '~2')/somewhere[@qux = ~3]//somewhat”, a, b, c)  
(: or :) 
xQueryBulder(repo.TEMPLATE, a, b, c) ```
(: or :) 
bx.open(a)
  .for(“somewhere”)
  .where((doc) → { return doc.attr(“qux”) == c })
  .return((doc) → { return doc.desc(c) });
```
or maybe POST ~/something
```java
xQueryBulder(“db:add("foobar", ~a, "something.xml")”, ValidDomainModel) 
```

- Session/Caching and some kind of Connection Pool?

> GUI components introduces X dependencies on Linux

I`m not sure, but for now this is relevant to Windows too – Windows Server 2016 Nano?

**Comment by ChristianGruen** [comment]
> Sory for disturbing.

No problem.

>  so, your app successfully connected to server and what's next?

The BaseXClient class can be used to send commands to the server and perform queries, as described in the referenced Wiki article. Obviously, it doesn’t go any further.

Apart from that way how we bundle this, it seems you are asking for various other things in this issue, such as extensions in the client architecture. Maybe you should check out alternatives instead, such as the XQJ API. For further ideas, feel free to write to our mailing list.

**Comment by tsiselskyi** [comment]
Ok, maybe this place not appropriate for such kind of flood and thanks for info.
Unfortunately XQJ, stuck in version XQuery 1.0, no? But anyway, thanks. Ideas for Client API: something like this – www.jooq.org. :) - for XQuery and BaseX modules.
