### ISSUE TITLE
external variables GUI glitch

### ISSUE THREAD

**Issue by gsf-greece** [BaseXdb/basex#1417]
Since the upgrade to 8.6, when I'm adding an external variable in the GUI, an additional entry is being added by basex, which is just a dot. It can be visible the next time you try to change the external variable. I'm adding a screenshot to help explain this better.

This is also happening in latest snapshot (302908e).

![screenshot from 2017-02-15 13-52-41](https://cloud.githubusercontent.com/assets/6191600/22973400/39fa6bb2-f386-11e6-801a-f55769fa3091.png)

**Comment by ChristianGruen** [comment]
That’s intended. The dot refers to the context item, which you can reference it in the GUI by a plain dot (`.`).

**Comment by gsf-greece** [comment]
Thanks Christian. However I think it should be hidden, it's confusing.  

Probably related, I'm also having trouble viewing the document node in latest snapshot. Pressing the Home button returns `[XPDY0050] Root of the context value must be a document node.`
Running root() returns an error: `Cannot cast xs:untypedAtomic to node(): "".`
and just referencing the dot, returns an empty result with query plan
```
<QueryPlan compiled="true">
  <ContextValue/>
</QueryPlan>
```

In case the aforementioned changes are intended, feel free to close the issue and we can continue the discussion on the mailing list.

**Comment by ChristianGruen** [comment]
> However I think it should be hidden, it's confusing.

This feature was requested by two different users in the past; so I think I will rather wait and see if it confuses others as well. Some documentation on bottom of the dialog window could surely be helpful, too; more suggestions (preferably those ones that don’t cause too much work…) are welcome.

> Probably related, I'm also having trouble viewing the document node in latest snapshot.

It seems you have done some things that I didn’t do, or that are not documented in your comment. Could you please give me a little step-by-step description how to reproduce this?

**Comment by ChristianGruen** [comment]
I think could easily add a separate line in the dialog window, exclusively for the context item. And I should probably dissolve an existing binding if an empty string is specified.

**Comment by gsf-greece** [comment]
After restarting basexgui it's working fine again, until I run one of my complex scripts. There are some doc($external_variable) in that scripts but I'm not sure if they are creating the issue. 

After this happens, If I open a new database I keep getting the same error (home, root(), and . not working), until I restart basexgui. If it is stuck at this state, and I write this: 

```
declare context item := document {
  <xml>
    <text>Hello</text>
    <text>World</text>
  </xml>
};

```
then dot and root() are working, but home button is still not working. I guess because it references a different context item.

**Comment by ChristianGruen** [comment]
Could you please check the [latest snapshot](http://files.basex.org/releases/latest/) and give me some feedback if the new dialog window works better for you? I have added a static entry for the context item, and the context item assignment will be reset if an empty value is specified in the dialog window.

> […] I'm not sure if they are creating the issue. […]

Then I would propose to close the issue after your snapshot review, and we can continue this discussion on the list once it’s reproducible.

**Comment by gsf-greece** [comment]
This change fixes both issues. I think it's because I was opening the external variables dialog, the context item was being set to an empty string, and then even opening a new database, had no effect on changing it back.

Thanks!

**Comment by ChristianGruen** [comment]
Even better! Thanks for the quick review.
