### ISSUE TITLE
GUI, Map: Last element won't be highligted.

### ISSUE THREAD

**Issue by ChristianLutz** [BaseXdb/basex#1420]
Hello Christian,

I am using the current version 8.6 and there is a minor bug. If you query for some items, the last element won't be highlighted in the map view.

How to reproduce:
* Use the provided file as database input [basexMapBug.txt](https://github.com/BaseXdb/basex/files/786875/basexMapBug.txt)
* Execute xquery //@type
* And you will see only the first two elements are hightlighted, but all should be highlighted.

Sincerely
Christian

**Comment by ChristianGruen** [comment]
Hi Christian, thanks for the hint, will be tackled tomorrow. Cheers, Christian

**Comment by ChristianGruen** [comment]
Thanks for noting and reporting this bug. It was fixed in the [latest snapshot](http://files.basex.org/releases/latest/).
Glad to hear that you’re still using BaseX ;)

**Comment by ChristianLutz** [comment]
Yes I try to keep in touch with baseX :)
