### ISSUE TITLE
GUI Editor wrong text element highlighting

### ISSUE THREAD

**Issue by ChristianLutz** [BaseXdb/basex#1426]
Hello,

I just stumbled over a minor bug in the editor. If you use the following query. It is somebit confusing, because the editor highlights `(: not a comment :)` as comment (cyan) but acutally it should be hightlighted as text (black).
```
let $x := <a>(: not a comment:)</a>
return $x
```

Sincerely

**Comment by ChristianGruen** [comment]
Hi Christian, yes, this is a known issue: The BaseX query editor does not parse the query; as a result, it cannot distinguish between XML text and XQuery comments. I have copied your comment to https://github.com/BaseXdb/basex/issues/949#issuecomment-283301017.
