### ISSUE TITLE
Data corruption when disabling autoflush

### ISSUE THREAD

**Issue by dirkk** [BaseXdb/basex#1434]
As reported on the Mailing list in https://mailman.uni-konstanz.de/pipermail/basex-talk/2017-March/011849.html:

> After the first FLUSH has been issued, the ADD  directive starts randomly
> throwing a org.basex.core.BaseXException (when using the BaseXClient
> implementation it was its inner ok() method that started returning false).
> 
> I tracked the root cause in the server: the SAXParser complaining about the
> documents not being well-formed (the exact same documents are all imported
> fine with AUTOFLUSH on). In the server standard logs I can see why: parts
> of those documents are suddenly missing (usually the beginning + command
> part) at parse time!
> 
> That is the symptom, now for the cause I'm also observing that the ADD and
> FLUSH directive in the logs are out of order, exactly like what would
> happen in the FLUSH commands were not properly queued.
> 
> I was expecting something like :
> ADD
> ADD
> ADD
> (N times)
> FLUSH
> ADD
> ADD
> ADD
> (N times)
> FLUSH
> etc.
> 
> Instead I'm observing
> ADD
> FLUSH
> ADD
> FLUSH
> ADD
> FLUSH
> (etc)
> then
> ADD
> ADD
> ADD
> (lots of them)
> ERROR
> 
>

**Comment by ChristianGruen** [comment]
Resolved (see mailing list).
