### ISSUE TITLE
fetch:xml() vs doc() relative paths 

### ISSUE THREAD

**Issue by gsf-greece** [BaseXdb/basex#1435]
fetch:xml() has different behaviour than doc() for relative paths to the XQuery script, I don't know if it is intentional or not. 

For example doc(xml/myXmlFile.xml) is working but fetch:xml(xml/myXmlFile.xml) is not, since it always looks for file in the basex bin directory.

**Comment by ChristianGruen** [comment]
I have added some information to the documentation (see http://docs.basex.org/wiki/Fetch_Module#Conventions). From today’s perspective, it would make more sense to base everything on the XQuery base URI. Maybe we will align the behavior of this module in a future version of BaseX (quite obviously, this will introduce compatibility issues, so I’m not sure if the change will happen).
