### ISSUE TITLE
fn:doc is not deterministic

### ISSUE THREAD

**Issue by gsf-greece** [BaseXdb/basex#1436]
While trying to resolve another issue, I noticed that fn:doc(url) is fn:doc(url) returns false in BaseX 8.6.1
The same call in BaseX 8.4.4 returns true. Is this intentional, can it be configured to use the same document node, or is it just a bug? [[1](https://www.w3.org/TR/xpath-functions-31/#func-doc)]

**Comment by ChristianGruen** [comment]
Wow. Confirmed. I’ll track down the cause, thanks.

**Comment by ChristianGruen** [comment]
Fixed (caused by #1416).
