### ISSUE TITLE
can you tell how can make the file CHANGELOG

### ISSUE THREAD

**Issue by liujie15838028035** [BaseXdb/basex#1438]
can you tell how can make the file CHANGELOG

**Comment by micheee** [comment]
@liujie15838028035 general question will be answered on our [mailing list](https://mailman.uni-konstanz.de/mailman/listinfo/basex-talk) or on [Stackoverflow: BaseX](https://stackoverflow.com/questions/tagged/basex?sort=newest&pageSize=50).

Another hint, be less brief, it is hard to tell what you actually want.

**Comment by liujie15838028035** [comment]
@ChristianGruen  thanks !

**Comment by micheee** [comment]
You're welcome! 🤣

**Comment by liujie15838028035** [comment]
@ChristianGruen , i try to send mail ,  but send failure, 
the file CHANGELOG in baseX project , is that make by run maven commond?
call you cell me ?

**Comment by micheee** [comment]
No it is written by hand,. 🥇

**Comment by ChristianGruen** [comment]
@liujie15838028035: What are your hobbies?

**Comment by liujie15838028035** [comment]
when i relase my project , i want to  make the file CHANGELOG, this is i want!

@ChristianGruen  i am interest in maven , workflow ！

**Comment by micheee** [comment]
You can find more information here: https://maven.apache.org/
