### ISSUE TITLE
RESTXQ: Status Code 410

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1458]
If the RESTXQ annotation `%rest:single` is used, and if a request is canceled, `410` will be returned by the web server (see http://docs.basex.org/wiki/RESTXQ#Query_Execution). The chosen code causes problems with some browsers, because 410 indicates that the “resource is no longer available” (https://tools.ietf.org/html/rfc7231#section-6.5.9), so a different code should be chosen.

New proposal: `460` (proprietary, as existing codes don’t really match).

**Comment by dirkk** [comment]
Sending back no-cache headers (http://stackoverflow.com/questions/49547/how-to-control-web-page-caching-across-all-browsers) also for this new status code still seems like a good idea to me. I guess failing requests because of `%rest:single` should never be cached.
