### ISSUE TITLE
Error in Docker -- Module not found: http://exquery.org/ns/request

### ISSUE THREAD

**Issue by citizenrich** [BaseXdb/basex#1467]
Hi,

I'm setting up a Docker container instance. One of my modules includes:
import module namespace request = "http://exquery.org/ns/request";

but, on trying to install it errors:
[XQST0059] Module not found: http://exquery.org/ns/request.

I see the identical error in this issue: https://github.com/BaseXdb/basex/issues/1348 But, I'm not clear how to solve it.

Best,
Richard

**Comment by micheee** [comment]
Hi Richard,

I guess you are building/running your own docker image and most probably the `basex-api.jar` is missing in your classpath? 
The `http://exquery.org/ns/request`-namespace is provided by the [basex-api](https://github.com/BaseXdb/basex/tree/master/basex-api) package and not loaded by default when you open the `BaseXGUI` or `BaseX`-standalone instance; so not particularly docker related :-)

---

Using "our" docker image from https://hub.docker.com/r/basex/basexhttp/ yields the following results:

```xquery
(: file test.xqm :)
module namespace page = 'http://basex.org/examples/web-page';
import module namespace request = "http://exquery.org/ns/request";

declare %rest:path("hello/{$who}") %rest:GET function page:hello($who) {
 <response>
  <title>
  Hello { $who },
  {request:remote-hostname()}!</title>
 </response>
};
```

```bash
docker run --rm -p 8984:8984 -v "$(pwd):/srv/BaseXWeb"  basex/basexhttp
```

```xml
<!-- open http://localhost:8984/hello/Richard -->
<response>
<title>Hello Richard, 172.17.0.1!</title>
</response>
```

---

I hope this helps! 

Michael

**Comment by citizenrich** [comment]
Hi,

Thanks for the easily reproducible example. It works in that manner.

I'm actually using a docker-compose file. Here's a barebones example that doesn't work.

[docker-compose.yml]
version: '3'

services:

  openinfoman:
    image: basex/basexhttp:latest
    volumes:
      - ".:/srv/BaseXWeb"

In the directory where docker-compose is launched is just the test.xqm file from above. Launch the container with `docker-compose up -d`. Then enter the container in a shell with `docker exec -it whatever_docker_named_it bash`

Error:
basex@4c20ab931572:~/BaseXWeb$ basex -Vc "repo install test.xqm"
Stopped at /srv/BaseXWeb/test.xqm, 2/66:
[XQST0059] Module not found: http://exquery.org/ns/request.

I'm not sure why it works from a `docker run` but not in a docker-compose with the paths. Any hints would be great. Very much appreciate the great example.

**Comment by micheee** [comment]
Hello Richard,

thanks for the clarification.

Yes that is the same problem; the `basex` command does not know of the EXQuery Module as the `basex-api.jar` is not in the classpath for the `basex` standalone command.

Yet: maybe I need some more information on why you need to run `REPO INSTALL` in the first place?

`REPO INSTALL` is used to install* library modules, but as you are trying to run a RestXQ Module it can happily live in `/srv/BaseXWeb` without any need for installation.
Simply omit the `REPO INSTALL` step and you should be fine :-)

More info can be found here: http://docs.basex.org/wiki/Repository

Hope this helps :-)

* install for a XQuery module basically means copying that file to `BaseXRepo` folder.

**Comment by ChristianGruen** [comment]
Dear Richard, for general questions on BaseX, it would be great if you could write to our [basex-talk mailing list](http://basex.org/open-source/). Thanks in advance.

**Comment by citizenrich** [comment]
Thanks, and will certainly address general questions going forward in mailing list!
