### ISSUE TITLE
deploying the BaseX war file into WebSphere Liberty throws exceptions 

### ISSUE THREAD

**Issue by stefaaxo** [BaseXdb/basex#1476]
use of the dropins of the WebSphere server and trying to add the war file generated and error

[ERROR   ] SRVE0271E: Uncaught init() exception created by servlet [RESTXQ] in application [BaseX864]: java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:505)
	at java.util.Properties.setProperty(Properties.java:179)
	at java.lang.System.setProperty(System.java:479)
	at org.basex.http.HTTPContext.init(HTTPContext.java:56)
	at org.basex.http.BaseXServlet.init(BaseXServlet.java:35)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:332)
	at [internal classes]

[ERROR   ] SRVE0276E: Error while initializing Servlet [RESTXQ]: javax.servlet.ServletException: SRVE0207E: Uncaught initialization exception created by servlet
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:401)
	at [internal classes]
Caused by: java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:505)
	at java.util.Properties.setProperty(Properties.java:179)
	at java.lang.System.setProperty(System.java:479)
	at org.basex.http.HTTPContext.init(HTTPContext.java:56)
	at org.basex.http.BaseXServlet.init(BaseXServlet.java:35)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:332)
	... 1 more

the NullPointerException at org.basex.http.HTTPContext.init(HTTPContext.java:56) appears to be due to

   final String webapp = sc.getRealPath("/");

returning null (where sc is an installation of ServerConttext). From the ServetContext.getRealPath javadoc,

   This method returns null if the servlet container is unable to translate the given virtual path to a real path.

any feedback?
thanks
Stefania

**Comment by stefaaxo** [comment]
what is failing is line 56 on
https://github.com/BaseXdb/basex/blob/476e6f12e251860b108a3e6cd4a7972ee003a6c8/basex-api/src/main/java/org/basex/http/HTTPContext.java
because the variable webapp is null

54    final String webapp = sc.getRealPath("/");
55    // system property (requested in Prop#homePath)
56  System.setProperty(Prop.PATH, webapp);

so the question is why  sc.getRealPath("/"); came empty??

**Comment by ChristianGruen** [comment]
Thanks for the hints; I’ll have a look at this soon. More observations are welcome.

**Comment by gdlxn-ibm** [comment]
I'm working with Stefania on this problem.  I found [Liberty profile servlet context getRealPath](https://www.ibm.com/developerworks/community/forums/html/topic?id=eb04c8ae-02d4-421b-af2c-2ef626a3db1), which suggests that WebSphere Liberty returns null for ServletContext.getRealPath when deploying a .war file.  I'm not sure deploying an expanded copy of the .war files will have  WebSphere Liberty returns a non-null value for ServletContext.getRealPath, though we plan to try.

But in any case, I'm not sure having the BaseX WAR depend on ServletContext.getRealPath returning a non-null value is a good idea since Java EE specification allows for ServletContext.getRealPath return null.  At a minimum, BaseX should produce a meaningful error message in the case that ServletContext.getRealPath returns null rather than just failing with a NullPointerException.

**Comment by ChristianGruen** [comment]
> But in any case, I'm not sure having the BaseX WAR depend on ServletContext.getRealPath returning a non-null value is a good idea since Java EE specification allows for ServletContext.getRealPath to return null. At a minimum, BaseX should produce a meaningful error message in the case that ServletContext.getRealPath returns null rather than just failing with a NullPointerException.

Absolutely. It would be interesting which reasonable alternatives we could use for `getRealPath`. Suggestions are welcome.

**Comment by stefaaxo** [comment]
i verified that the expanded version of the war file solved the problem.
I expanded the war file and called it with the .war in it
C:\Program Files\IBM\WebSphere\Liberty\usr\servers\sport\apps\BaseX864.war

C:\Program Files\IBM\WebSphere\Liberty\usr\servers\sport\apps\BaseX864.war>dir
 Volume in drive C has no label.
 Volume Serial Number is 7B77-7220

 Directory of C:\Program Files\IBM\WebSphere\Liberty\usr\servers\sport\apps\BaseX864.war

07/24/2017  10:04 AM    <DIR>          .
07/24/2017  10:04 AM    <DIR>          ..
07/24/2017  09:47 AM    <DIR>          .logs
07/24/2017  10:04 AM    <DIR>          data
07/24/2017  09:41 AM    <DIR>          dba
07/24/2017  09:41 AM    <DIR>          META-INF
04/11/2017  10:22 AM             3,376 restxq.xqm
07/24/2017  09:41 AM    <DIR>          static
07/24/2017  09:41 AM    <DIR>          WEB-INF
               1 File(s)          3,376 bytes
               8 Dir(s)  145,144,422,400 bytes free

I modified the server.xml as follow 

    
     <application id="BaseX864" name="BaseX864" location="${server.config.dir}/apps/BaseX864.war" 
context-root="BaseX864" type="war">
</application> 


Now baseX deploys with success and i am able to run the dba and do all the operation: 
- create database
- add xml documents.

here is where it deploys ->  http://192.168.1.194:9080/BaseX864/

here is my test
http://192.168.1.194:9080/BaseX864/dba/database?name=APARS

[7/24/17 9:47:08:533 EDT] 00000028 com.ibm.ws.webcontainer                                      I SRVE0250I: Web Module BaseX: The XML Database and XQuery Processor has been bound to default_host.
[7/24/17 9:47:08:533 EDT] 00000028 com.ibm.ws.http.internal.VirtualHostImpl                     A CWWKT0016I: Web application available (default_host): http://192.168.1.194:9080/BaseX864/
[7/24/17 9:47:08:799 EDT] 00000028 com.ibm.ws.session.WASSessionCore                            I SESN0176I: A new session context will be created for application key default_host/BaseX864

**Comment by stefaaxo** [comment]
here some research: 
https://stackoverflow.com/questions/12160639/what-does-servletcontext-getrealpath-mean-and-when-should-i-use-it
https://stackoverflow.com/questions/536228/why-does-getrealpath-return-null-when-deployed-with-a-war-file

**Comment by stefaaxo** [comment]
from the link:
getRealPath() is unportable; you'd better never use it

Use getRealPath() carefully. There are actually no sensible real world use cases for it. If all you actually need is to get an InputStream of the web resource, better use ServletContext#getResourceAsStream() instead, this will work regardless of the way how the WAR is expanded.

**Comment by ChristianGruen** [comment]
> getRealPath() is unportable; you'd better never use it

Thanks! Would you mind sending me an exemplary pull request that might solve the issue?

**Comment by gdlxn-ibm** [comment]
Christian, what does BaseX do with the directory it gets back from ServletContext.getRealPath?  Does BaseX write files into this directory?  If so, be aware that this directory is overwritten whenever the BaseX application is redeployed -- from [What does servletcontext.getRealPath(“/”) mean and when should I use it](https://stackoverflow.com/questions/12160639/what-does-servletcontext-getrealpath-mean-and-when-should-i-use-it)

> **Don't ever write files in there**

> Also note that even though you can write new files into it using FileOutputStream, all changes (e.g. new files or edited files) will get lost whenever the WAR is redeployed; with the simple reason that all those changes are not contained in the original WAR file. So all starters who are attempting to save uploaded files in there are doing it wrong.

> Moreover, getRealPath() will always return null or a completely unexpected path when the server isn't configured to expand the WAR file into the disk file system, but instead into e.g. memory as a virtual file system. 

If you need a location in which to write BaseX files, I would suggest letting the BaseX administrator specify the location via some sort of configuration in the .basex configuration file.  If the file location configuration isn't specified, I would suggest having BaseX fail at startup with a message indicating the missing configuration.  You'd probably also want / need to handle migration from earlier BaseX versions which used the ServletContext.getRealPath directory.

**Comment by ChristianGruen** [comment]
> Christian, what does BaseX do with the directory it gets back from ServletContext.getRealPath?

Hi gdlxn, as I think you have already found out, the result of `ServletContext.getRealPath` is currently assigned to the [WEBPATH](http://docs.basex.org/wiki/Options#WEBPATH) option (see [HTTPContext.java#L58](https://github.com/BaseXdb/basex/blob/master/basex-api/src/main/java/org/basex/http/HTTPContext.java#L58)). In this directory, all web application contents are stored (RESTXQ files, static directories, scruipts, etc). For example, this path is requested in [RestXqModules.java#L45](https://github.com/BaseXdb/basex/blob/master/basex-api/src/main/java/org/basex/http/restxq/RestXqModules.java#L45).

No files will be written into that directory from BaseX, but it’s possible for users to change the contents of this directory, and BaseX will automatically detect new and updated files at runtime (see e.g. the [PARSERESTXQ](http://docs.basex.org/wiki/Options#PARSERESTXQ) option for more details). This is also used in productive environments (as an example, the servlet contents are changed via hot deploys without any need to restart the BaseX servlet).

I think we can easily agree that the current solution is not the most desirable one in your environment. It works fine in practice in various configurations we have tested so far (with BaseXHTTP, and as servlet with Jetty or Tomcat). I didn’t have time to play around with WebSphere Liberty, though, but I’ll be glad to get some concrete proposals on how to get this resolved for your application server.

What did you try so far? What other chances do we have with WebSphere to dynamically parse directory contents that have not been delivered via WAR files?

**Comment by stefaaxo** [comment]
> What did you try so far? What other chances do we have with WebSphere to dynamically parse directory contents that have not been delivered via WAR files?

As i said before i expanded the war file and that was successful.
I was able to run BaseX, create a database and add an xml document to it.
is there any other test that you were thinking about?

**Comment by ChristianGruen** [comment]
> As i said before i expanded the war file and that was successful.
I was able to run BaseX, create a database and add an xml document to it.
is there any other test that you were thinking about?

If I got you right, you are still interested in having `getRealPath` replaced with a better solution. If so, it would be great if you could rewrite the code in a way that you believe matches your requirements.

**Comment by gdlxn-ibm** [comment]
Christian - A colleague who uses BaseX in another project informed us that she runs the BaseX WAR (without needing to explicitly expand the WAR file) on WebSphere Liberty Profile (WLP) by configuring the WLP server to automatically expand deployed WAR files.  This done by adding the following line to the WLP server's server.xml file:

> &lt;applicationManager autoExpand="true"/&gt;

While it would be nice if the BaseX WAR handled the case where ServletContext. getRealPath returns null, we plan to go with the solution of having the WLP server automatically expand WAR files.

Thanks for your help with this issue.

**Comment by ChristianGruen** [comment]
…good to hear that you have found a solution. Feel free to keep me updated.

**Comment by ChristianGruen** [comment]
I’m closing this for now. You are invited to reopen it if there are some news.
