### ISSUE TITLE
Shouldn't CHOP = false make xml:space="preserve" the default behavior?

### ISSUE THREAD

**Issue by ottidmes** [BaseXdb/basex#1479]
From the documentation about the `CHOP` option I assumed that since `xml:space="preserve"` sets `CHOP = false` for that part of the document, that if I set `CHOP = false` in my configuration file, that the behavior you get when you use `xml:space="preserve"` would be applied to the whole database (I created the database after setting the option). However the only way I have ever been able to get this behavior, has been to set `xml:space="preserve"` at the root element. Am I missing something, or is this a bug? How could I get this behavior by default in my databases?

**Comment by ChristianGruen** [comment]
An [MCVE](https://stackoverflow.com/help/mcve) would be appreciated.

**Comment by ChristianGruen** [comment]
Closed for now (unconfirmed bugs should first be reported to our [basex-talk](http://basex.org/open-source/) mailing list, thanks).
