### ISSUE TITLE
http:send-request multipart/form-data base64 encoding

### ISSUE THREAD

**Issue by apb2006** [BaseXdb/basex#1487]
## An HTML form that posts two text values to a test server. 
The second text has a UTF8 component
```html
<form  action="http://posttestserver.com/post.php" method="post" 
            enctype="multipart/form-data">
  <input type="text" name="text1" value="text default"/>
  <input type="text" name="text2" value="a&#x03C9;b"/>
  <button type="submit">Submit</button>
</form>
```
The server [shows](http://www.posttestserver.com/data/2017/08/15/10.32.362142876372)
```
Post Params:
key: 'text1' value: 'text default'
key: 'text2' value: 'aÏ‰b'
Empty post body.
```
## Trying to replicate this with `http:send-request`
```xquery
let $target:="http://posttestserver.com/post.php"
let $req:= <http:request method="POST"  xmlns="http://expath.org/ns/http-client">
  <multipart media-type="multipart/form-data"> 
       <header name="Content-Disposition" value='form-data; name="text1"'/>   
       <body media-type="text/plain"/>
       <header name="Content-Disposition" value='form-data; name="text2"'/> 
	 <body media-type="text/plain"/>
</multipart>
</http:request>
return http:send-request($req,$target,("text default","a&#x03C9;b"))
```
The server [shows](http://www.posttestserver.com/data/2017/08/15/10.43.37698171803)
```
Post Params:
key: 'text1' value: 'text default'
key: 'text2' value: 'Yc+JYg==
'
Empty post body.
```
Note the text2 value has been base64 encoded.  I suspect this is wrong and it should just be sent as bytes.

Related mailing list posts:
* https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg09324.html
* https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg09669.html

**Comment by gcelano** [comment]
I do not know how much this is related to this problem, but I cannot send a non-ASCII text with "curl"  via proc:execute() (the function returns gibberish instead of UTF-8). The function is:

```
proc:execute(
"curl",
(  
"-F", "data=@example.txt",  "-F", "tagger=", 
"-F", "parser=",  "http://lindat.mff.cuni.cz/services/udpipe/api/process" )
)
```
@ChristianGruen, I sent you example.txt

**Comment by ChristianGruen** [comment]
I got finally some time to look at this issue.

The first observation: If non-ASCII texts are sent via `http:send-request`, they will be encoded as Base64 (source: [HttpClient.java](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/util/http/HttpClient.java#L268-L280)); a `content-transfer-encoding` is added to indicate how the data is encoded (but it seems it is ignored by http://posttestserver.com, and probably other servers). This behavior was introduced two years to fix some other bugs (https://github.com/BaseXdb/basex/issues/1203). I’ll try to find out when encoding is required, and when we can get rid of it.

**Comment by apb2006** [comment]
"Currently, no deployed implementations that send such bodies have been discovered." :-)
Thanks for this.

**Comment by ChristianGruen** [comment]
So the last existing implementation may be history ;) I decided to discard all the Base64 encoding code (I didn’t found any obvious reason to keep it in the latest version of the code base).
