### ISSUE TITLE
BaseX hangs with some kind of tar.gz files

### ISSUE THREAD

**Issue by BritFox42** [BaseXdb/basex#1488]
Welcome to the BaseX issue tracker! We appreciate your feedback. Please mind the following guidelines:

* Before adding new feature requests and bug reports, please write to our
   basex-talk mailing list: http://basex.org/open-source/.
* You may as well find it helpful to browse through our documentation:
   http://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: http://www.mail-archive.com/basex-talk%40mailman.uni-konstanz.de/

Thanks for your support.

**Comment by BritFox42** [comment]
BaseX hangs with some kind of tar.gz files.
I'm using BaseX 8.6.5 on Windows 10 64bits.

Below are 2 tar.gz files:
- The OK.tar.gz works without any problem.
- The KO.tar.gz make BaseX hangs.

I guess that the problem is due to the .dat file inside the KO.tar.gz

[OK.tar.gz](https://github.com/BaseXdb/basex/files/1227747/OK.tar.gz)
[KO.tar.gz](https://github.com/BaseXdb/basex/files/1227748/KO.tar.gz)

**Comment by ChristianGruen** [comment]
Fixed, thanks. Next time, please have a look at the guidelines before creating a new issues.

New snapshots: http://files.basex.org/releases/latest/
