### ISSUE TITLE
[bxerr:BXDB0002] Database 'test' was not found.

### ISSUE THREAD

**Issue by MOBproject** [BaseXdb/basex#1502]
I write restxq in basex 

![image](https://user-images.githubusercontent.com/17538721/30962093-f31fba40-a437-11e7-920f-587b7e519709.png)
And then save under basex that deploying in tomcat.
I call like that
http://localhost:8080/BaseX866/insert/lay
error is 
"Stopped at /home/khainglay/workstation/apache-tomcat-8.5.20/wtpwebapps/BaseX866/insert.xqm, 9/21:
[bxerr:BXDB0002] Database 'test' was not found."

**Comment by ChristianGruen** [comment]
Sorry for closing this. This doesn’t look like a bug, rather something that should be discussed on our basex-talk list.
