### ISSUE TITLE
WebDAV getlastmodified shows last modified date of db instead of resource

### ISSUE THREAD

**Issue by TomGroeneboer** [BaseXdb/basex#1514]
The getlastmodified property in a WebDAV response returns the last modified date of the database instead of a file. So all resources in a database have the same lastmodified property. If I create a new resource in my database, the lastmodified of all files are updated. 

We're using the getlastmodified since BaseX does not supply the getetag property. Could you please make the getetag work or the getlastmodified correct?

Thanks!

**Comment by ChristianGruen** [comment]
Right now, single XML documents have no individual timestamp in BaseX; that’s the reason why they are not propagated to WebDAV either.

Do you know if getetag is supported by the Milton WebDAV implementation, which is used in BaseX?
