### ISSUE TITLE
Comparison operator strange behaviour

### ISSUE THREAD

**Issue by sofiageo** [BaseXdb/basex#1517]
A very strange issue that I'm not sure how it went unnoticed all this time. This returns false in BaseX from version 8.4.4 up until the latest snapshot.
```
let $start := 2015
let $end := 2013
return not($start <= $end)
```

**Comment by ChristianGruen** [comment]
Wow; it’s rare to come across such bugs today. Thanks for reporting this, one of the operator inversion rules in the compilation phase used a wrong mapping. A new snapshot will be available in around 15 minutes.

**Comment by sofiageo** [comment]
Thanks! I downloaded the new snapshot and it works fine. I guess for people forced to use previous versions `le` works similar to `<=` and it isn't affected by this bug.
