### ISSUE TITLE
CSV Parsing/Serialization: escaping raw data

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1518]
Excel tends to interpret the CSV data and set data types:

* https://stackoverflow.com/questions/29028337/how-to-escape-forward-slash-in-csv
* https://superuser.com/questions/318420/formatting-a-comma-delimited-csv-to-force-excel-to-interpret-value-as-a-string

In order to avoid to this, an option could be added to escape values that might be wrongly interpreted.

**Comment by ChristianGruen** [comment]
Prefixing a field with `=` and quoting the actual value (and double-quoting quotes in that value) may not be sufficient. If the value contains a semicolon, it will be split into two fields, as can be seen with this little CSV document:

```csv
="1/4;5"
```

Some more hints:
* https://stackoverflow.com/questions/4438589/bypass-excel-csv-formula-conversion-on-fields-starting-with-or

**Comment by ChristianGruen** [comment]
Behavior of Excel versions may even differ, depending on regional versions: https://stackoverflow.com/questions/47888753/generating-csv-data-with-slashes-and-semicolons-to-be-imported-with-excel.

Closing this (users may need to resort to the built-in Excel import features).

**Comment by joewiz** [comment]
A great collection of links. Many thanks!
