### ISSUE TITLE
Wrong Optimization for fn:count() and eq with Big Sequences

### ISSUE THREAD

**Issue by LeoWoerteler** [BaseXdb/basex#1519]
The checks in `Cmp#check(OpV, Item)` seem to assume that the number to be compared always fits into a `double` as well as an `int`:

https://github.com/BaseXdb/basex/blob/1059b939b0b72207c3b62a0e0f84f5f9e6804938/basex-core/src/main/java/org/basex/query/expr/Cmp.java#L136-L143

One example where this does not hold is the following query that reimplements `util:replicate(...)`:

```xquery
declare function local:replicate($seq, $n, $out) {
  if($n eq 0) then $out
  else (
    let $out2 := if($n mod 2 eq 0) then $out else ($out, $seq)
    return local:replicate(($seq, $seq), $n idiv 2, $out2)
  )
};
let $n := 1000000000
return (
  count(local:replicate((1,2,3), $n, ())) eq 3 * $n,
  count(local:replicate((1,2,3), $n, ())) = 3 * $n
)
```

The comparison with `=` returns `true()` as expected, but the one with `eq` is pre-evaluated to `false()`:

    Compiling:
    - inline $out2_3
    - simplify gflwor
    - mark as tail call: local:replicate(($seq_0, $seq_0), ($n_1 ...
    - pre-evaluate expression list to xs:integer sequence: (1, 2, 3)
    - pre-evaluate expression list to xs:integer sequence: (1, 2, 3)
    - rewrite = operator to simple = operator: (count(local:replicate((1, 2, 3), $n_4, ...
    - inline $n_4
    - pre-evaluate '*' operator to xs:integer: (3 * 1000000000) -> 3000000000
    - pre-evaluate 'eq' operator to xs:boolean: (count(local:replicate((1, 2, 3), 100000... -> false()
    - pre-evaluate '*' operator to xs:integer: (3 * 1000000000) -> 3000000000
    - simplify gflwor

**Comment by ChristianGruen** [comment]
Thanks for the hint!
