### ISSUE TITLE
dba - databases.xqm

### ISSUE THREAD

**Issue by nikelback** [BaseXdb/basex#1521]
I get an error in the webapp - dba - [databases.xqm](https://github.com/BaseXdb/basex/blob/master/basex-api/src/main/webapp/dba/databases/databases.xqm) module:

``` Stopped at /Users/XXX/Data/BaseX/BaseXWeb/dba/databases/databases.xqm, 52/49:
[XPTY0004] Item expected, sequence found: ("^(.*)-(\d{4}-\d\d-\d\d)-(\d\d)....

Stack Trace:
- /Users/XXX/Data/BaseX/BaseXWeb/dba/databases/databases.xqm, 31/10
```

It appears that the `$regex` (line 47) is passed on to the `replace(..., $regex, ...)` in the for-loop as sequence despite that it is defined before.
Easy fix for me was to move the `$regex` in front of the `$backups` definition.
But since the syntax seems correct for me, there may be a possibility that this is the outcome of a buggy query optimization?!

edit:
After a closer look, i found that this occurs only a dropped DB with **multiple** backups.
I don't know if it is the expected behaviour of the group-by clause to pass the `$regex` variable as sequence / change the variable-scope? Nevertheless it is odd that the position of `$regex` either before or after `$backups` changes the outcome.

**Comment by ChristianGruen** [comment]
Thanks for the hint and your analysis. I haved now moved the regex to a global variable.

The query optimizer behaved correctly indeed. The following query returns `2`:

```xquery
let $a := "A"
for $i in (1,1)
group by $i
return count($a)
```

In XQuery, values of variables will be reassigned after a group by clause. This is somewhat counterintuitive (it doesn’t really go hand in hand with the functional nature of the language if variables change their value), but it can be quite helpful in practice.
