### ISSUE TITLE
XSLT module: unparsed-entity-uri and Catalog

### ISSUE THREAD

**Issue by vincentml** [BaseXdb/basex#1523]
I am using xslt:transform-text and have run into an issue with a transformation that uses unparsed-entity-uri to expand local DTD entity references and requires a Catalog. A solution for #1405 would probably solve this problem, although there is another difference I am seeing.

I am using doc() to parse XML so that certain options including the catalog are used:

declare option db:catfile 'catalog.xml';
declare option db:chop 'false';
declare option db:intparse 'false';
declare option db:dtd 'true';

When I use the output of doc() as input to xslt:transform() then unparsed-entity-uri fails to expand entities. Why is this?

When I provide the file path of the source XML as input to xslt:transform() then unparsed-entity-uri correctly expands the entities. However, the catalog file is not used.

The source XML contains DOCTYPE's referencing URLs that no longer exist or take a long time to load so the catalog file is needed to parse the XML correctly and quickly. My solution for now is to use string replacement to replace the URLs with a file path to the local DTD. 

Attached is an MCVE that has been tested using BaseX 8.6.7 with xml-resolver-1.2.jar and Saxon-HE-9.7.0-15.jar.

[mcve.zip](https://github.com/BaseXdb/basex/files/1494052/mcve.zip)

**Comment by ChristianGruen** [comment]
Thanks for the example. 
> When I use the output of doc() as input to xslt:transform() then unparsed-entity-uri fails to expand entities. Why is this?

If I got it right, it always seems to be the XSL transformer that does the entity expansion, no matter if you pass on a document or a string to the function. I tried Saxon’s XQuery processor, and it does not expand entities either. If I invoke the XQuery function `doc('mcve-A.xml')` with Saxon, I get:

```xml
<?xml version="1.0" encoding="UTF-8"?><article><abstract><graphic entityref="UF0001"/></abstract></article>
```

If I remove the DOCTYPE declaration, the result is:

```xml
<?xml version="1.0" encoding="UTF-8"?><article>
    <abstract>
        <graphic entityref="UF0001"/>
    </abstract>
</article>
```

So maybe we would need to find out how to activate entity expansion in Java (or with Saxon) while parsing XML documents, and we could then think about adding an option for this in BaseX, or enable it by default it DTD is true.

Feedback is welcome.

**Comment by ChristianGruen** [comment]
I’m not quite sure what could be done to resolve the reported issue. Should we close the issue or keep it open?

**Comment by vincentml** [comment]
I think this issue can be closed. Thank you for the analysis.

**Comment by ChristianGruen** [comment]
And thanks for the quick reply.
