### ISSUE TITLE
Failing to connect to basex/dba container on address "http://localhost:18984/"

### ISSUE THREAD

**Issue by Rodrigo2018** [BaseXdb/basex#1528]
The port 18984 is exposed as instructed on the documentation.
Nevertheless, it seems to be a problem related to a unknown function, as described in the error message below:

```Shell
Stopped at /srv/BaseXWeb/modules/util.xqm, 113/18:
[XPST0017] Unknown function: xquery:update (similar: util:update).
```

Both basex/basexhttp and basex/dba containers were runned using the latest tag.
Connection, or access, was made using Firefox Quantum 57.0.1 (64-bit) for Ubuntu 16.04.03.
Is there a fix?

**Comment by ChristianGruen** [comment]
The port number 18984 is not a valid BaseX port number. Apart from that, the Docker image may be outdated.

We would appreciate if you could follow the indicated steps and write to the mailing list first. Thank you.
