### ISSUE TITLE
Incremental update of text index in the presence of mutation of the XML tree (by adding or subtracting subgraphs)

### ISSUE THREAD

**Issue by CMCDragonkai** [BaseXdb/basex#1529]
In the docs it is mentioned that if you switch on `UPDINDEX` option, that text indexes should be incrementally updated upon xquery update operations.

I had a look at how basex might do this (although I don't completely understand it). I mostly care about adding new nodes and removing old nodes, not renaming existing nodes.

Consider a XML tree like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<root>
    <section>
        <heading>S1</heading>
        <keyvalue>
            <key>KEY</key>
            <value>VALUE 1</value>
        </keyvalue>
    </section>
    <section>
        <heading>S2</heading>
        <keyvalue>
            <key>KEY</key>
            <value>VALUE 4</value>
        </keyvalue>
    </section>
    <section>
        <heading>S1</heading>
        <keyvalue>
            <key>KEY</key>
            <value>VALUE 2</value>
        </keyvalue>
    </section>
    <section>
        <heading>S2</heading>
        <keyvalue>
            <key>KEY2</key>
            <value>VALUE 2</value>
        </keyvalue>
        <keyvalue>
            <key>PATH</key>
            <value>somepath</value>
            <root>
                <section>
                    <heading>S1</heading>
                    <keyvalue>
                        <key>KEY</key>
                        <value>VALUE 3</value>
                    </keyvalue>
                </section>
            </root>
        </keyvalue>
    </section>
</root>
```

Running a get query like: `//section[heading = "S1"]/keyvalue[key = "KEY"]/value/text()` gives me:

```
VALUE 1
VALUE 2
VALUE 3
```

This is great, as this is what I want. I want the values to be in "document order". The query optimiser reports that this uses the text index: `db:text("example", "KEY")/parent::*:key/parent::*:keyvalue[parent::*:section[(*:heading = "S1")]]/*:value/text()` and specifically the `KEY` text index.

If I now use an update query and add in a new section:

```
    <section>
        <heading>S1</heading>
        <keyvalue>
            <key>KEY</key>
            <value>VALUE NEW</value>
        </keyvalue>
    </section>
```

Into somewhere in the XML as long as the subtree is between the nodes for `VALUE 1` and `VALUE 2`, then the next time I run the get query, I should get (according to document order):

```
VALUE 1
VALUE NEW
VALUE 2
VALUE 3
```

My question is that, does this kind of update operation result in an _incremental_ update to the text index? And if so, how does it do it?

I'm mainly looking at `org.basex.data.Data.java`, and this only shows updating the name of the index, rather than dealing with structural updates.

https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/data/Data.java#L525-L538

Aside:

My naive implementation of a such an index would be a simple map of text keys to a list of cursors, but doing this doesn't allow mutations to the XML tree to incrementally synchronise with the text index and maintain document order for subsequent queries.

**Comment by ChristianGruen** [comment]
> My question is that, does this kind of update operation result in an *incremental* update to the text index?

The general answer is yes (provided that we have the same mental image of “incremental updates”). Document order will always be preserved in the results, as it is a basic and fundamental requirement of the XQuery path expressions semantics.

> And if so, how does it do it?

For details on the incremental indexing and the related id/pre mapping, you should definitely spend some time with Dimitar Popov’s thesis [Advanced Storage Structures for Native XML Databases](http://basex.org/about-us/publications/). After that, one possible entry point in the code could be the [UpdatableDiskValues](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/index/value/UpdatableDiskValues.java) and [IdPreMap](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/index/IdPreMap.java) classes.

**Comment by CMCDragonkai** [comment]
For an incremental update query I mean something like:

```
insert node (
  <section>
    <heading>S1</heading>
    <keyvalue>
      <key>KEY</key>
      <value>VALUE NEW</value>
    </keyvalue>
  </section>
) before (//section[heading = "S1" and keyvalue[key="KEY"]])[2]
```

I understand that the XML tree would be updated with this new information, but I was hoping to see that the text index would also be incrementally updated (in the sense not needing to traverse the entire tree nor traverse the entire index). Although within these bounds, the implementation could vary.

Thanks for the resources, I'll take a look.

I noticed that my updates don't immediately reflect in my xml file, but I found out about the WRITEBACK option. Just wanted to report that the WRITEBACK option is a bit strange, since by switching this on, it wipes out some "metadata" of the XML file that I was using, specifically things like indentation (it canonicalises it to 2 spaces I think), and throws a way the `<?xml version="1.0" encoding="UTF-8"?>` heading I had in my input file.

**Comment by CMCDragonkai** [comment]
After testing the above query, I found that after that I ran the update operation, the subsequent get operation doesn't use the text index anymore (the query info didn't show the usage of it), instead I had to switch on `AUTOOPTIMIZE` as well before get query would use the text index again.

```
//section[heading = "S1"]/keyvalue[key = "KEY"]/value/text()
```

Gives me query info:

```
Compiling:
- pre-evaluate root() to document-node()
- rewrite descendant-or-self step(s)
Optimized Query:
db:open-pre("example",0)/descendant::*:section[(*:heading = "S1")]/*:keyvalue[(*:key = "KEY")]/*:value/text()
Query:
//section[heading = "S1"]/keyvalue[key = "KEY"]/value/text()
```

Switching on `AUTOOPTIMIZE`, the query info box shows:

```
Compiling:
- pre-evaluate root() to document-node()
- rewrite descendant-or-self step(s)
- apply text index for "KEY"
Optimized Query:
db:text("example", "KEY")/parent::*:key/parent::*:keyvalue[parent::*:section[(*:heading = "S1")]]/*:value/text()
Query:
//section[heading = "S1"]/keyvalue[key = "KEY"]/value/text()
```

**Comment by ChristianGruen** [comment]
You may need to explicitly address the text node:

```xquery
//section[heading/text() = "S1"]/keyvalue[key/text() = "KEY"]/value/text()
```

For adding the text node step, up-to-date database statistics are required; these are not automatically being updated so far.

For more questions, please take advantage of our basex-talk mailing list. Thank you.
