### ISSUE TITLE
Java 9 / macOS

### ISSUE THREAD

**Issue by micheee** [BaseXdb/basex#1535]
```bash
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.basex.gui.GUIMacOSX (file:/Users/mathias/BaseX.jar) to method com.apple.eawt.Application.getApplication()
WARNING: Please consider reporting this to the maintainers of org.basex.gui.GUIMacOSX
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Failed to initialize native Mac OS X interface
$ java -version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
```

**Comment by ChristianGruen** [comment]
Should be identical to…

https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg10162.html
https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg10194.html

The proforma has been tackled (albeit not solved) in 
https://github.com/BaseXdb/basex/commit/c02581c8ed4929ec8f4113eff53cc0ba8132045e#diff-abf6d6ad87f70eca70952cc10affa0b2, so I decided to close this issue again. Current recommendations for users:

* Use Java 8, or
* Use the latest snapshot and live with the restrictions.

**Comment by micheee** [comment]
Thank you! :)
