### ISSUE TITLE
BaseX 9.0 Breaking Build on Windows - With Resolution

### ISSUE THREAD

**Issue by exwhyz** [BaseXdb/basex#1557]
I just upgraded to the latest 9.0 version and noticed that the http server was reporting Unknown Functions across the board. On further review it was identified that several files dated 2016 were included along with files dated 2018 under webapp/dba for the 9.0 build causing conflicts. Deleting all the files dated 2016 resolved the issues for me.

**Comment by ChristianGruen** [comment]
I can follow your observations (thanks), but I am not 100% sure which fix you would suggest. I guess you used the Windows installer, and you would expect an old webapp/dba directory to be deleted before the new files are installed, right?

**Comment by ChristianGruen** [comment]
Resolved (https://github.com/BaseXdb/basex-dist/commit/c724f0212fb8e060abf90cc1db09f0041b880f53).
