### ISSUE TITLE
XQuery: map:merge, wrong map size

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1561]
**XQuery:**

```xquery
declare namespace map = 'http://www.w3.org/2005/xpath-functions/map';
map:size(
  map:merge((
    map { 'A': 'a' },
    map { 'A': 'a', 'B': 'b' })
  )
)
```

**Result:** 3
**Expected:** ~~3~~ 2

Occurs with both 8.6.7 and 9.x.

**Comment by joewiz** [comment]
Did you mean Expected: 2?

**Comment by ChristianGruen** [comment]
Hi Joe, exactly… Thanks for the hint!

**Comment by ChristianGruen** [comment]
First assessment: The bug was introduced at the time when options were added to `map:merge`, and when the default behavior of the function (adding the first instead of the last value when encountering duplicates) was changed in the XQuery 3.1. As a result, the condition in https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/value/map/TrieBranch.java#L134-L135, and probably others, need to be diversified.
