### ISSUE TITLE
Unicode text content is not correct

### ISSUE THREAD

**Issue by SebastianZimmer** [BaseXdb/basex#1562]
I think a regression occured in BaseX 9.0.

When I import the following XML file `test.xml`:
```
<?xml version="1.0"?>
<root>Ö</root>
```
with this script:
```
xquery version "3.1";
declare namespace db = "http://basex.org/modules/db";
db:create("zktest", "test.xml")
```
then the text content is not correct anymore, when quering:
```
> OPEN zktest
Database 'zktest' was opened in 95.16 ms.
> XQUERY //text()
&#xD;&#xD;&#xD;&#xD;







Query executed in 237.18 ms.
```

When executing the command in BaseX 8.6.7, everything is fine:
```
> OPEN zktest
Database 'zktest' was opened in 56.39 ms.
> XQUERY //text()
Ö
Query executed in 6.82 ms.
```

The problematic Unicode char I'm using is `Ö` (U+00D6), but other chars with diaresis don't work either.

**Comment by ChristianGruen** [comment]
Hi Sebastian, this has already been fixed (https://mailman.uni-konstanz.de/pipermail/basex-talk/2018-April/013066.html).

**Comment by SebastianZimmer** [comment]
Alright, thank you. Do you know, when BaseX 9.0.1 stable will be released?

**Comment by ChristianGruen** [comment]
Next week (I invite you to join our mailing list!).

**Comment by SebastianZimmer** [comment]
Will do!

**Comment by ChristianGruen** [comment]
Hi @SebastianZimmer, I got feedback from people who had problem registering on our list. If you encountered similar issues, feel free to tell me, and I’ll dig deeper.

**Comment by SebastianZimmer** [comment]
I've had no issues registering. Thanks for asking.
