### ISSUE TITLE
Importing module should check repository modules first

### ISSUE THREAD

**Issue by a-trifyllis** [BaseXdb/basex#1580]
The importModule function: https://github.com/BaseXdb/basex/blob/176ff837a60b74692d3fdd58cb9e7ed2d704e730/basex-core/src/main/java/org/basex/query/QueryParser.java#L734

Checks if paths are specified and if there are it does not check for the module in the repository modules.
According to the documentation:
"If a module has been placed in the repository (see below), there is no need to specify the location. "
It is not clear that if a location is specified there will be no check in the repository modules (if for example it is not found at the location specified).
Does this work as intended? If so maybe the documentation should clarify that?

**Comment by ChristianGruen** [comment]
Thanks for the observation. I’ll get back to you in appr. 2 weeks.

**Comment by ChristianGruen** [comment]
I have slightly revised the wording in our documentation (http://docs.basex.org/wiki/Repository#Accessing_Modules). I hope this answer your question; if not, feel free to reopen the issue.
