### ISSUE TITLE
GUI: Support natural order within plot

### ISSUE THREAD

**Issue by ChristianLutz** [BaseXdb/basex#1581]
Within the attached image you see two axis in both axies we do have numbers and NA values. I guess this is the reason why it is interpreted as string.

In such cases it would be helpfull if strings would be sorted in natural order instead of 1, 10, 2, 3...

![plot](https://user-images.githubusercontent.com/16245857/41662757-16c4450c-74a2-11e8-9655-af5f691d63d1.png)

**Comment by ChristianGruen** [comment]
Due to the "na" value, your data will be interpreted as strings. I guess it would be a major update to handle special cases like this. Maybe there is a chance to remove these values from your documents instead?

**Comment by ChristianGruen** [comment]
Closing this, because we won’t have free resources to put more energy into this. Volunteers are invited to contribute ;)
