### ISSUE TITLE
GUI: Copy path is incorrect from map

### ISSUE THREAD

**Issue by ChristianLutz** [BaseXdb/basex#1583]
Hello,

if you use the copy path command from the GUI-Map (9.0.1) context menu then the copied path is wrong. E.g. 

`db:open("BA", "sensors.xml")/record/record/record/record/record `

only the last path part is correct.

**Comment by ChristianGruen** [comment]
Thanks Christian, the bug has been fixed (https://github.com/BaseXdb/basex/commit/cad5350c0d44fd8dc661418d8b6955cc686d1a23).
