### ISSUE TITLE
XPATH with two attribute bug

### ISSUE THREAD

**Issue by ChristianLutz** [BaseXdb/basex#1587]
Hello

I guess I found a bug in the latest version 9.0.2. 

How to reproduce: 
I am using the provided factbook example.

`
let $id := 'f0_162'
let $value := db:open('factbook')/mondial/country[@id=$id]/religions[@percentage='75']
return <value>{ $value }</value>
`

This returns an empty `<value/>`  what is the wrong result. But it if you replace the last equals symbol with eq what is the same.

`
let $id := 'f0_162'
let $value := db:open('factbook')/mondial/country[@id=$id]/religions[@percentage **eq** '75']
return <value>{ $value }</value>
`

It will return the correct result.
`
<value>
<religions percentage="75">Roman Catholic</religions>
</value>
`

kind regards 
Christian

**Comment by ChristianGruen** [comment]
Definitely something that needs to be fixed, thanks.

The query is correctly rewritten, but the index value gets lost in the resulting query:

**Optimized Query:**

```
db:attribute("factbook", ())/self::*:percentage/parent::*:religions[parent::*:country[(@*:id = "f0_162")]/parent::*:mondial/parent::document-node()]
```

**Compiling:**

```
- pre-evaluate db:open(database[,path]) to document-node(): db:open("factbook") -> db:open-pre("factbook", 0)
- apply attribute index for "75"
- inline $id_0
- simplify gflwor
```

**Comment by ChristianLutz** [comment]
Hello Christian,

thank you for the fix.

greetings
