### ISSUE TITLE
macOS GUI: Various Issues

### ISSUE THREAD

**Issue by holu** [BaseXdb/basex#1591]
When closing the main GUI (via upper, left, red close-button) the application BaseXGUI is still running.
There is, however, no way to open a new 'main' window again.

An entry in the main menubar in 'View' with 'Main window CMD+0' or something similar would be nice.

Relates #1582

**Comment by jb8748** [comment]
I know it's not intuitive and a bit of a workaround but I've noticed that if you close the main window and then click on the Dock icon a new main window will be displayed.

**Comment by ChristianGruen** [comment]
Some additional issues (with BaseX 9.x, probably only with version >= 9 of Java):

* The Preference menu option (which is located in the Options menu on Windows system) seems to be missing on Mac.
* An exception is displayed on command line.

```
java.lang.NoSuchMethodException: java.awt.Desktop.setAboutHandler(org.basex.gui.GUIMacOSX9)
    at java.base/java.lang.Class.getMethod(Class.java:2109)
    at org.basex.gui.GUIMacOSX9.initAboutMenu(GUIMacOSX9.java:89)
    at org.basex.gui.GUIMacOSX9.init(GUIMacOSX9.java:56)
    at org.basex.gui.GUI.<init>(GUI.java:148)
    at org.basex.BaseXGUI.lambda$0(BaseXGUI.java:62)
```
