### ISSUE TITLE
XQuery: util:or

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1614]
When coding, it frequently happens that you want to work with a value, or use a default value instead if this value is not available (null, undefined, … In XQuery, we have an empty sequence).

Perl provides the `//` operator for this; in C#, you can use `??`. If the value to be tested is not `0` or an empty string, some languages allow you to use `||` or the `or` operator.

We shouldn't extend the syntax of XQuery, but introduce a little helper function:

```xquery
util:or($value, 'default')
```

Suggestions for a better (or canonical?) function name are welcome.

Wikipedia: https://en.m.wikipedia.org/wiki/Null_coalescing_operator

**Comment by apb2006** [comment]
So the semantics would be as `eg:if-empty` or `eg:if-absent` ?
https://www.w3.org/TR/xpath-functions-31/#if-empty-or-absent

**Comment by ChristianGruen** [comment]
Interesting, I was not aware of the existence of these functions. The semantics would be similar to `eg:if-absent` indeed.

**Comment by ChristianGruen** [comment]
A suggestion (thanks @dominikk): `util:if-exists`.
Symmetrical (`if (exists) then first-argument else default`).

**Comment by ChristianGruen** [comment]
One more suggestion (thanks @micheee): `util:default-or`.

**Comment by ChristianGruen** [comment]
The resulting function is now called `util:or`: http://docs.basex.org/wiki/Utility_Module#util:or.
