### ISSUE TITLE
Support Xerces 2.12 with XML-Schema 1.1

### ISSUE THREAD

**Issue by ChristianLutz** [BaseXdb/basex#1615]
Hello,

Version 2.12. of Xerces  is final, [now](http://xerces.apache.org/news.html). 
But this version isn't compatible with basex (current version 9.0.2) and XML-Schema 1.1, anymore. 
Also the two files 
- cupv10k-runtime.jar and
- org.eclipse.wst.xml.xpath2.processor_1.1.0.jar
have been removed from the binary package.

However, the old files are available in the [archive](http://archive.apache.org/dist/xerces/j/).

Would it be even possible to provide xerces per default within your distribution? Or are there any [legal](https://softwareengineering.stackexchange.com/questions/40561/is-bsd-license-compatible-with-apache) problems?

regards
Christian

**Comment by ChristianGruen** [comment]
PS: For feature requests, please write to our basex-talk mailing list first.

**Comment by ChristianLutz** [comment]
Yes, sorry, I should have done it in the first place.

1. I replaced all four libs of the previous xerces installation with the current xml-api.jar and xercesImpl.jar
=> `[validate:version] No XML Schema implementation for version '1.1'.`
2. Than I checked the source ValidateXsd.java and found a reference to `org.apache.xerces.jaxp.validation.XMLSchema11Factory`. But this class doesn't exist within xercesImpl.jar. 

So I guess, the API has changed.

**Comment by ChristianGruen** [comment]
I see; thanks. If you find out how validation works with the new version of the lib, and if you could paste a little Java example here, that’d be great! We could then add it to our reflection invocations.

Regarding your second question: As we want to keep our distribution as small as possible, we are somewhat hesitant to add new libraries. The current size of the additional library files is around 6 mb.  For Xerces2, we’d need to add 2.2 more mb, and we should surely check if the libraries will affect the overall behavior of BaseX. We’ll at least have some thoughts on your suggestion.

**Comment by ChristianGruen** [comment]
Hi @ChristianLutz, one more question: I would like to compare the changes in the Xerces code. Could you tell me a recent version of Xerces which was still compatible with BaseX?

**Comment by ChristianLutz** [comment]
Hello @ChristianGruen, I used the 2.11 beta version from 2014-10-30. I haven't tested the 2.12 version, yet.

**Comment by ChristianGruen** [comment]
Hi @ChristianLutz, sorry for letting you wait, I finally had the time to look at your issue. And I’m sorry, as I still cannot see what we should do here:

* As far as I can judge, the required JAR libraries are still contained in the archives of the new version of Xerces2. Did you really download `Xerces2 Java 2.12.0 (XML Schema 1.1)`, which is offered on the official web site (http://xerces.apache.org/mirrors.cgi#binary)?
* The class `org.apache.xerces.jaxp.validation.XMLSchema11Factory` is contained in both version 2.11 beta and 2.12.

What else could I have a look at?

**Comment by ChristianLutz** [comment]
Hello @ChristianGruen,

you are right there is a new binary containing the Schema 1.1 so I used this one and it worked like charme. I guess I used the wrong binary somehow.

So I close this issue. Thx
