### ISSUE TITLE
RELAX NG: invalid documents incorrectly reported as valid

### ISSUE THREAD

**Issue by AndrewSales** [BaseXdb/basex#1622]
Following query should return an error, `IDREF "a" without matching ID`:

    validate:rng-report(
      <test><link to='a'/><target id='a1'/></test>,
      'datatypes xsd = "http://www.w3.org/2001/XMLSchema-datatypes"

      element test { 
        element link{ 
            attribute to{xsd:IDREF}
        },
        element target{
            attribute id{xsd:ID}
        }
    }',
      true()
    )

However, it returns:
  `<report>
    <status>valid</status>
  </report>`

The same documents validated using the bundled `jing` distribution (`jing-20091111.jar`) do produce the expected error, e.g.
 `c:\temp\jing-id-test.xml:2:21: error: IDREF "a" without matching ID`

Observed in BaseX 8.6.7 and 9.0.2.

**Comment by ChristianGruen** [comment]
I have built a simple Java example, based on `jing-20091111.jar`, to get the reported behavior reproduced:

```java
import java.io.ByteArrayInputStream;

import org.xml.sax.InputSource;
import com.thaiopensource.util.PropertyMapBuilder;
import com.thaiopensource.validate.SchemaReader;
import com.thaiopensource.validate.ValidationDriver;
import com.thaiopensource.validate.rng.CompactSchemaReader;

public class RelaxNGTest {
  public static void main(String... args) throws Exception {
    String schema = "element xml { attribute idref { xsd:IDREF } }";
    String doc = "<xml idref='a'/>";

    PropertyMapBuilder pmb = new PropertyMapBuilder();
    SchemaReader sr = CompactSchemaReader.getInstance();
    ValidationDriver vd = new ValidationDriver(pmb.toPropertyMap(), sr);

    vd.loadSchema(new InputSource(new ByteArrayInputStream(schema.getBytes())));
    vd.validate(new InputSource(new ByteArrayInputStream(doc.getBytes())));
  }
}
```

It doesn’t raise any error on my system on STDERR. It raises errors, however, if I add other errors (e.g. if I use a wrong element name).

Could you possibly look at the Java snippet and see how it behaves on your system? Maybe some flags are enabled in your test case that are not enabled by default?

**Comment by AndrewSales** [comment]
Exactly, apologies for omitting that vital piece of information - and many thanks!
