### ISSUE TITLE
DBA: Tweaks

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1631]
* Files Panel: Include navigation links if number of table entries exceeds current maximum
* Logs Panel: Display results if search term occurs either in the login name or the full error text

**Comment by mgaerber** [comment]
Maybe:
* Logs Panel: filter out requests to the DBA itself

**Comment by ChristianGruen** [comment]
Done. @mgaerber: In the DBA Settings, there’s an option now to ignore DBA log entries

**Comment by mgaerber** [comment]
yay!

**Comment by ChristianGruen** [comment]
I have reopened this issue. We should generalize the feature for filtering our DBA matches and allow arbitrary substrings or even regular expressions.
