### ISSUE TITLE
BaseX failed to start on JDK 11

### ISSUE THREAD

**Issue by erchbox** [BaseXdb/basex#1651]
Hi,
I inadvertently installed openjdk11 (it was checked by default) on top of  the following platform:

OS: **openSUSE Leap 15.0 kernel: 4.12.14-lp150.11-default**
Application Server: **Apache Tomcat/9.0.12**
Java: **openjdk 11.0.1 2018-10-16**
OpenJDK Runtime Environment (build 11.0.1+13-suse-lp150.2.9.1-x8664)
OpenJDK 64-Bit Server VM (build 11.0.1+13-suse-lp150.2.9.1-x8664, mixed mode)

When trying to Start the BaseX911 application I got the following error in Tomcat Manager:
**FAIL - Application at context path [/BaseX911] could not be started
FAIL - Encountered exception [org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/BaseX911]]]**

I removed openjdk11 and installed openjdk8 and BaseX is up and running.

Are you guys planning to support JDK 11 soon?

Thanks!

**Comment by ChristianGruen** [comment]
I’m wondering if it’s the Tomcat combination that leads to the reported error. Are you referring to the war servlet, which you tried to deploy in Tomcat? Did you try to run BaseX als self-contained application?

**Comment by erchbox** [comment]
I have always deployed BaseX on Tomcat/Linux.
Keep in mind that it is working now on Tomcat after I downgraded to Java 8 from the default Java 11 what suggests that the issue is with Java instead of Tomcat.

**Comment by ChristianGruen** [comment]
I couldn’t reproduce the issue with an initial Tomcat installation, OpenJDK 11 and Ubuntu. Maybe it was a version conflict on your system (see e.g. https://stackoverflow.com/questions/28753473/org-apache-catalina-lifecycleexception-failed-to-start-component-standardserve)?

Feel free to send us the full Tomcat log data, maybe this gives us some more clues.

**Comment by erchbox** [comment]
Sorry I cannot be of more help right now but leaving for a long trip abroad. However you could easily reproduce the case I described by downloading openSUSE 15 Leap from https://software.opensuse.org/distributions/leap

**Comment by ChristianGruen** [comment]
I’ll leave this open for a while; if no one else confirms problems with OpenJDK 11, I’ll close the issue, and people can reopen it if needed.

**Comment by ChristianGruen** [comment]
@b-itkin: I am afraid we can’t fix segmentation faults in Java. I hope this will be solved in the next version of the JDK. Did you try version 11?

**Comment by holu** [comment]
Just to add test results regarding JDK11. BaseX runs fine with the following version:
```
$ java -version
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```
