### ISSUE TITLE
/dba unavailable with defect .xql scripts in webapp directory

### ISSUE THREAD

**Issue by zopyx** [BaseXdb/basex#1652]
The `/dba` interface gives an error

```
Stopped at /home/ajung/sandboxes/basex/webapp/foo.xql, 8/15:
[XPST0003] Unexpected end of query: '>...'.
````

when the webapp folder contains a script with errors...

The Web UI should be available all the time.

**Comment by zopyx** [comment]
Buggy code should not go into production, agreed.

But as part of development cycle it is possible that buggy code exists and it should not break any other functionality like the DBA interface.

**Comment by ChristianGruen** [comment]
I have added some code to exclude modules that cannot be parsed.
