### ISSUE TITLE
%output:method("json") generating improper response (quoted XML instead of JSON)

### ISSUE THREAD

**Issue by zopyx** [BaseXdb/basex#1655]
Defining `%output:method("json")` returns an HTTP response with `content-type: application/json` and returns the XML as a quoted string. This makes no sense - neither the quoting nor the XML return. 

Only an additional `%output:json("format=jsonml")` generates a valid JSON document. All other formats `xquery`, `direct` and `attributes` do no generate a proper JSON output.

The output must generate JSON by default (it should not be necessary to specify an explict `format`. It should default to `direct` as documented.

**Comment by ChristianGruen** [comment]
Strings are valid JSON, too, so the result is correct (albeit not what you would expect).

Please read the specs in order to understand how JSON serialization works, or ask on the list first before creating new GitHub issues. Thanks in advance!

**Comment by ChristianGruen** [comment]
Here are two links on that topic:
* JSON serialization in BaseX: http://docs.basex.org/wiki/XQuery_3.1#JSON_Serialization
* JSON format (root values can be objects, arrays, strings, etc): http://json.org/
