### ISSUE TITLE
Docs confusing re use XQDT

### ISSUE THREAD

**Issue by dentarthur** [BaseXdb/basex#1656]
I am a newbie unfamiliar with all three. But after careful research I am assuming optimum combination for trying out BaseX with XQuery 3+ is with both Eclipse IDE and oXygen.

Reporting as problem here as found docs very confusing. Perhaps due to my ignorance, perhaps not.

http://docs.basex.org/wiki/Integrating_oXygen

Says to use XQJ for XQuery. But this only supports XQuery 1.0?

XQDT supports XQuery 3+ and oXygen Enterprise edition uses it to connect to Marklogic.

BaseX uses it to integrate with Eclipse:

http://docs.basex.org/wiki/Integrating_Eclipse

Both docs may be out of date. Eclipse IDE 2018-12 includes DLTK so no need to install it.

Is there some way to use XQDT for oXygen direct to BaseX without needing Enterprise edition and without needing to use Eclipse?

If so BaseX should document it.

Otherwise I assume best to use Eclipse plugin version of oXygen connected by XQDT to BaseX.

**Comment by ChristianGruen** [comment]
Thanks for your observations. It’s true, the documentation on Eclipse and oXygen has not been updated for a while. As far as I know, many people use IntelliJ today, in combination with the excellent XQuery plugin from @rhdunn (https://plugins.jetbrains.com/plugin/8612-xquery-intellij-plugin).

> Is there some way to use XQDT for oXygen direct to BaseX without needing Enterprise edition and without needing to use Eclipse?

I don’t know. Would you be willing to talk to the developers of oXygen? Maybe they can tell us more about it.

**Comment by dentarthur** [comment]
Thanks for tip on option to use IntelliJ XQuery plug-in instead of Eclipse.
I will keep that in mind as perhaps less "heavy" than Eclipse though not
sure how to combine with non-Eclipse standalone version of OXygen.

No, sorry cannot follow up with oXygen support. Still doing preliminary
study to consider options and have not installed anything at all.

Presumably no technical problem for XQDT there since Enterprise edition
uses it with Marklogic but they may have marketing reasons to not mention
whether works with their cheaper editions.

Feature Matrix shows eXist but not Marklogic support for non-enterprise
versions. Does not mention BaseX at all, so up to BaseX to proclaim any
support (or perhaps to provide it).

https://www.oxygenxml.com/xml_editor/feature_matrix.html

Here is all they say about BaseX:

https://www.oxygenxml.com/doc/versions/20.0/ug-editorEclipse/topics/basex-support.html#basex-support

Simpler for some BaseX user with non-enterprise standalone version of
oXygen to check XQDT themselves or ask oXygen support.

Free trial 30 day licenses available for each version. I guess most BaseX
users would be using an IDE and if using oXygen would have an eclipse
plugin version but perhaps same license key applies to both standalone and
Eclipse plugin versions?

BaseX developer fixing docs could check by getting free trial
personal/academic/professional standalone version and asking oXygen support
if necessary.

https://www.oxygenxml.com/xml_editor/register.html

Also perhaps worth developer adding  BaseX support if not already there.
Claims full extensibility with free SDK:

https://www.oxygenxml.com/xml_editor/dita_cms_and_extensibility.html

https://www.oxygenxml.com/doc/versions/20.1/ug-editor/topics/xproc-API-external-engine.html

I am looking for simple use of Editor for DITA by non-technical author
without added confusion from an IDE. BaseX backend should be a good fit.

https://www.oxygenxml.com/xml_editor/dita_editor.html

https://www.oxygenxml.com/xml_editor/dita_editor_structured_editing.html

https://www.oxygenxml.com/xml_editor/dita_maps_manager.html

etc etc follow links

Also

https://www.oxygenxml.com/doc/versions/20.0/ug-editorEclipse/topics/migrate-archives.html

Similar use cases for other WYSIWYG eg docbook and epub authors:

https://www.oxygenxml.com/xml_editor/WYSIWYG_Editors.html

https://www.oxygenxml.com/xml_editor/docbook_editor.html

https://www.oxygenxml.com/xml_editor/epub.html

I am just reporting doc problem to BaseX as should fix if in fact not
restricted to XQJ with no XQuery 3 for widely used oXygen standalone Editor.

**Comment by siserle** [comment]
Dear Arthur,

I updated the BaseX Documentation a few days ago regarding oXygen, Eclipse and IntelliJ.

My first proposition to you, and your non-technical DITA author, would be to use the built-in BaseX editor itself to edit and query your DITA data. In that case, you'd have the power of BaseX **and** XQuery 3.1. readily at your command.

However, your DITA author might already be used to working with oXygen and its DITA features. In that case, you will have to opt for XQJ and XQuery 1.0.

Since XQDT seems to be no longer supported by the latest Eclipse version, I deleted the page "Integrating with Eclipse" from our BaseX documentation.

Instead, I added some step-by-step instructions on "Integrating IntelliJ" using either  the XQuery Support + MarkLogic Debugger plugin by Grzegorz Ligas or the xquery-intellij-plugin by Reece H. Dunn.

I hope this helps you. If you have any further questions, please feel free to contact us.

Best regards, Sabine

**Comment by dentarthur** [comment]
Thanks!!

The docs are quite clear now, so feel free to close this issue.

http://docs.basex.org/wiki/Integrating_IntelliJ_IDEA

Coincidentally I just discovered "DITA for small teams" a couple of days ago, links about it are at my notes here:

https://github.com/thecapitalistcycle/tech-indexing/blob/master/dita-for-small-teams.md

As I understand it they use BaseX directly for XQuery 3.1 as you suggest,  (via your RESTXQ API while still using oXygen for authoring/editing):

http://www.d4st.org/topics/tools-basex.html

As a separate issue, please consider whether BaseX could take an initiative to ensure integration with Eclipse for XQuery 3.1. We don't need it immediately in view of your advice and above confirmation of it and I really have no understanding at all of what the relevant issues are. But I am pretty sure we will eventually be using Eclipse for many things as others do and will find it surprising that BaseX does not integrate with it fully.

Deletion of:

http://docs.basex.org/wiki/Integrating_Eclipse

is very clear.

But is it really satisfactory given the widespread use of Eclipse including for development of BaseX?

http://docs.basex.org/wiki/Developing_with_Eclipse

Perhaps BaseX developers could find some way to adopt one or both of the methods you document for fully integrating with IntelliJ to also work with Eclipse. Marklogic does so BaseX might benefit from doing so?

**Comment by siserle** [comment]
Thanks again for your comprehensive feedback!

I will make sure that we will internally discuss integration with Eclipse once more!
