### ISSUE TITLE
A function contained in a comment will be evaluated

### ISSUE THREAD

**Issue by ChristianLutz** [BaseXdb/basex#1658]
Hello,

I am using basex 9.1.1 and I do see the following behavior.

I created a public function

```
declare function big:foo() as element()* {
  let $x := <a><b>1</b><b>2</b></a>
  return <group>
    <n>dim</n>
    (: <size>{big:bar($x)}</size> :)
  </group>
};
```
and in the same file I created the private function
```
declare %private function big:bar($x as element()) as xs:number {
   fn:number($x/b)
};
```
executing this leads to an error like `[XPTY0004] Item expected, sequence found:`  This is correct if the function is in use. But it isn't. 
If I remove just the comment from the method, `foo()` works. So for some reason the method within the comment will be evaluated during execution. 

Sincerely

**Comment by dominikk** [comment]
Hi @ChristianLutz,

`big:foo` returns a group element that contains a text node: `(: <size>{big:bar($x)}</size> :)`. Hence, the function call is evaluated. To prevent this, you have to use xml-comments, see below:

```xml
<group>
  <n>dim</n>
  <!--<size>{big:bar($x)}</size>-->
</group>
```
