### ISSUE TITLE
White spaces are dealt as element's text under certain situations

### ISSUE THREAD

**Issue by mhoss-id1** [BaseXdb/basex#1665]
Hello,

the following code runs perfectly under BaseX 8.6.4 but I get "[XPTY0004] Item expected, sequence found: (text {" "}, text {" "})." at line 5/50 under 9.1.2
Could you please help me what is the best way to avoid this problem?

Regards,
Moe

```xml
declare function local:test( $a as item() ) as item()
{
   copy $tmp := $a/a
   modify (
      for $b in $tmp/b[normalize-space( ./text() ) = "text"]
      return
        ()
   )
   return $a
};

'<a>
   <b>
     <c/>
   </b>
</a>'
=> parse-xml()
=> local:test()
```

**Comment by ChristianGruen** [comment]
I guess that the implementation of `parse-xml` had some flaws in version 8. The `b` element has two text nodes indeed:

```xml
count(parse-xml('<a>
 <b>
   <c/>
 </b>
</a>')/a/b/text())
```

For general questions on XQuery and unconfirmed bug reports, please write to our [basex-talk mailing list](https://mailman.uni-konstanz.de/mailman/listinfo/basex-talk).

**Comment by mhoss-id1** [comment]
Thanks for the reply. I subscribed for the mailing list to be able to sent to it this morning, but I get no confirmation email or any other feedback. So I put this here.

**Comment by ChristianGruen** [comment]
Sorry, that’s unusual. Feel free to contact [mailman@mailman.uni-konstanz.de](https://mailman.uni-konstanz.de/mailman/listinfo), or send me a private mail if you don’t get the confirmation until tomorrow morning.

**Comment by ChristianGruen** [comment]
PS: If you want to check if at least one of the text nodes equals the `text` string, you can rewrite your query as follows:

```xquery
$tmp/b[(text() ! normalize-space()) = "text"]
```
