### ISSUE TITLE
Windows version: BaseX GUI launcher not working - Launch jar is work-around

### ISSUE THREAD

**Issue by Jim-Salmons** [BaseXdb/basex#1675]
My dev box is Windows 10 with Java JDK 10.0.2 which reports its JRE version as 18.3. After standard installation of version 9.1.2, double-clicking the BaseX GUI icon launcher on the desktop brings up a dialog saying ""This application requires a Java Runtime Environment 1.8.0 The registry refers to a nonexistent Java Runtime Environment installation or the runtime is corrupted."

I completely checked my registry for zombie entries and found none. I can however stop and start the server, the standalone version, and the command-line client, etc.

So I went to the BaseX installation directory to look for configuration info that might be akimbo and saw nothing unusual. Seeing the Explorer listing of both the BaseX.exe and executable BaseX.jar, I decided to try them both directly in the installation directory. Same result with the exe file with the nifty logo, no go with the dialog about requiring Java JRE 1.8.0. The executable jar, however, popped open in all its BaseX GUI glory!? :-)

WORK-AROUND: Simply recreate a generic Java desktop shortcut icon that directly starts the jar. Works fine but it doesn't have the snazzy BaseX GUI icon of the currently funky exe launcher.

Second small point... while tweaking whatever is causing this BaseX GUI launcher issue, you might want to change or delete the Community menu item under the Help menu as it links to a missing page on the basex.org website.

Now that I have the GUI running, I am a happy camper ATM. When a fix is in for this small issue, I will gladly test it. However, my learning progress is not impacted as the work-around above solves the immediate issue.

**Comment by ChristianGruen** [comment]
Jim, thanks for your feedback! We are aware of this current limitation, it’s due to the exe wrapper code that launches BaseX. It will be fixed with the upcoming release of BaseX 4.2 (to be expected in 1, 2 weeks).

**Comment by ChristianGruen** [comment]
We‘ve uploaded a new (stable) snapshot of our Windows installer. The exe wrapper skips the version test, but (unfortunately) requires the environment variable `JAVA_HOME` to be set. Unfortunately, this variable is not assigned by all JDK/JRE distributions.

We hope that the issue will soon be tackled by the launch4j developers which BaseX is based on:
* https://sourceforge.net/p/launch4j/bugs/197/
* https://sourceforge.net/p/launch4j/feature-requests/127/

**Comment by ChristianGruen** [comment]
And yet another update: No need to test the current snapshot. On Monday, we’ll upload a new snapshot, which gets rid of launch4j and the exe wrapper. We’ll simply do what you’ve done anyway, and create icons for the JAR (or the basexgui.bat) file for the Windows installer. I’ll keep you updated!

**Comment by ChristianGruen** [comment]
Hi Jim, I invite you to have a quick look at the [latest snapshot](http://files.basex.org/releases/latest/). We have dropped the `exe` file and linked the `bat` startup script. In addition, I have updated the community link in the BaseX GUI.

**Comment by Jim-Salmons** [comment]
Yipes... Have a gnarly gotcha after having installed the latest snapshot.

PROCESS FOLLOWED: 1. Changed name (did not uninstall) 9.1.2 prior version of BaseX. 2. Installed the latest exe build. 3. Ran the new BaseX GUI desktop icon and got an error message in the command prompt window saying DOSKEY not recognized and a error pop-up saying javaw could not be found!?

ISSUE SEEMS TO BE: When I inspect my system variables' PATH, the _only_ entry points to the BaseX/bin directory where I installed it. ALL other entries are gone! :-(

Am looking into ways to recover my path or will do a backup recovery to see if I can get it back or something close to it. ITMT, this build may not be ready for Prime Time. :-/

**Comment by ChristianGruen** [comment]
Oh dear. I’m sorry to hear that our installer messed up your system! And I’m surprised, because I didn’t change anything regarding the modification of the PATH environment variable (the only thing I did was switching to the latest version of the NSIS installer). I just tried the installer on a fresh Windows installation, and PATH was correctly extended. Be sure I’ll spend some more time to find out what might have gone wrong on your system!

**Comment by ChristianGruen** [comment]
This is the default value of the PATH variable (taken from https://superuser.com/questions/973153/standard-value-of-path-variable-windows-10): 

```
%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
```

Sorry again; I’ll check the NSIS forums if someone has experienced similar problems in the NSIS forums.

**Comment by ChristianGruen** [comment]
As our user never reported problems with our installer and the PATH variable, the only guess I have is that the new NSIS version might have caused the problems. I decided to revert to the old version, and I have create a new snapshot; I’m not sure if you are motivated enough to give it a try…

**Comment by Jim-Salmons** [comment]
Okay... and update. I have fully recovered and am in the position to test if this was a real issue or a gremlin one-off gotcha. ITMT, here are tips for anyone who has this problem whether created by a real or one-off gotcha...

0. I have for years depended on the brilliant Registrar Registry Manager from Resplendence, https://www.resplendence.com/registrar. Fortunately, I used the free Home edition to backup my registry in late February. So rather than have to do a full system restore or a System Point restore point, I was able to do the following...

1. The current registry _may_ have a copy of a nuked PATH env variable string at this registry location (where 'X' is an integer 1, 2, whatever): 

    HKEY_LOCAL_MACHINE\SYSTEM\ControlSet00X\Control\Session Manager\Environment\Path

2. If your missing path is there in the current registry, copy it for pasting into the System provided environment variable editing interface at: Control Panel > System & Security > System > Advanced System Settings > Advanced tab > Environment Variables button where you can simply paste in your recovered PATH string from step 1.

3. If the current PATH is in the System partition of your registry is nuked, too, you can turn to any backup you may have of your Windows registry and dig for this value at the location mentioned above.

4. If you have a RegRegMgr backup of your registry! :-) The easy thing is first backup the current state of your registry and then simply restore the latest of your old registry backups, reboot, use RegRegMgr to copy the PATH from the above location in your old copy of the reg and save it to a file, restore your nuked registry, reboot, and use the procedure in step 2 to copy and paste the old path from the recovery file into your current environment variable.

BONUS TIP: In addition to using Registrar Registry Manager, I use the equally brilliant Rapid Environment Editor (https://www.rapidee.com/en/about) to manage all Windows-based environment configurations.

**Comment by Jim-Salmons** [comment]
BTW, once I did this path recovery, I was able to double-click the BaseX GUI desktop shortcut from the latest build and it opened cleanly as expected. :-)

BONUS WINDOWS TOOL TIP: In addition to RegRegMgr and Rapid Environment Editor mentioned above, another absolutely BRILLIANT secret weapon tool I use frequently during development is Jan Goyvaert's RegexBuddy (https://www.regexbuddy.com/). I have NEVER seen _any_ tool that comes close to the rich feature set of this regular expression IDE. Seriously run, don't walk to check this out if you have regular need to do complex regex authoring. BTW, it knows all about XPath and XML Schema regexes as well as many regex varieties used in many different programming languages and platforms.

**Comment by ChristianGruen** [comment]
That’s good news. And I hope the latest installer will keep your environment alive and healthy?

Talking about secret weapons… Total Commander (ghisler.com) is the main reason why I’ve always sticked to the Windows operating system. It takes months, if not years, to get to know the full power of this tool and all its hidden features and shortcuts.

**Comment by Jim-Salmons** [comment]
Hi @ChristianGruen, 

Indeed, I remember Total Commander from the very early days on Windows, back when it would be among the go-to system tweaking and maintenance tools you would put on those tiny-capacity thumb drives because hardware was so much less "self-healing" than it is today.

Oh, and BTW on the recovery from your PATH system environment variables getting nuked... the simplest method to be prepared for a quick recovery (as I have now done) is simply to pipe your PATH to a file and have it handy for a quick copy-paste if needed. 

You could even backup a user's PATH to a date-stamped file silently in the BaseX directory as a 'help if ever needed' step during the BaseX install process. :-) So, with up-to-date PATH in hand, I will be ready to try an updated build whenever it is appropriate.

As to my comment on RegexBuddy, Jan Goyvaerts is a total Windows Tool God!!! Besides RegexBuddy, all his tools are awesome, https://www.just-great-software.com/. I have had PowerGREP and AceText (awesome!!!) in my must-have toolkit for years.

**Comment by ChristianGruen** [comment]
I got confirmed by some other users/clients that the latest snapshot seems to be working as expected. Do you think we can close this issue?

**Comment by Jim-Salmons** [comment]
I'll close this and keep an eye out for the next release and do its installation to see if I have a recurrence of this issue. One possibility is that the other folks may have done a "correct" uninstall and reinstall, or a clean install in their cases, where I did a (dubious maybe) renaming of my current installation directory (to '../_basex/' from '../basex/') and then did the trial install... _maybe_ that had am impact on my munged PATH... that, or I just had a gremlin show up and throw me a curve on that particular morning.

**Comment by Momischmiddi** [comment]
Still present with version 9.3.3

**Comment by ChristianGruen** [comment]
What exactly?
