### ISSUE TITLE
Taking time to add xml's to collection

### ISSUE THREAD

**Issue by vcsred** [BaseXdb/basex#1681]
Hi all,
We have already created one collection after that adding xmls to that collection,This process is taking much time and the total xml are nearly 2 lakhs. How to get performance to add xmls to collections.

We are using basex client server architecture with java technology to perform creating collection and adding xmls to collection.

**Comment by ChristianGruen** [comment]
Hi, your questions are welcome, but please (as stated in the initial comment in the issue) direct them to our mailing list. Thanks in advance.
