### ISSUE TITLE
inspect:xqdoc o/p invalid against schema

### ISSUE THREAD

**Issue by apb2006** [BaseXdb/basex#1683]
I notice the o/p reverses the positions of `xqdoc:namespaces` and `xqdoc:imports`

```
"https://raw.githubusercontent.com/BaseXdb/basex/f84183c1ac3006d7e1fa85e22147186f03bce305/basex-api/src/main/webapp/dba/files/files.xqm"
=>inspect:xqdoc()
=>validate:xsd-report("http://files.basex.org/etc/xqdoc-1.1.30052013.xsd")

<report>
  <status>invalid</status>
  <message level="Error" line="4" column="39">cvc-enumeration-valid: Value '1.1' is not facet-valid with respect to enumeration '[1.0, N/A]'. It must be a value from the enumeration.</message>
  <message level="Error" line="4" column="39">cvc-type.3.1.3: The value '1.1' of element 'xqdoc:version' is not valid.</message>
  <message level="Error" line="23" column="18">cvc-complex-type.2.4.a: Invalid content was found starting with element 'xqdoc:imports'. One of '{"http://www.xqdoc.org/1.0":variables, "http://www.xqdoc.org/1.0":functions}' is expected.</message>
</report>
```

And perhaps the version "1.1" should be in the schema?

**Comment by ChristianGruen** [comment]
> I notice the o/p reverses the positions of `xqdoc:namespaces` and `xqdoc:imports`

Thanks; I have reversed the order of the elements.

> And perhaps the version "1.1" should be in the schema?

The referenced schema has been taken from the [official homepage](http://xqdoc.org/xqdoc_schema_doc.html) a long time ago. Maybe we could incorporate schema changes in Loren Cahlander’s (@lcahlander) [xqdoc repository](https://github.com/lcahlander/xqdoc)?

**Comment by apb2006** [comment]
From a quick look I cant see any material changes. Moving the comments to  `xs:documentation` is good.
(@lcahlander - are there other changes?)

The `xsd-report` shows the same result. 
```
"https://raw.githubusercontent.com/BaseXdb/basex/f84183c1ac3006d7e1fa85e22147186f03bce305/basex-api/src/main/webapp/dba/files/files.xqm"
=>inspect:xqdoc()
=>validate:xsd-report("https://raw.githubusercontent.com/lcahlander/xqdoc/master/src/main/resources/xqdoc-1.1.20190513.xsd")
```

**Comment by ChristianGruen** [comment]
I am closing this (maybe the next steps could be discussed in Loren’s repository).
