### ISSUE TITLE
better way to serve dba static file. and my patch

### ISSUE THREAD

**Issue by oguma** [BaseXdb/basex#1715]
I often use this setting for .basex .
```
# Local Options
SERIALIZER = method=html,version=5.0,html-version=5.0,media-type=text/html
```

Then, these urls do NOT work, properly.

http://localhost:8984/dba/static/basex.svg
http://localhost:8984/dba/static/style.css

So, I have to add this code in webapp/dba/common.xqm
```
--- common.xqm.orig	2019-08-23 13:10:31.000000000 +0900
+++ common.xqm	2019-08-23 13:18:01.000000000 +0900
@@ -26,6 +26,7 @@
  :)
 declare
   %rest:path("/dba/static/{$file=.+}")
+  %output:method("basex")
   %perm:allow("all")
 function dba:file(
   $file  as xs:string
```
And then, these urls work, properly.

http://localhost:8984/dba/static/basex.svg
http://localhost:8984/dba/static/style.css

I do this every time for new my BaseX app, but If BaseX original code has this one line, my tedious tiny edit would not be need anymore.

So, I hope add this one line in original code.

```
%output:method("basex")
```

Thanks.

**Comment by ChristianGruen** [comment]
Resolved, thanks.
