### ISSUE TITLE
Master Slave Replication

### ISSUE THREAD

**Issue by sarankup** [BaseXdb/basex#1718]
Hi,

This is not a bug ticket but checking for the feature. Does BaseX support Master-Slave replication set up something similar in other databases like MySQL and MongoDB?

**Comment by ChristianGruen** [comment]
Welcome to the BaseX issue tracker! We appreciate your feedback. Please mind the following guidelines:

* Before adding new feature requests and bug reports, please write to our
   basex-talk mailing list: http://basex.org/open-source/.
* You may as well find it helpful to browse through our documentation:
   http://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: http://www.mail-archive.com/basex-talk%40mailman.uni-konstanz.de/

Thanks for your support.
