### ISSUE TITLE
XQuery, Variable Refinements: Consistency

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#1731]
**Source:** https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/var/Var.java#L160

Check if it wouldn’t be more appropriate to call [ExprType.assign(Type, Occ, long)](https://github.com/BaseXdb/basex/blob/master/basex-core/src/main/java/org/basex/query/value/type/ExprType.java#L108).

**Comment by STPR** [comment]
Hello,

I have a problem with the RUNS command which i didn't have in the previous versions of BaseX.

Using BaseX  9.2.4, the command:
**SET RUNS 1; RUN "E:\SERVER\DB\db.xq"**

Bring me this error:
**Invalid 'RUNS' value '1; RUN E:\SERVER\DB\db.xq'; must be a number.**
