### ISSUE TITLE
RUNS command issue

### ISSUE THREAD

**Issue by STPR** [BaseXdb/basex#1732]
Hello,

I have a problem with the RUNS command which i didn't have in the previous versions of BaseX.

Using BaseX  9.2.4, the command:
**SET RUNS 5; RUN "E:\SERVER\DB\db.xq"**

Brings me this error:
**Invalid 'RUNS' value '5; RUN E:\SERVER\DB\db.xq'; must be a number.**

**Comment by ChristianGruen** [comment]
With more recent versions, you might need to separate your commands more clearly:
`basex -c"set runs 5" -c"run ..."`

Please refer to the mailing list for further question; thanks in advance.

**Comment by STPR** [comment]
I'm using this command in a bsx file and the syntax from here:
[http://docs.basex.org/wiki/Commands](url)

`SET RUNS 10; XQUERY 1 to 10`

I will use the mailing list.
Thank you.

**Comment by ChristianGruen** [comment]
Thanks for the hint, I’ve revised the example in the doc.
