### ISSUE TITLE
Service jobs do not restart after exiting (basex 9.2 and 9.3)

### ISSUE THREAD

**Issue by bookvik** [BaseXdb/basex#1740]
When I go into the console and run

> xquery jobs:eval('1+1', (), map { 'id': 'test', 'interval': 'P1D', 'service': true(), 'start': '01:00:00' })

I see that the service has been created and queued

> jobs list
ID    Type      State      User   Duration  Start                     End  Reads   Writes  Time                      
-------------------------------------------------------------------------------------------------------------------
job1  JobsList  running    admin  PT0.001S                                 (none)  (none)  2019-10-10T14:09:01.592Z  
test  QueryJob  scheduled  admin            2019-10-11T01:00:00.017Z       (none)  (none)  2019-10-10T14:08:55.258Z  

But after I left the console and entered again
nothing in the task list

if you call

```
> xquery jobs:services()
<job base-uri="" id="test" interval="P1D" start="01:00:00">1+1</job>
```

then its definition is visible

**Comment by ChristianGruen** [comment]
Services will only be registered if you run the BaseX server or HTTP server. See http://docs.basex.org/wiki/Jobs_Module#Services for more information.

For further questions on BaseX, please write to our mailing list first. Thanks in advance!
