### ISSUE TITLE
Dockert Instance returns: No function found that matches the request.

### ISSUE THREAD

**Issue by LaughingBubba** [BaseXdb/basex#1750]
I'm using the suggest docker run command
```bash
docker run -d \
--name basexhttp \
--publish 1984:1984 \
--publish 8984:8984 \
--volume "$HOME/Projects/basex-dev/data":/srv/basex/data \
basex/basexhttp:latest
```

There was no response to my posting on the mailing list https://mailman.uni-konstanz.de/pipermail/basex-talk/2019-November/014803.html

So I'm wondering if this is is the more appropriate place?

**Comment by ChristianGruen** [comment]
I hope your question has been answered?
