### ISSUE TITLE
unexpected request:parameter() result for POST-method

### ISSUE THREAD

**Issue by kontur32** [BaseXdb/basex#1756]
- **m.xqm**

```
module namespace m = 'm';
import module namespace Request = 'http://exquery.org/ns/request';
declare
  %rest:path( '/get-param' )
  %rest:method( 'POST' )
function m:func() {
  for $i in Request:parameter-names()
  return
   string-join( $i || ' : ' ||  Request:parameter( $i ),  '&#xd;' )
};
```

- **curl** `-X POST -F 'param1=expr1' -F 'param2=expr2' http://localhost:8984/get-param?param3=expr3`

- BaseX **9.2.4** **unexpected**  returns:
```
param3 : expr3
param1 :
param2 :
```

- BaseX **9.0.1** expected  returns:
```
param3 : expr3
param1 : expr1
param2 : expr2
```

**Comment by ChristianGruen** [comment]
Confirmed; the responsible commit: 7197e829ec1cd367312dfb57ee8a7bbb833d2e8c.

**Comment by ChristianGruen** [comment]
#### Analysis

* If `request:parameter-names` and `request:names` is called, the request body is now parsed more than once (and in the second run, the payload will already be exhausted).
* The change was introduced by the API rewriting: All XQuery functions are now placed in separate functions (one of the advantages of the new architecture is that external modules, such as the Request Module, need not be imported in the prolog anymore).
* With the introduction of WebSockets, the functions of the Request Module rely on the `HttpServletRequest` standard Java class, which exists for both RESTXQ and WebSocket requests. Before that, the BaseX `HTTPConnection` class was referenced, which can be adapted more easily to cache request parameters.

#### Solutions

1. Additionally bind `HTTPConnection` to query context; refer to it only when query parameters are parsed.
2. Use `ThreadLocal` instances to cache Query parameters (will need to be invalidated after query execution).
3. Restrict `request:parameter-names`/`request:names` support to query parameters (would facilitate streaming of request payloads, but would make existing code incompatible).

I tend to Solution 1.

**Comment by ChristianGruen** [comment]
The bug has been fixed (a new [snapshot](http://files.basex.org/releases/latest/) is available).
Thanks for reporting.
