### ISSUE TITLE
Add '.idml' to ZIPSUFFIXES

### ISSUE THREAD

**Issue by gimsieke** [BaseXdb/basex#1758]
I need (quite urgently) to index a lot of IDML files. While I can in principle rename them to `.zip`, I’d prefer if you added `.idml` to the ZIPSUFFIXES array in org/basex/io/IO.java

**Comment by ChristianGruen** [comment]
I was happy to merge your pull request; [a new snapshot](http://files.basex.org/releases/latest/) is online.

**Comment by gimsieke** [comment]
Thank you, Christian!
