### ISSUE TITLE
Maven repository lacks checksums for net.xqj:basex-xqj:9.0

### ISSUE THREAD

**Issue by sewe** [BaseXdb/basex#1794]
The Maven repository at http://files.basex.org/maven/ lacks `.sha1` checksum files for some artifacts. In particular, running Maven with strict checksum validation (`mvn --strict-checksums`) fails because of that:

```
Downloading from basex: http://files.basex.org/maven/net/xqj/basex-xqj/9.0/basex-xqj-9.0.pom
[WARNING] Could not validate integrity of download from http://files.basex.org/maven/net/xqj/basex-xqj/9.0/basex-xqj-9.0.pom: Checksum validation failed, no checksums available
[WARNING] Checksum validation failed, no checksums available from basex for http://files.basex.org/maven/net/xqj/basex-xqj/9.0/basex-xqj-9.0.pom
```

The problem seems to be that there was a `.sha` rather than a `.sha1` file deployed: http://files.basex.org/maven/net/xqj/basex-xqj/9.0/

Other artifacts in the repository look as expected, though. (For example, http://files.basex.org/maven/org/basex/basex/9.3.1/)

**Comment by ChristianGruen** [comment]
Fixed, I renamed the suffixes to `sha1` (and I noticed this only affected the latest version of XQJ).
