### ISSUE TITLE
Validating big files(about 256 Mbytes)

### ISSUE THREAD

**Issue by kzdanila** [BaseXdb/basex#1815]
Hello,
Could you help me?
I have a big file in database and i want to validate it by XSD-schema.
It doesnt'work, it crashed with error "java heap space".
Thanks for help.

**Comment by ChristianGruen** [comment]
We appreciate your feedback on BaseX. Please mind the following guidelines:

* Our issue tracker is used to discuss confirmed bugs and feature requests.
* For general questions, new feature requests and bug reports, please write to our
   basex-talk mailing list: http://basex.org/open-source/.
* You may as well find it helpful to browse through our documentation:
   http://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: http://www.mail-archive.com/basex-talk%40mailman.uni-konstanz.de/

Thanks for your support.
