### ISSUE TITLE
NPE in REPO DELETE

### ISSUE THREAD

**Issue by brandes-pq** [BaseXdb/basex#1826]
When trying to delete a XAR package that contains more than one XQuery module with the same namespace, it triggers an NPE in [EXPathRepo.java:101](https://github.com/BaseXdb/basex/blob/6d36334e0016bdef2c22821d8c012b52ca575bdb/basex-core/src/main/java/org/basex/query/util/pkg/EXPathRepo.java#L101).

To reproduce, it suffices to build a trivial EXPath package `foo.xar` containing the three files

```xml
<!-- expath-pkg.xml -->
<package xmlns="http://expath.org/ns/pkg" spec="1.0" name="urn:example-pkg" abbrev="expkg" version="1.0">
  <title>Example package</title>
  <xquery>
    <namespace>urn:foo</namespace>
    <file>foo.xqm</file>
  </xquery>
  <xquery>
    <namespace>urn:foo</namespace>
    <file>foo2.xqm</file>
  </xquery>
</package>
```

```xquery
(: content/foo.xqm :)
module namespace foo="urn:foo";
```

```xquery
(: content/foo2.xqm :)
module namespace foo="urn:foo";
```

Now the error can be triggered on the command line with

```sh
basex -c 'repo install foo.xar'
basex -c 'repo delete urn:example-pkg'
```

The XAR may also be found in this archive: [test-files.zip](https://github.com/BaseXdb/basex/files/4295131/test-files.zip)

I tried a trivial fix by replacing `pkgs.size() > 1` with `pkg != null && pkgs.size() > 1`, and that seems to fix it. I am not sure whether any further steps must be taken.

**Comment by ChristianGruen** [comment]
Thanks for the reproducible test case and the proposed fix; I’ll have a look at that soon. Cheers from… the Northern Region of Karlsruhe.

**Comment by ChristianGruen** [comment]
My fix is very close to your proposal; a new [stable snapshot](http://files.basex.org/releases/latest/) is online.
