### ISSUE TITLE
VirusTotal detects basex.exe as malicious

### ISSUE THREAD

**Issue by imranazad** [BaseXdb/basex#1828]
Hi,

VirusTotal detects basex.exe as malicious:

https://www.virustotal.com/gui/file/a92809b5e0f324dc0f0857e13b7c0a92e6b40acd73cc4063d46734db1617e353/detection

Which makes me reluctant to use it. Can anyone explain why it's being reported as malicious?

Thanks

**Comment by ChristianGruen** [comment]
We can't, sorry. Maybe you need to contact the developers of VirusTotal?

**Comment by imranazad** [comment]
No worries @ChristianGruen  I will see if I can get in-touch with them. Just to confirm using https://virusdesk.kaspersky.com/ it gets an all clear!
