### ISSUE TITLE
When trying to startup the app getting an error

### ISSUE THREAD

**Issue by JustAzex** [BaseXdb/basex#1830]
The error that I get is "Windows can't find javaw file.
How do I fix this error ?
Sorry the picture is on Spanish.
![Captura](https://user-images.githubusercontent.com/62765788/77784883-960d2480-705b-11ea-9cd7-66be4c366d73.PNG)

**Comment by ChristianGruen** [comment]
You’ll probably need to install Java (JRE, JDK) for running BaseX. – For more questions, please write to our [basex-talk mailing list](http://basex.org/about/open-source/); thanks.
