### ISSUE TITLE
BaseX GUI: Out of Main Memory while creating new DB on external drive

### ISSUE THREAD

**Issue by ms452206** [BaseXdb/basex#1837]
BaseX v9.3.2: I got an _Out of Main Memory_ Error while creating a new DB on an external drive by importing several xml files. I've started BasexGUI with 10GB with this command:

C:\Users>java -Xmx10g -cp C:\Tools\BaseX932\basex\BaseX.jar org.basex.BaseXGUI

Used Memory alert shows _Reserved Memory_ far from the available heap size ~10GB:

![oom](https://user-images.githubusercontent.com/17757721/79455061-952d3a00-7fec-11ea-9adf-242aae2a4a7b.png)

I never saw this error before while creating similar databases on internal SSD but it appears now using an external SSD.

**Comment by ChristianGruen** [comment]
We appreciate your feedback on BaseX. Please mind the following guidelines:

* Our issue tracker is used to discuss confirmed bugs and feature requests.
* For general questions, new feature requests and bug reports, please write to our
   basex-talk mailing list: http://basex.org/open-source/.
* You may as well find it helpful to browse through our documentation:
   http://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: http://www.mail-archive.com/basex-talk%40mailman.uni-konstanz.de/

Thanks for your support.
