### ISSUE TITLE
Inconsistent classpath handling in starter scripts

### ISSUE THREAD

**Issue by opax** [BaseXdb/basex#1847]
Hello,

I found a minor inconsistency between the starter scripts for UNIX/macos and the Windows batch files. For the UNIX scripts, it is possible to have additional entries in the Java classpath by setting the environment variable CLASSPATH before starting BaseX. The Windows batch files do not allow this.

I would find it very useful to have the same behavior in the Windows batch files. It may be necessary to have project-specific CLASSPATH entries; that way, a central BaseX installation may be shared among different projects, even if the projects have incompatible additional dependencies.

**Comment by ChristianGruen** [comment]
Quite indeed. I have revised the starter scripts. Feel free to close the issue if you believe it’s resolved ([new snapshots](http://files.basex.org/releases/latest/) are online).
