### ISSUE TITLE
TLS-Certificate for files.basex.org

### ISSUE THREAD

**Issue by opax** [BaseXdb/basex#1859]
Hello,

since the artifacts deployed to maven central tend to be outdated (I found ticket #1099 discussed problems with automatic deployment), it would be nice if the repository at `files.basex.org/maven` could be reachable via HTTPS. At present, HTTPS is enabled, but the server presents a self-signed certificate.

HTTP access to repositories in an automated build system is problematic, as no integrity guarantees can be given whatsoever.

**Comment by ChristianGruen** [comment]
Done.
