### ISSUE TITLE
Option to output text of XQUERY in script

### ISSUE THREAD

**Issue by ericjs** [BaseXdb/basex#1871]
I'm finding BaseX's command line scripts really handy to do some analysis of a set of content. Load it up into a database, run some queries to explore the structure of the content, what tags or combinations of structures are actually in use in the set of content. It's really handy to be able to put a bunch of such queries into a script for re-running later, after getting more content or an update.

What would make this even more handy would be if there was an option to output the text of each xquery instead of just the result. Right now if I run such a script, with 3 xquery commands in it, call it "script.bxs", run like so (with -v for "progress info"):

basex -v -i somedb -c script.bxs

I get output like the following:

Query "script.bxs" executed in 89.96 ms.
3539
Query "script.bxs" executed in 43.93 ms.
75
Query "script.bxs" executed in 2.04 ms.
52

What would really be ideal would be something like

Query "count(//ELEMENT1)" executed in 89.96 ms.
3539
Query "count(//ELEMENT2)" executed in 43.93 ms.
75
Query "count(/ELEMENT1//ELEMENT2)" executed in 2.04 ms.
52

This could be an optional switch or even just an enhancement to the the current outputting when using -v of the name of the script for every line, which doesn't seem very useful.

(BTW I am aware -V will get the query in the output, but not without a lot of additional stuff.)

**Comment by ChristianGruen** [comment]
Dear Eric,

We appreciate your feedback on BaseX. Please mind the following guidelines:

* Our issue tracker is used to discuss confirmed bugs and feature requests.
* For general questions, new feature requests and bug reports, please write to our
   basex-talk mailing list: http://basex.org/open-source/.
* You may as well find it helpful to browse through our documentation:
   http://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: http://www.mail-archive.com/basex-talk%40mailman.uni-konstanz.de/

Thanks for your support.
