### ISSUE TITLE
CreateDB throws java.lang.NegativeArraySizeException if the source is a character stream and its length > 1Gb (int overflow)

### ISSUE THREAD

**Issue by vladich** [BaseXdb/basex#1900]
The bug is in Token.utf8 

 private static byte[] utf8(final String string) {
    final char[] arr = string.toCharArray();
    final int al = arr.length;
    **final TokenBuilder tb = new TokenBuilder(al << 1);** // al << 1 becomes negative if the stream is > 1Gb due to int overflow
    for(int c = 0; c < al; ++c) {
      final char ch = arr[c];
      tb.add(Character.isHighSurrogate(ch) && c < al - 1
          && Character.isLowSurrogate(arr[c + 1])
           ? Character.toCodePoint(ch, arr[++c]) : ch);
    }
    return tb.finish();
  }

**Comment by vladich** [comment]
Another problem - it's super memory inefficient for character streams. Reading character by character from a stream? Copying data unnecessarily? Is it possible to fix? It works much more efficiently with byte streams.

**Comment by ChristianGruen** [comment]
Thanks vladich,

We appreciate your feedback on BaseX. Please mind the following guidelines:

* Our issue tracker is used to discuss confirmed bugs and feature requests.
* For general questions, new feature requests and bug reports, please write to our
   basex-talk mailing list: https://basex.org/open-source/.
* You may as well find it helpful to browse through our documentation:
   https://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/

Thanks for your support.

**Comment by vladich** [comment]
@ChristianGruen Is the bug closed as unconfirmed?
I can open a new one with more detailed information about the problem.
It happens when CreateDB command is called with setInput set to a Reader (InputStreamReader in my case).
Then in ACreate.sourceToIO it creates IOContent with all input passed as a single String.
In my case that String's size is > 1Gb. Then IOContent constructor generates a token which calls Token.utf8 method, which has a code with int overflow. Do you want me to create a more detailed issue? This problem is easy enough to fix, I may create a pull request myself. Another problem that I mentioned is that the input method (using Reader) is much slower than the one that uses InputStream, that one may be harder to fix.
Thank you.

**Comment by ChristianGruen** [comment]
Thanks for your feedback. I understand that our introductory text is not that self-explanatory as we hoped. I have slightly rewritten the first lines:

* For bug reports, feature requests and questions, please first write to our
   basex-talk mailing list: https://basex.org/open-source/.
* This tracker is used in a next step to discuss confirmed issues.

It’s the mailing list that’s the first address to discuss further steps. Hope this helps.

**Comment by vladich** [comment]
Ok, thank you

**Comment by ChristianGruen** [comment]
I have revised the code for resizing the temporary UTF8 arrays.

Feel free to provide us with some exemplary Java code on our mailing list, which allows us to reproduce the issues you observed with the InputStreamReader instance.
