### ISSUE TITLE
xslt:transform function not working with XML Catalog

### ISSUE THREAD

**Issue by vincentml** [BaseXdb/basex#1903]
The xslt:transform function is not using the XML Catalog to resolve the DTD location when parsing XML.

See the mailing list discussion thread related to this issue: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg12859.html

The REAME.md file in the attached SSCE contains examples to illustrate the problem.

[xslt-transform-with-dtd-catalog-ssce.zip](https://github.com/BaseXdb/basex/files/4904655/xslt-transform-with-dtd-catalog-ssce.zip)

**Comment by liamquin** [comment]
If i make an intermediate XSLT file that calls
`transform(
	map {
	  "stylesheet-location" : "transform.xsl",
	  "source-node" : doc("input1.xml")
	}

      )?output'`
and call that with xslt:transform('irrelevant.xml', 'intermediate.xsl') then it works. Well, i didn't see the entity turn into a useful filename(i get the empty string) but i think that's a different problem.

**Comment by vincentml** [comment]
Hi @liamquin 

The entityref expansion is a separate problem from the problem of the catalog not being used when parsing the XML, but these two problems are hand in hand. 

The doc() function in BaseX does use the catalog to locate the DTD when parsing the XML. Unfortunately, parsing the XML and with doc() and then calling xslt:transform() produces an empty filename attribute.

`(# db:catfile schemas/catalog.xml #) (# db:intparse false #) (# db:dtd true #) (# db:chop false #) { doc('input1.xml') => xslt:transform('transform.xsl') }
`
To get the filename attribute to populate correctly based on the entityref, the XML has to be passed as a string to xslt:transform(), the string being either a file path or serialized XML. Because the XML is pointing to its DTD using a non-working URI I wanted to use an XML Catalog to resolve the location of the DTD but in xslt:transform() the catalog is not working to locate the DTD. It looks as though the EntityResolver might not be getting set to the CatalogWrapper.

The workaround I'm now using is to replace the non-working URI with a relative file path to the DTD (relative to .basexhome) prior to xslt:transform(). This results in the XML being parsed with the local copy of the DTD and the filename attribute being populated based on the entityref.

(# db:catfile schemas/catalog.xml #) (# db:intparse false #) (# db:dtd true #) (# db:chop false #) { unparsed-text('input1.xml') => replace('non-working-uri', 'relative/path/to/dtd.dtd') => xslt:transform('transform.xsl') }

**Comment by ChristianGruen** [comment]
The issue should be resolved with BaseX 10 (check out a [first snapshot](https://files.basex.org/releases/latest-10/) or the [BaseX 10 branch](https://github.com/BaseXdb/basex/tree/10)).

As the JDK 11 catalog resolver raises exceptions if an error is found in the catalog, BaseX may need to be started with custom catalog settings:

```
-Djavax.xml.catalog.resolve=continue
```

For further details, see https://docs.oracle.com/en/java/javase/11/core/xml-catalog-api1.html

**Comment by vincentml** [comment]
Hi @ChristianGruen 

I've just had an opportunity to test the latest BaseX 10. Unfortunately it is not working.

I have an XSLT which uses fn:collection() to find and read information from XML files in a directory, and an XML Catalog is needed to resolve the DTD DOCTYPE references when parsing the XML. This XSLT works fine when using Saxon from the command line and providing an XML Catalog via the -catalog parameter. However, running the same XSLT on the same files in BaseX using xslt:transform-text() with db:catfile specified at the start of the query does not work. The error message "The markup declarations contained or pointed to by the document type declaration must be well-formed" indicates that the XML Catalog is not being used to resolve the location of the DTD.

**Comment by ChristianGruen** [comment]
@vincentml, thanks for testing the BaseX 10 branch. Would you mind creating a little test case for us? We can then check if the JDK standard catalog resolver allows us to find a solution.

The existing catalog test cases can be found here: https://github.com/BaseXdb/basex/blob/10/basex-core/src/test/java/org/basex/core/CatalogTest.java

**Comment by vincentml** [comment]
@ChristianGruen Thanks for the quick response! I've created a few small examples based on the test cases that you referenced and the test resources in https://github.com/BaseXdb/basex/tree/10/basex-core/src/test/resources/catalog In each example it appears that the resolvers configured by db:catalog are not being provided to Saxon.

## Example: XSLT uses `fn:doc()` to parse XML that references a DTD

This example uses `fn:doc()`, although a similar problem was also observed using `fn:catalog()`.

File: doc.xml

```xml
<!DOCTYPE xml SYSTEM 'http://dtd.dtd'>
<doc>&x;</doc>
```

File: doc2.xml

```xml
<!DOCTYPE doc SYSTEM 'http://dtd.dtd'>
<doc>2&x;</doc>
```

File: fn-doc.xsl

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    version="3.0">
    
    <xsl:template match="/*">
        <xsl:copy>
            <xsl:apply-templates/>
            <xsl:sequence select="doc('doc2.xml')"/>
        </xsl:copy>
    </xsl:template>
    
</xsl:stylesheet>
```

File: dtd.dtd

```xml
<!ENTITY x 'X'>
<!ELEMENT doc (#PCDATA)>
```

File: catalog.xml

```xml
<catalog xmlns='urn:oasis:names:tc:entity:xmlns:xml:catalog'>
  <system systemId='http://dtd.dtd' uri='dtd.dtd' />
</catalog>
```


Saxon

```cmd
java -cp %SAXON_CP% net.sf.saxon.Transform -catalog:basex-core\src\test\resources\catalog\catalog.xml -s:basex-core\src\test\resources\catalog\doc.xml -xsl:basex-core\src\test\resources\catalog\fn-doc.xsl
```

Produces the correct result:

```xml
<?xml version="1.0" encoding="UTF-8"?><doc>X<doc>2X</doc></doc>
```

BaseX

```xquery
declare option db:dtd "true";
declare option db:intparse "false";
declare option db:catfile "catalog.xml";

let $doc := file:resolve-path("doc.xml")
let $xsl := file:resolve-path("fn-doc.xsl")
return xslt:transform-text($doc, $xsl)
```

Produces an error message:

```
[xslt:error] Recoverable error 
  I/O error reported by XML parser processing
  C:/Users/lizziv/Projects/OpenSource/BaseXdb/basex/basex-core/src/test/resources/catalog/doc.xml: dtd.dtd
```


## Example: XSLT uses `fn:unparsed-entity-uri()`

File: fn-unparsed-entity-uri.xml

```xml
<!DOCTYPE graphic SYSTEM "http://dtd.dtd" [
<!ENTITY photo SYSTEM "photo.gif" NDATA GIF>
]>
<graphic entityref="photo"/>
```

File: fn-unparsed-entity-uri.xsl

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    version="3.0">
    
    <xsl:template match="graphic">
        <graphic src="{unparsed-entity-uri(@entityref)}"/>
    </xsl:template>
    
</xsl:stylesheet>
```

File: dtd.dtd

```xml
<!ENTITY x 'X'>
<!ELEMENT doc (#PCDATA)>
<!ELEMENT graphic EMPTY>
<!ATTLIST graphic entityref ENTITY #IMPLIED src CDATA #IMPLIED>
```

File: catalog.xml

```xml
<catalog xmlns='urn:oasis:names:tc:entity:xmlns:xml:catalog'>
  <system systemId='http://dtd.dtd' uri='dtd.dtd' />
</catalog>
```


Saxon

```cmd
java -cp %SAXON_CP% net.sf.saxon.Transform -catalog:basex-core\src\test\resources\catalog\catalog.xml -s:basex-core\src\test\resources\catalog\fn-unparsed-entity-uri.xml -xsl:basex-core\src\test\resources\catalog\fn-unparsed-entity-uri.xsl
```

Produces the correct result:

```xml
<?xml version="1.0" encoding="UTF-8"?><graphic src="file:/C:/Users/lizziv/Projects/OpenSource/BaseXdb/basex/basex-core/src/test/resources/catalog/photo.gif"/>
```

BaseX

```xquery
declare option db:dtd "true";
declare option db:intparse "false";
declare option db:catfile "catalog.xml";

let $doc := file:resolve-path("fn-unparsed-entity-uri.xml")
let $xsl := file:resolve-path("fn-unparsed-entity-uri.xsl")
return xslt:transform-text($doc, $xsl)
```

Produces an error message:

```
[xslt:error] Recoverable error 
  I/O error reported by XML parser processing
  C:/Users/lizziv/Projects/OpenSource/BaseXdb/basex/basex-core/src/test/resources/catalog/fn-unparsed-entity-uri.xml: dtd.dtd
```

**Comment by ChristianGruen** [comment]
Thanks, Vincent, for the comprehensive test cases.

I tried to get your first test case working with a pure Java solution:

```java
import java.io.*;
import java.net.*;

import javax.xml.catalog.*;
import javax.xml.transform.*;
import javax.xml.transform.stream.*;

public class Xslt {
  public static void main(String... args) throws Exception {
    String dir = "c:/users/user/Desktop/";

    String catalogURI = "file:///" + dir + "catalog.xml";
    CatalogFeatures cf = CatalogFeatures.defaults();
    Catalog catalog = CatalogManager.catalog(cf, URI.create(catalogURI));
    CatalogResolver cr = CatalogManager.catalogResolver(catalog);

    TransformerFactory tf = TransformerFactory.newInstance();
    tf.setURIResolver(cr);
    // Saxon reports: "Unrecognized configuration feature: javax.xml.catalog.files"
    tf.setAttribute(CatalogFeatures.Feature.FILES.getPropertyName(), catalogURI);

    Templates templates = tf.newTemplates(new StreamSource(dir + "fn-doc.xsl"));
    Transformer tr = templates.newTransformer();
    tr.setURIResolver(cr);

    ByteArrayOutputStream os = new ByteArrayOutputStream();
    tr.transform(new StreamSource(dir + "doc.xml"), new StreamResult(os));
    System.out.println(os);
  }
}
```

The `setURIResolver` calls are required to enable catalog resolution during the XSLT process. Actually, it’s called twice in the code: One call will trigger resolutions in Saxon, the other one will be detected by the default transformer.

With `setAttribute`, catalog resolution is enabled for input stream sources input files. However, when invoked, Saxon reports `Unrecognized configuration feature: javax.xml.catalog.files` (most probably because the feature was only introduced with Java 9).

In BaseX, this method is [currently not invoked](https://github.com/BaseXdb/basex/blob/da1e55d0214e44c1532f121c282021db50a9aa51/basex-core/src/main/java/org/basex/query/func/xslt/XsltTransform.java#L73-L76), but catalog resolution for input files works if `fn:doc` is used:

```xquery
declare option db:dtd "true";
declare option db:intparse "false";
declare option db:catfile "catalog.xml";

let $doc := doc("doc.xml")
let $xsl := doc("fn-doc.xsl")
return xslt:transform-text($doc, $xsl)
```

I more and more doubt we’ll be able to get a fully working solution with Saxon unless it provides support (or at least tolerates settings) for JDK 11 and its built-in transformer factory and catalog resolver.

Ideas are welcome. Maybe there are other ways to propagate the catalog options to Saxon?

This article gives a good introduction into the workings of the XML Catalog API: https://docs.oracle.com/en/java/javase/11/core/xml-catalog-api1.html#GUID-963956F7-17C1-483D-AF0F-5106298A8C99.

**Comment by vincentml** [comment]
Hi @ChristianGruen 

Thank you for looking into this. Based on Saxon's documentation on [XML Catalogs](https://www.saxonica.com/html/documentation10/sourcedocs/xml-catalogs.html) it looks like the missing piece is to set an entity resolver. I tried modifying your pure Java test but have not gotten it to work. 

```java
import java.io.*;
import java.net.*;

import javax.xml.catalog.*;
import javax.xml.transform.*;
import javax.xml.transform.sax.SAXSource;
import javax.xml.transform.stream.*;
import org.xml.sax.XMLReader;
import javax.xml.parsers.SAXParserFactory;
import javax.xml.parsers.SAXParser;

public class Xslt {
  public static void main(String... args) throws Exception {
    String dir = "c:/users/user/Desktop/";

    String catalogURI = "file:///" + dir + "catalog.xml";
    CatalogFeatures cf = CatalogFeatures.builder().with(CatalogFeatures.Feature.RESOLVE, "continue").build();
    Catalog catalog = CatalogManager.catalog(cf, URI.create(catalogURI));
    CatalogResolver cr = CatalogManager.catalogResolver(catalog);

    TransformerFactory tf = TransformerFactory.newInstance();
    tf.setURIResolver(cr);
    // Saxon reports: "Unrecognized configuration feature: javax.xml.catalog.files"
    // tf.setAttribute(CatalogFeatures.Feature.FILES.getPropertyName(), catalogURI);

    Templates templates = tf.newTemplates(new StreamSource(dir + "fn-doc.xsl"));
    Transformer tr = templates.newTransformer();
    tr.setURIResolver(cr);

    SAXParserFactory sxf = SAXParserFactory.newInstance(); 
    sxf.setNamespaceAware(true);
    sxf.setXIncludeAware(true);
    SAXParser parser = sxf.newSAXParser();
    XMLReader reader = parser.getXMLReader();
    reader.setEntityResolver(cr);
    SAXSource ss = new SAXSource();
    ss.setInputSource(new org.xml.sax.InputSource(dir + "doc.xml"));
    ss.setXMLReader(reader);
    ByteArrayOutputStream os = new ByteArrayOutputStream();
    tr.transform(ss, new StreamResult(os));
    System.out.println(os);
  }
}
```

The error message that this shows is below, and indicates that the XML Catalog is not being used by Saxon when the stylesheet opens a document with `doc('doc2.xml')"`

```
Error in xsl:sequence/@select on line 8 column 53 of fn-doc.xsl:
  FODC0002: I/O error reported by XML parser processing
  file:/C:/Users/lizziv/Projects/OpenSource/BaseXdb/basex/basex-core/src/test/resources/catalog/doc2.xml: dtd.dtd
  In template rule with match="document-node()/element()" on line 5 of fn-doc.xsl
     invoked by built-in template rule (text-only)
Exception in thread "main" ; SystemID: file:///C:/Users/lizziv/Projects/OpenSource/BaseXdb/basex/basex-core/src/test/resources/catalog/fn-doc.xsl; Line#: 8; Column#: 53
net.sf.saxon.trans.XPathException: I/O error reported by XML parser processing file:/C:/Users/lizziv/Projects/OpenSource/BaseXdb/basex/basex-core/src/test/resources/catalog/doc2.xml: dtd.dtd
```

I might try configuring the XML Catalog for Saxon via system properties which would essentially duplicate the CATFILE configuration for BaseX.

**Comment by ChristianGruen** [comment]
> I might try configuring the XML Catalog for Saxon via system properties which would essentially duplicate the CATFILE configuration for BaseX.

Thanks; feel free to tell us if this works out. Maybe this could also be discussed on saxonica.plan.io (with our without reference to BaseX).

**Comment by ChristianGruen** [comment]
Closed, as I assume this would need to be resolved by Saxon (I’ll be happy to be proven wrong.)

**Comment by ChristianGruen** [comment]
Thanks, Vincent. Maybe I can include that in our documentation with the release of BaseX 10.

**Comment by ChristianGruen** [comment]
A side note: As much more BaseX features will support catalog resolution, we decided to rename the `CATFILE` option to `CATALOG`.

Our documentation still needs to be fully updated.
