### ISSUE TITLE
<!DOCTYPE some name SYSTEM .. and <?xml version="1.0"?> data loss are happening while importing the xml document using db:replace(...) API. 

### ISSUE THREAD

**Issue by talk2srikumar** [BaseXdb/basex#1904]
<!DOCTYPE some name SYSTEM .. and <?xml version="1.0"?> data loss are happening while importing the xml document using db:replace(...) API. 

 <?xml version="1.0"?>

<!DOCTYPE testSuiteConfig SYSTEM "../../../configs/TestConfig_2_1.dtd">
etc.
We need help to resolve this issue. 
we are using Java executeQuery api of XQExpression. class to run "db:replace(...)" query. 
Please tell us, how we can resolve this issue or any other API we can use solve this problem. 

referred few document: but do not know how it will help to solve our problem. 
https://basex.readthedocs.io/en/latest/Serialization/
Thanks,
Srikumar

**Comment by ChristianGruen** [comment]
We appreciate your feedback on BaseX. Please mind the following guidelines:

* For bug reports, feature requests and questions, please first write to our
   basex-talk mailing list: https://basex.org/open-source/.
* This tracker is used in a next step to discuss confirmed issues.
* You may as well find it helpful to browse through our documentation:
   https://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/

Thanks for your support.
