### ISSUE TITLE
Basex query execution is too slow in linux 

### ISSUE THREAD

**Issue by nikhilsethi** [BaseXdb/basex#1916]
While executing any query in basex, 
-> windows machine takes around 4 to 15 millisec 
-> On linux machine same query takes around 120 to 150 millisec

During some application execution we are selecting/importing the xml nodes in different docs in basex and there are around 13000 xml nodes which needs to be imported in db.
Windows worst case(15 ms) query execution time => 13000 x 15ms => 65000ms => 65 sec = around 1 min
Linux average case(130 ms) query execution time => 13000 x 130ms => 1690000ms => 1690 sec = around 28 min to execute same operation
I am using  BaseX941.zip ZIP Package 
eg queries :  
for $alias in collection(mydbname)//* where (($alias/@id="4249f0807da81000a734525400c54430018") and ($alias/@deleted="false") and ($alias/object-type/@uid="com.MyObjectName")) return $alias

or

insert node <myxmlNode>…….</myxmlNode> into (for $alias in doc('MyDoc') return $alias)

We appreciate your feedback on BaseX. Please mind the following guidelines:

* For bug reports, feature requests and questions, please first write to our
   basex-talk mailing list: https://basex.org/open-source/.
* This tracker is used in a next step to discuss confirmed issues.
* You may as well find it helpful to browse through our documentation:
   https://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/

Thanks for your support.

**Comment by ChristianGruen** [comment]
We appreciate your feedback on BaseX. Please mind the following guidelines:

* For bug reports, feature requests and questions, please first write to our
   basex-talk mailing list: https://basex.org/open-source/.
* This tracker is used in a next step to discuss confirmed issues.
* You may as well find it helpful to browse through our documentation:
   https://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/

Thanks for your support.
