### ISSUE TITLE
C# API client

### ISSUE THREAD

**Issue by rohmin9122** [BaseXdb/basex#1929]
How do I change dbpath using C# API?
An error, '**Global option 'DBPATH' cannot be set**.', occurred when sending the command, 'SET DBPATH C:\Users\minyoung\Desktop\basex_test'.
Please let me know.
Thank in advance for helping me.

**Comment by ChristianGruen** [comment]
As DBPATH is a global option, it cannot be set at runtime via databases commands. See https://docs.basex.org/wiki/Options for more information

-------------

We appreciate your feedback on BaseX. Please mind the following guidelines:

* For bug reports, feature requests and questions, please first write to our
   basex-talk mailing list: https://basex.org/open-source/.
* This tracker is used in a next step to discuss confirmed issues.
* You may as well find it helpful to browse through our documentation:
   https://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/

Thanks for your support.
