### ISSUE TITLE
fn:replace incorrectly raising FORX0003

### ISSUE THREAD

**Issue by adamretter** [BaseXdb/basex#1940]
The following query in BaseX is raising the error: `FORX0003`.

```
fn:replace("hello", "hel(?:lo)", "$1")
```

However, as I interpret the specification, it should instead be returning an empty string. The spec says:

> A dynamic error is raised [err:FORX0003] if the pattern matches a zero-length string, that is, if the expression fn:matches("", $pattern, $flags) returns true. It is not an error, however, if a captured substring is zero-length.

However `fn:matches("", "hel(?:lo)")` is returning `false()` in BaseX.

I compared this to Saxon (which has it correct), and eXist-db which did not.

**Comment by ChristianGruen** [comment]
Thanks, Adam, for sharing your obsveration! We’ll have a look at that.

**Comment by ChristianGruen** [comment]
Another example: The query `replace('abc', 'b', '$1')` raises `FORX0003`, too. It should return `ac` instead.

**Comment by adamretter** [comment]
@ChristianGruen No problem. I thought you might like to know, as normally BaseX is very correct with regards to the spec ;-)

**Comment by ChristianGruen** [comment]
Thanks again. The bug has been fixed; a [new snapshot](https://files.basex.org/releases/latest/) is available.

**Comment by adamretter** [comment]
Thanks @ChristianGruen that was super-fast!
