### ISSUE TITLE
Possible to get result count from query?

### ISSUE THREAD

**Issue by binarycow** [BaseXdb/basex#1947]
Is it possible to execute a query, and get the result count?

I know the BaseX GUI displays the result as well as the number of results; Is there a way for me to get that information prior to parsing the output?

**Comment by ChristianGruen** [comment]
We appreciate your feedback on BaseX. Please mind the following guidelines:

* For bug reports, feature requests and questions, please first write to our
   basex-talk mailing list: https://basex.org/open-source/.
* This tracker is used in a next step to discuss confirmed issues.
* You may as well find it helpful to browse through our documentation:
   https://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/

Thanks for your support.
