### ISSUE TITLE
Versioning in BaseX

### ISSUE THREAD

**Issue by Flurb** [BaseXdb/basex#1952]
Hi all,

I was wondering how versioning works in BaseX.
So I have a XML file, I store another version of that same XML file and within BaseX there is some kind of versioning so I can retrieve both versions of the XML file.

I look into your mail archive, and I found the following mail:
https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg07369.html

Here it states that with using database metadata (Database Module, https://docs.basex.org/wiki/Database_Module), you can achieve versioning. But I don't see anything about it in the documentation. So I was wondering if it is a thing in BaseX (versioning), and how it's accomplished 👍 

Thanks!

Kind regards,
Rob

**Comment by ChristianGruen** [comment]
Thanks for your question, we appreciate your feedback. Please mind the following guidelines:

* For bug reports, feature requests and questions, please first write to our
   basex-talk mailing list: https://basex.org/open-source/.
* This tracker is used in a next step to discuss confirmed issues.
* You may as well find it helpful to browse through our documentation:
   https://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/

Thanks for your support.

**Comment by Flurb** [comment]
Hi,

I did send an email to the mailing list about this, but no one answers :(
How can I still get my answer? :)

Kind regards,
Rob
