### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by camtechnica** [BaseXdb/basex#1958]
I have just tried to download the Windows version of BaseX. Norton AV deleted the file noting that it apparently contained a virus WS,Reputation.1. Screenshot of notification attached. This occurred with both the .exe and .zip downloads.

![VirusDetected](https://user-images.githubusercontent.com/74353145/98926465-42a6f400-24cf-11eb-8f84-33e1fa4530ad.png)

**Comment by ChristianGruen** [comment]
Thanks for the observation. Norton has obviously detected a false positive:

https://community.norton.com/en/forums/clarification-wsreputation1-detection
https://www.nsoftware.com/kb/xml/11011701.rst

We have reported this back to Norton. If you want to contribute, we invite you to also submit this information via the following web site (→ Incorrectly Detected by Symantec):

https://symsubmit.symantec.com/

**Comment by ChristianGruen** [comment]
Feedback from Symantec (Tracking #43897637):

![Screenshot_20201122-170144_Gmail](https://user-images.githubusercontent.com/196589/99908752-8f1adc80-2ce4-11eb-9fa2-df6da660726a.png)
