### ISSUE TITLE
Basex: how to  analyse a basex file(rather than a xml file) with this toolkit

### ISSUE THREAD

**Issue by sanshuiii** [BaseXdb/basex#1986]
We appreciate your feedback on BaseX. Please mind the following guidelines:

* For bug reports, feature requests and questions, please first write to our
   basex-talk mailing list: https://basex.org/open-source/.
* This tracker is used in a next step to discuss confirmed issues.
* You may as well find it helpful to browse through our documentation:
   https://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/

Thanks for your support.

**Comment by sanshuiii** [comment]
Hello, I am now trying to analyse some files with suffix "basex". There are lots of XQuery tutorials for XML file analyse when I search with the key word basex. However, I failed to find a document or something to guide me to analyse a local basex file (7 actually). I wonder if there is a more user-friendly guidance for basex file analysing.  If there is any approach to turn a basex file to a dict or a XML file, it will be perfect given I can handle these matters more easily. Thanks a lot.

**Comment by ChristianGruen** [comment]
Dear sanshuii, we appreciate your feedback on BaseX. Please mind the following guidelines:

We appreciate your feedback on BaseX. Please mind the following guidelines:

* For bug reports, feature requests and questions, please first write to our
   basex-talk mailing list: https://basex.org/open-source/.
* This tracker is used in a next step to discuss confirmed issues.
* You may as well find it helpful to browse through our documentation:
   https://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/

Thanks for your support.
