### ISSUE TITLE
bug in bin:shift function

### ISSUE THREAD

**Issue by hfmanson** [BaseXdb/basex#1988]
bin:shift produces incorrect results, see snippet below, e.g. it produces `<shift>7F0080</shift>` instead of `<shift>632080</shift>`

```
xquery version "3.0";

<shift>
{
  xs:hexBinary(bin:shift(bin:hex('00C641'), 7))    
}
</shift>
```

**Comment by ChristianGruen** [comment]
Fixed; a [new snapshot](https://files.basex.org/releases/latest/) is available.
