### ISSUE TITLE
Tough start - request for help

### ISSUE THREAD

**Issue by commandline-be** [BaseXdb/basex#1993]
We appreciate your feedback on BaseX. Please mind the following guidelines:

Maybe a feature request is in place here, first a request for direction.

Having to plow throw Microsoft Eventlogs and JSON log files i seek to use BaseX.
Casual creating a database and loading a .evtx file which was converted into .xml first works well.

The problem i face is the XQuery syntax as casually documented on the portal does not work or makes sense for my queries.

I can only query the root element //Events which then returns the entire file as response.
Providing a bit more newbie friendly documentation or pointers to suitable learning pages is most welcome.

Thanks for your support.

ps: In terms of a feature request, using jython it could be possible to make absorbind a .evtx files a possibility using one of available modules. Myself i use evtx_dump.py to export to .xml which is very fast and easy to use.

**Comment by ChristianGruen** [comment]
We appreciate your feedback on BaseX. Please mind the following guidelines:

* For bug reports, feature requests and questions, please first write to our
   basex-talk mailing list: https://basex.org/open-source/.
* This tracker is used in a next step to discuss confirmed issues.
* You may as well find it helpful to browse through our documentation:
   https://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/

Thanks for your support.

**Comment by commandline-be** [comment]
Thanks anyway. To be fair to my point for posting, the documenation is mostly redundant since it serves neither entry level, neither knowledgeable XQuery users. I do think baseX has great promise once i master some of it but the threshold for entry is extreme.

**Comment by ChristianGruen** [comment]
We invite you to write to our mailing list. The members of the list will be happy to give you more support.

**Comment by commandline-be** [comment]
oh, no mailinglist. Thanks, i'll check Stackoverflow first.

**Comment by ChristianGruen** [comment]
Have you made bad experiences? ;)

**Comment by commandline-be** [comment]
Are there any good ? 

:100: 

;)
