### ISSUE TITLE
documentation broken link

### ISSUE THREAD

**Issue by sbi6c** [BaseXdb/basex#1996]
**sorry for posting directly here**, had I more time would love to go the whole journey of registering and other things to get to base-x talk - a great measure to filter the posts, but I am really sorry I have no time for all that for this:

thx for all the good in your work, my small contrib

https://files.basex.org/releases/9.5/BaseX94.pdf

should be

https://files.basex.org/releases/9.5/BaseX95.pdf

Wishing you all the best, Kay

**Comment by ChristianGruen** [comment]
Thanks, the link has been fixed.
