### ISSUE TITLE
basex create new database returns error “resource not found”

### ISSUE THREAD

**Issue by danjbrendel** [BaseXdb/basex#2006]
Hello. Posted this in stackoverflow also, but no takers yet.

I'm trying to use basex to read xml. I'm running mac os Big Sur 11.2.3.

I download BaseX951.zip, open the gui, Database → New, as the documentation describes to get started. But when I put in a path to any xml file, including the complimentary factbook.xml practice file, I get the error: "Resource "[path name] (Operation not permitted)" not found."

If I try to browse instead, it doesn't show / let me go into most folders, and doesn't show any files in the folders I can get into (even when there are .xml files there).

I thought maybe add to "Full Disk Access" in System Preferences, but doesn't let me add BaseX.jar (or much else from the distribution).

**Comment by ChristianGruen** [comment]
I recommend you to post this to our basex-talk mailing list, as the issue tracker is used for confirmed bugs. Thanks in advance!
