### ISSUE TITLE
How to insert XML Content in db using  SQL Module

### ISSUE THREAD

**Issue by salim-dev** [BaseXdb/basex#2019]
Basex 9.5.2
First of all, I'd like to thank you guys for your work. It's a great tool and I am glad I was able to find it ! I am a beginner in XQuery and I could use some help on how to insert XML elements in my MySQL database. So far, it only inserts pieces of fragments of an xml file but I'd like to fetch the full fragments, including the elements along the content.
For instance, let's say I have :

```
let $element := "<exemple>hello world</exemple>"
let $currentDate := fn:format-dateTime(fn:current-dateTime(), "[Y0001]-[M01]-[D01] [H01]:[m01]:[s01]")
let $values :=  "('" ||  $element || "','" || $currentDate|| "','" || $currentDate ||  "')"


let $q := 'INSERT into table (element,created,updated) values ' || $values
let $conn := sql:connect("jdbc:mysql://xxxx:xxx@mysql:3306/database",map{'autocommit': true() ,'useUnicode':true(),'characterEncoding':'utf8'})
let $s := sql:execute($conn, $q)
let $conn := sql:close($conn)
```

```
---------------------------------------------------------------------------------
|	id	|	element		|	created 	|	updated	|
---------------------------------------------------------------------------------
|   x           |   hello world          |	xxxxx        | 	 xxxxx       | <===   ? ( "<exemple>hello world</exemple>")


```
I actually need the full fragment. How to achieve that?

Thanks for your help.

**Comment by ChristianGruen** [comment]
We appreciate your feedback on BaseX. Please mind the following guidelines:

* For bug reports, feature requests and questions, please first write to our
   basex-talk mailing list: https://basex.org/open-source/.
* This tracker is used in a next step to discuss confirmed issues.
* You may as well find it helpful to browse through our documentation:
   https://docs.basex.org/.
* Other helpful resources:
   * Stackoverflow: https://stackoverflow.com/questions/tagged/basex
   * Mailing list archive: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/

Thanks for your support.
