### ISSUE TITLE
Bindings (External Variables) dialog elements are tab-traversed by columns (instead of rows)

### ISSUE THREAD

**Issue by dliakh** [BaseXdb/basex#2050]
### Description of the Problem

(Not entirely a big problem, I'd say, however)
When you press \<tab> on the External Variables dialog, the order of element traversal is like
```

Name1  +->Value1
  |    |    |
  v    |    v
Name2 -+  Value2
```

### Expected Behavior

It would be nice to have
```
Name1---->Value1
            |
  +---------+
  |
  v
Name2---->Value2
```

### Steps to Reproduce the Behavior

1. Open the External Variables Dialog
2. Focus the fist variable name input text box (on the left)
3. Press the \<tab> key
4. You can see that the input focus moves to the next Name input (below), while it would be nice if it moved to the Value element (at the right)

### Do you have an idea how to solve the issue?

This is how this can be solved
https://github.com/BaseXdb/basex/pull/2049

### What is your configuration?

No specific configuration (reproducible in any case)

**Comment by ChristianGruen** [comment]
Thanks for the PR.
