### ISSUE TITLE
XPath: filter by original position() not working within collections

### ISSUE THREAD

**Issue by FherStk** [BaseXdb/basex#2064]
### Description of the Problem

Dear team,

When querying collections using XPath, it's not possible to get the item at a concrete position within each document. It works on eXist-db, but doesn't work on BaseX. 

Kind regards,
Fher

### Expected Behavior

Imagine 3 XML docs within the collection named "col" and 2 nodes called "node" within each XML doc.

Query: (collection("col")//node)[1]
Output:
It gets all the nodes (2 per file) and gets just the first one (1 hit).
Expected:
The same, this works just fine.

Query: collection("col")//node[1]
Output:
All the six nodes (6 hits), 2 per file.
Expected:
The first node of each XML file as eXist-db does (3 matches).

### Steps to Reproduce the Behavior

1. Create any XML file.
2. Create some copies of this XML file.
3. Create a collection with those XML files.
4. Run the XPath queries described before against this collection.

### Do you have an idea how to solve the issue?

Using the XPath query **collection("col")//node[1]** 

I suspect that the current behavior is:
1. Gets all the files within the collection.
2. Runs the XPath query _//node_ for each file.
3. Joins the results into a set.
4. Applies the [1] filter over the set itself, so returns the set. 

But I guess it should be:
1. Gets all the files within the collection.
2. Runs the XPath query _//node[1]_ for each file.
3. Joins the results into a set.
4. Return the set (already filtered)

### What is your configuration?

Ubuntu 21.10 
Kernel 5.13.0-28-generic
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment (build 16.0.2+7-Ubuntu-2)
OpenJDK 64-Bit Server VM (build 16.0.2+7-Ubuntu-2, mixed mode, sharing)

I tested with BaseX 9.0.1 (Ubuntu repo's lastest version) and also BaseX 9.6.4 running the **jar** file obtaining exactly the same results.

**Comment by ChristianGruen** [comment]
Could you please provide us with a minimal sample XML file for testing? Thanks in advance.

**Comment by FherStk** [comment]
Sure! Here you have the same files that I'm using for testing: [https://drive.google.com/file/d/1jZW9DeAd_1RsnDfinbpdv-536zmrdR4-/view?usp=sharing](https://drive.google.com/file/d/1jZW9DeAd_1RsnDfinbpdv-536zmrdR4-/view?usp=sharing)

**Comment by ChristianGruen** [comment]
Thanks. As your files don’t seem to include `node` elements, could you share a minimized version of your query with us which you believe should yield different results?

**Comment by FherStk** [comment]
Sorry, I tried to generalize the issue with generic data. 
Here you have the XPath queries I'm using:

**Query:**
declare namespace foaf="http://xmlns.com/foaf/0.1/";
collection("FOAF")//foaf:name[1]/text()

**Current result:**
Fernando Porrino Serrano
Amigote
Augusta Ada Byron
Charles Babage
Patrick Stewart
Data

**Expected result**
Fernando Porrino Serrano
Augusta Ada Byron
Patrick Stewart

**Comment by ChristianGruen** [comment]
Thanks! Please note that the returned result is correct:

```xquery
collection("FOAF")//foaf:name[1]
```

… is a shortcut for …

```xquery
collection("FOAF")/descendant-or-self::node()/child::foaf:name[position() = 1]
```

Two `foaf:name` are returned for each of your documents:

* The `descendant-or-self::node()` step will choose all nodes from the document.
* For each of these intermediate nodes, the `child` axis will be evaluated.
* The `foaf:Person` element has a `foaf:name` child, which will be returned.
* The `foaf:Person/foaf:knows/foaf:Person` element has a child as well, which will be returned as second result.

If you want to restrict the result to the first `foaf:name` of each document, you can e.g. use the `descendant` axis:

```xquery
collection("FOAF")/descendant::foaf:name[1]
```

**Comment by FherStk** [comment]
Hi Christian,

Thanks a lot for your explanations, I was looking at the [3.1 standard documentation ](https://www.w3.org/TR/xpath-31/#id-filter-expression)and I found the following (chapter 3.3.5):

`Note:
The path expression //para[1] does not mean the same as the path expression /descendant::para[1]. The latter selects the first descendant para element; the former selects all descendant para elements that are the first para children of their respective parents.`

So everything it's clear to me now. I guess that eXist-db is using a different approach that doesn't follow the standard specification. 

Thanks a lot for your help and sorry for all the inconveniences, 
Kind regards.
