### ISSUE TITLE
XQFT: different sentence

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#2088]
```xquery
'base.x' contains text 'base x' different sentence
```

Returns `false`, whereas `true` is probably correct.

**Comment by hrennau** [comment]
Same problem with "different paragraph":

basex "'x&#xA;y' contains text 'x y'"
=>
true

basex "'x&#xA;y' contains text 'x y' same paragraph"
=>
false

basex "'x&#xA;y' contains text 'x y' different paragraph"
=>
false

**Comment by ChristianGruen** [comment]
I‘ve decided to stick with the current implementation. The spec indicates that:

> A scope selection selects matches which satisfy the operand full-text selection and for which the matched tokens and phrases are contained in the same scope or in different scopes.

However, information is missing on what is going to happen with phrases that extend over several scopes.
