### ISSUE TITLE
GUI: info view source link wrong when module transport not file

### ISSUE THREAD

**Issue by apb2006** [BaseXdb/basex#2091]
### Description of the Problem

In the GUI run
```
inspect:xqdoc("https://raw.githubusercontent.com/acdh-oeaw/vleserver_basex/main/vleserver/changes.xqm")
```
![image](https://user-images.githubusercontent.com/429616/164975035-218ba21a-3b9d-4eb7-8f30-f755912bff64.png)

### Expected Behavior

link is wrong

### Steps to Reproduce the Behavior

```
inspect:xqdoc("https://raw.githubusercontent.com/acdh-oeaw/vleserver_basex/main/vleserver/changes.xqm")
```
Click info stopped at link

### Do you have an idea how to solve the issue?

Not sure. No link or  Load remote module into view?

### What is your configuration?

Basex 9.7

**Comment by ChristianGruen** [comment]
So we’ve stumbled across the same issue almost simultaneously … The second line had mistakenly been interpreted as part of the stack trace.

This has been fixed in 263ed8f02e3229e3300be8bbdddb544563d566b7 (and 08dfbcf3751d6e905a58fe0657357cd638622ab9). I’ve just updated the latest snapshot.
