### ISSUE TITLE
XQuery, static typing: Intersection of name tests

### ISSUE THREAD

**Issue by apb2006** [BaseXdb/basex#2102]
### Description of the Problem

BaseX 9.7.1 with the default setting 
```
set inlinelimit 50
```
Running `main.xq` from the attached [test.zip](https://github.com/BaseXdb/basex/files/8644969/test.zip) returns the empty sequence. 

After `set inlinelimit 0` it returns a map. This is the result I expect.
The map is returned for inlinelimit 14 or less.

If the following line in `qipe.xqm`  `function qipe:step` is commented out 
  `case element(qipe:xslt) return qipe:xslt($qitem,$this,$opts)`
the map is returned for all `inlinelimit` settings.

Similarly changing line 6 in `main.xq` to
```
return  fold-left( <load  xmlns="http://quodatum.com/ns/pipeline"  href="any.xml" />, (),qipe:step-across#2)
```
returns  the map  for all `inlinelimit` settings.

### Expected Behavior

The map result for all values of `inlinelimit`

### Steps to Reproduce the Behavior

As above

### What is your configuration?

BaseX 9.7.1

**Comment by ChristianGruen** [comment]
Confirmed. A minimized version (expected: `true`, returned: `false`):

```xquery
fold-left(
  <_><n/></_>/Q{}*,
  (),
  function($_, $n) { $n instance of element(n) }
)
```

**Comment by ChristianGruen** [comment]
The intersection of name tests at compile time was buggy (it was only triggered by inlining code).
A new snapshot is online.
