### ISSUE TITLE
BaseX ZIP package should contain .logs directory

### ISSUE THREAD

**Issue by tohuuuuu** [BaseXdb/basex#2105]
### Description of the Problem

When running BaseX on Linux using Yajsw/systemd, yajsw will create the (initially missing) data/.logs directory with user root as owner and restricted permissions. If a user different than root is used to run the BaseX server, that user won't have appropriate permissions to create and write logs into data/.logs. Thus, no server logs are created / written on a server system using Yajsw and a non-privileged system user to run the BaseX server.

### Expected Behavior

Server logs should be available also on systems that use Yajsw and a non-privileged system user who runs the BaseX server process.

### Steps to Reproduce the Behavior

1. On a Linux system, follow the steps explained in the Wiki: https://docs.basex.org/wiki/YAJSW (adapting paths);
2. Adapt the wrapper.basex.conf with wrapper.app.account=baseX to run the BaseX server as user baseX instead of root;
3. Install and start the BaseX service as described in the Wiki: https://docs.basex.org/wiki/YAJSW
4. Check $basexhome/data/.logs. The .logs directory will belong to user root with restricted access rights for other users.

### Do you have an idea how to solve the issue?

In the ZIP download package, just provide an empty .logs subdir in /data. If it's present, Yajsw won't create it with restrictive persmission.

### What is your configuration?

YAJSW: yajsw-stable-13.03
OS   : Linux/5.13.0-41-generic/amd64
JVM  : Private Build/11.0.15//usr/lib/jvm/java-11-openjdk-amd64/64

**Comment by ChristianGruen** [comment]
Thanks in advance for the proposed solution, sounds good.

**Comment by ChristianGruen** [comment]
I have [uploaded new snapshots](https://files.basex.org/releases/latest/).
Feel free to close the issue if you believe this has been fixed.

**Comment by tohuuuuu** [comment]
Great, thanks a lot for the quick fix!
