### ISSUE TITLE
Running Release 9.7.2 in Docker with dba attatched causes error

### ISSUE THREAD

**Issue by ywarnecke** [BaseXdb/basex#2108]
### Description of the Problem

When trying to run the newest release 9.7.2 with the proposed command: 

```
docker run -d \
	--name basexhttp \
	--publish 1984:1984 \
	--publish 8984:8984 \
	--volume "$HOME/basex/data":/srv/basex/data \
	--volume "$(pwd)/basex-api/src/main/webapp":/srv/basex/webapp \
  basex/basexhttp:latest
``` 
to include the dba webapp the following error appears when opening localhost:8984: 

```
Stopped at /srv/basex/webapp/dba/jobs/jobs.xqm, 116/45:
[XPST0017] Unknown function: jobs:bindings.
``` 

### Expected Behavior

The Webapp welcome page should load, as it does with versions prior to 9.7.2

### Steps to Reproduce the Behavior

1. clone newest git repo
2. run the mentioned command to start the docker container 
3. open localhost:8984

### Do you have an idea how to solve the issue?

Apparently the newest changes to the jobs.xqm are not correct. See error output. 

### What is your configuration?

Running on Linux with Kernel 5.13.19-2-MANJARO
Intel Core i5-4590
16 GB RAM

**Comment by ChristianGruen** [comment]
`basex/basexhttp:latest` is not maintained anymore, so I assume that your setup is based on an older instance of BaseX.

See https://github.com/BaseXdb/basex/issues/2051 for latest developments around BaseX and Docker.

**Comment by ChristianGruen** [comment]
I hope you could reconstruct the setting. If yes, I invite you to close the issue and use #2051 for further discussions.

**Comment by ywarnecke** [comment]
If the Docker I used is deprecated, then I will close this issue. I have a working version now, so thank you for the help.
