### ISSUE TITLE
xs:float idiv xs:decimal returns the wrong result

### ISSUE THREAD

**Issue by adamretter** [BaseXdb/basex#2111]
### Description of the Problem

The following query returns `0` in BaseX.

```
xs:float(1.13) idiv xs:decimal(1.13)
```

In Saxon and eXist-db this returns `1`.

### Expected Behavior

I think the query should return `1`.

As I understand https://www.w3.org/TR/xpath-31/#promotion then the `xs:decimal` should be promoted to an `xs:float` which would yield the equivalent query:

```
xs:float(1.13) idiv xs:float(1.13)
```

The equivalent query does produce `1`.

### Steps to Reproduce the Behavior

Run the query `xs:float(1.13) idiv xs:decimal(1.13)`

### What is your configuration?

BaseX 9.7.2 / OpenJDK 8 / macOS.

**Comment by ChristianGruen** [comment]
Thanks, @adamretter, very appreciated.

**Comment by adamretter** [comment]
Not at all! Thanks to you Christian :-)
