### ISSUE TITLE
xs:float ge xs:double returns the wrong result

### ISSUE THREAD

**Issue by adamretter** [BaseXdb/basex#2114]
### Description of the Problem

The following query returns `true` in BaseX.
```
xs:float(1.13) ge xs:double(1.13)
```

In Saxon and eXist-db this returns `false`.

### Expected Behavior

I think the query should return `false`.

### Steps to Reproduce the Behavior

Run the query `xs:float(1.13) ge xs:double(1.13)`

### What is your configuration?

BaseX 9.7.2 / OpenJDK 8 / macOS.

**Comment by ChristianGruen** [comment]
Awesome, thanks.
