### ISSUE TITLE
XQuery: sort order in Window function

### ISSUE THREAD

**Issue by mikekuznetsov11** [BaseXdb/basex#2119]
### Description of the Problem

Under certain circumstances Window function applies ordering where it should not.

### Expected Behavior

The resulting sequence must be unordered

### Steps to Reproduce the Behavior

[BaseX_window sorting defect.txt](https://github.com/BaseXdb/basex/files/8917451/BaseX_window.sorting.defect.txt)
In the example above I constructed a cascade:
* input
* sort
* apply window

When I return the whole window $w it gives:
* his - 1
* my - 1
* my - 2

However when I return $w/d it gives:
* 1 (assuming his)
* 2 (assuming my)
* 1 (assuming my)
Should be 1,1,2

### What is your configuration?

BaseX version 9.7.1
installed on Windows 10 Enterprise 1903

# General Options
DEBUG = false
DBPATH = C:\Program Files (x86)\BaseX\data
LOGPATH = .logs
REPOPATH = C:\Program Files (x86)\BaseX\repo
LANG = English
LANGKEYS = false
FAIRLOCK = false
CACHETIMEOUT = 3600

# Client/Server Architecture
HOST = localhost
PORT = 1984
SERVERPORT = 1984
USER = 
PASSWORD = 
SERVERHOST = 
PROXYHOST = 
PROXYPORT = 0
NONPROXYHOSTS = 
IGNORECERT = false
IGNOREHOSTNAME = false
TIMEOUT = 30
KEEPALIVE = 600
PARALLEL = 8
LOG = true
LOGMSGMAXLEN = 1000
LOGTRACE = true

# HTTP Services
WEBPATH = C:\Program Files (x86)\BaseX\webapp
GZIP = false
RESTPATH = 
RESTXQPATH = 
PARSERESTXQ = 3
RESTXQERRORS = true
HTTPLOCAL = false
STOPPORT = 8985
AUTHMETHOD = Basic

# Local Options

**Comment by ChristianGruen** [comment]
Please help us to make your question more specific.  If `<window>{$w}</window>` in your query is replaced by `<window>{$w/d}</window>`, the result is:

 ```xml
<outWindow>
  <window>
    <d>1</d>
  </window>
  <window>
    <d>2</d>
    <d>1</d>
  </window>
</outWindow>
<outd>
  <window>
    <d>1</d>
  </window>
  <window>
    <d>2</d>
    <d>1</d>
  </window>
</outd>
```

Which result would you expect?

**Comment by mikekuznetsov11** [comment]
Christian, thanks very much for the quick response. You hit it exactly right - my expectation was that the "order by" on step 2 should persist in the Window output (step 3). I like your advice in Solution 2 - use (!) instead of (/). This helps a lot!
