### ISSUE TITLE
Identation is disabled by default for JSON serialization in 10.3

### ISSUE THREAD

**Issue by dliakh** [BaseXdb/basex#2150]
### Description of the Problem

The JSON module documentation (https://docs.basex.org/wiki/Serialization) states that the 'indent' option is enabled by default (and it was in 9.7.3, for example)
and in 10.3 it's _disabled_ by default:

```
$ java -cp ~/BaseX103.jar org.basex.BaseX 'json:serialize(array {1, 2, 3, map {1 : array {1, 2, 3}}})'
[1,2,3,{"1":[1,2,3]}]

$ java -cp ~/BaseX973.jar org.basex.BaseX 'json:serialize(array {1, 2, 3, map {1 : array {1, 2, 3}}})'
[
  1,
  2,
  3,
  {
    "1": [
      1,
      2,
      3
    ]
  }
]

```

### Expected Behavior

The default for the 'indent' option is like in the documentation

### Steps to Reproduce the Behavior

1. Try calling json:serialize() to serialize some relatively complex structure that should produce multi-line formatted output (if the 'indent' option is enabled.
2. Check the output is all in one line (and not indented)
3. Try the same query with an older version of BaseX (for example 9.7.3)

### What is your configuration?

Ubuntu 22.0.4,
openjdk 17.0.5 2022-10-18,
BaseX 10.3

**Comment by ChristianGruen** [comment]
Thanks for the observation.

> The JSON module documentation (https://docs.basex.org/wiki/Serialization) states that the 'indent' option is enabled by default

In the documentation, we tried to indicate that the default has changed with version 10 (see also the changelog):

![image](https://user-images.githubusercontent.com/196589/202435304-8bad460b-6f9c-43b6-b663-b175081e587b.png)

Maybe there’s another piece in the documentation that tells otherwise? Could you please give us additional hints?

**Comment by ChristianGruen** [comment]
An addendum: With BaseX 11, it will be possible to enforce indentation on command-line via `-W`. A beta implementation is already available in BaseX 10.3.

**Comment by dliakh** [comment]
Hi Christian,
This is the document: https://docs.basex.org/wiki/JSON_Module#Options

(the default for the indent option is specified as 'yes')

Thank you for your prompt response
Best regards

**Comment by ChristianGruen** [comment]
Thanks; I have updated our documentation.

**Comment by dliakh** [comment]
Thank you very much
