### ISSUE TITLE
base-uri() produces "Invalid URI: ..." for file with square brackets in name

### ISSUE THREAD

**Issue by jperterm** [BaseXdb/basex#2180]
### Description of the Problem

When I execute `collection('...')/base-uri()` on a database which has a file/document named `[Content_Types].xml`, I get `Invalid URI: /some-db/[Content_Types].xml`.

`[Content_Types].xml` files are part of the *Open Packaging Conventions*, which e.g. is used for packaging OOXML (DOCX files etc.).

### Expected Behavior

I expect the URI have escaped square brackets and produce `/some-db/%5BContent_Types.xml%5D.xml`.

### Steps to Reproduce the Behavior

1. Create a `[Content_Types].xml` file with valid xml.
2. Create and open a database `some-db` with file above.
3. Run `collection('some-db')/base-uri()`

### What is your configuration?

- BaseX v10.4
- OS: Win 10

**Comment by ChristianGruen** [comment]
True, we need to fix this. There's already an open issue for that (#1172), so I'll close yours.

Until this is fixed, you can use helper functions of our Database Module  instead([db:name, db:path](http://docs.basex.org/wiki/Database_Module#Helper_Functions)).

**Comment by jperterm** [comment]
Ah, thanks for the hint with the helper functions. I already tried to find something alike.
