### ISSUE TITLE
XQuery: Bug on exist() with non-existing attribute

### ISSUE THREAD

**Issue by Twilight-Shuxin** [BaseXdb/basex#2212]
### Description of the Problem

Given this XML document:
```
<K id="1">1</K>
```
and XPath Query
```
//*[exists(@n1 >= -1)]
```
BaseX give result
```
<K id="1">1</K>
```

### Expected Behavior

Should return empty result set as eXist & Saxon since attribute n1 does not exist in node K.

### Steps to Reproduce the Behavior

1. Create database `create database test`
2. Insert XML file into database `put test.xml path/to/file `
3. Execute XPath query `xquery //*[exists(@n1 >= -1)]`

### What is your configuration?

BaseX version: BaseX 10.7 beta latest commit 081fb4d on Windows

**Comment by Twilight-Shuxin** [comment]
Thanks a lot for the explanation! It seems that this is correct while a bit tricky and I will close the issue :)

**Comment by michaelhkay** [comment]
@martin-honnen Thanks for the feedback.

**Comment by Twilight-Shuxin** [comment]
@michaelhkay I initially tested this on Saxon-HE 12.0, which is currently out of date. Today I tried again with the latest Saxon-HE12.2 release and it seems that the problem still exists.

**Comment by Twilight-Shuxin** [comment]
I used the Saxon-HE 12.2 jar files in SaxonHE12-2J.zip as external libraries and ran from java on Windows.

**Comment by michaelhkay** [comment]
Thanks. I feel we're trespassing on this space to be discussing this here: could we please continue the conversation at https://saxonica.plan.io/issues/6051 - thank you.

**Comment by Twilight-Shuxin** [comment]
@michaelhkay Sure, thanks!
