### ISSUE TITLE
XQuery: Unexpected exception of mapping double attributes

### ISSUE THREAD

**Issue by Twilight-Shuxin** [BaseXdb/basex#2215]
### Description of the Problem

Given this XML document:
```
<T id="1" a="1" b="1"/>
```
and XPath Query
```
boolean(count(//*[@id="1"] ! (@a, @b)))
```

BaseX throws exception: 
[XPTY0019] (@a | @b): node expected, xs:boolean found: true().

### Expected Behavior

Should return true as Saxon and eXist-DB.

### Steps to Reproduce the Behavior

1. Create database `create database test <T id="1" a="1" b="1"/>`
3. Execute XPath query `xquery boolean(count(//*[@id="1"] ! (@a, @b)))`

### What is your configuration?

BaseX version: BaseX 10.7 beta latest commit 081fb4d on Windows

**Comment by ChristianGruen** [comment]
Thanks for all the bug reports. I'll look at them in around 10 days. Keep on going ;)

**Comment by Twilight-Shuxin** [comment]
@ChristianGruen Thanks a lot! :)
