### ISSUE TITLE
XQuery: Bug on consecutive map with distinct-values

### ISSUE THREAD

**Issue by Twilight-Shuxin** [BaseXdb/basex#2217]
### Description of the Problem

Given this XML document:
```
<F/>
```
and XPath Query
```
/F[(distinct-values(. ! (boolean(.), . = <A/>)) ! count(.)) castable as xs:boolean]
```

BaseX throws exception:
java.io.IOException: Stopped at C:/BaseX/BaseXSource/basex/, 1/42:
[FORG0001] Cannot convert element() to xs:boolean: <A/>.

### Expected Behavior

Should execute successfully,

### Steps to Reproduce the Behavior

1. Create database `create database test <F/>`
3. Execute XPath query `xquery /F[(distinct-values(. ! (boolean(.), . = <A/>)) ! count(.)) castable as xs:boolean]`

### What is your configuration?

BaseX version: BaseX 10.7 beta latest commit 081fb4d on Windows

**Comment by ChristianGruen** [comment]
@Twilight-Shuxin All bugs have been fixed. Thanks again for providing us with such valuable feedback!

**Comment by Twilight-Shuxin** [comment]
Thank you too for such a quick fix!
