### ISSUE TITLE
XQuery: Bug on node selection with position()

### ISSUE THREAD

**Issue by Twilight-Shuxin** [BaseXdb/basex#2219]
### Description of the Problem

Given this XML document:
```
<T/>
```
and XPath Query
```
//*[position() < position()]
```
BaseX returned node T.

### Expected Behavior

Should not select node as predicate evaluates to false always.

### Steps to Reproduce the Behavior

1. Create database `create database test <T/>`
3. Execute XPath query `xquery //*[position() < position()]`

### What is your configuration?

BaseX version: BaseX 10.7 beta latest commit 28e2e38 on Windows

**Comment by ChristianGruen** [comment]
Fixed, and optimized for all 6 operators (=, !=, <=, >=, <, >): `EXPR[position() < position()]` is rewritten to `()`.
