### ISSUE TITLE
XQuery: Bug on contains-token() with token index

### ISSUE THREAD

**Issue by Twilight-Shuxin** [BaseXdb/basex#2222]
### Description of the Problem

Given this XML document:
```
<M v="a"/>
```
and XPath Query
```
//M/descendant-or-self::M[contains-token(@v, "a")]
```
after creating token index BaseX returns empty result set. 

### Expected Behavior

Should return node M as before token index is created. 

### Steps to Reproduce the Behavior

1. Create database `create database test <M v="a"/>`
2. Create index token `create index token`
3. Execute XPath query `xquery //M/descendant-or-self::M[contains-token(@v, "a")]`

### What is your configuration?

BaseX version: BaseX 10.7 beta latest commit 27725e9 on Windows

**Comment by ChristianGruen** [comment]
Thanks for the observation. I noticed it also fails with the default attribute index:

```xquery
//M/descendant-or-self::M[@v = 'a']
```

**Comment by ChristianGruen** [comment]
Fixed (for all index types).
