### ISSUE TITLE
XQuery: Incorrect result count with multiple sequence operators

### ISSUE THREAD

**Issue by Twilight-Shuxin** [BaseXdb/basex#2225]
### Description of the Problem

Given this XML document:
```
<I><A/><B/></I>
```
and XPath Query
```
//B/reverse(tail(reverse(subsequence(//*/has-children(), 3))))
```
BaseX returns one element false. 

### Expected Behavior

Should return empty result set. For node `B`, `//*/has-children()` selects the result of `I, A, B` three nodes. Applying subsequence(s, 3) selects only the last element, and after application of tail function no result should be selected. In terms of number of results returned, the two reverse() operations seems redundant in this case. If deleted BaseX returns the expected results. 

### Steps to Reproduce the Behavior

1. Create database `create database db <I><A/><B/></I>`
2. Execute XPath query `xquery //B/reverse(tail(reverse(subsequence(//*/has-children(), 3))))`

This is a reduced test case from: 

1. Create database `create database db <I><A><B><C/></B></A><D/></I>`
2. Execute XPath query `xquery //D/reverse(tail(reverse(subsequence(./preceding::*/has-children(), 3))))`

### What is your configuration?

BaseX version: BaseX 10.7 beta latest commit 564bd39 on Windows

**Comment by ChristianGruen** [comment]
Thanks as always! `reverse(tail(reverse(...)))` is rewritten to a function that will be introduced with XQuery 4.0 – [fn:trunk](https://qt4cg.org/specifications/xpath-functions-40/Overview.html#func-trunk) – and the optimization rules of that function contained a bug.

**Comment by Twilight-Shuxin** [comment]
Thanks also for the response speed always so impressive!
