### ISSUE TITLE
Text selection in the editor of the gui works incorrectly

### ISSUE THREAD

**Issue by dt192** [BaseXdb/basex#2230]
### Description of the Problem

See video.

https://github.com/BaseXdb/basex/assets/2612048/ebfaccd6-d416-4589-a69d-bf1c1a2c78e2

### Expected Behavior

It should select `loot`. I tested in a few other windows applications and they don't jump to the left when you first mouse down and they don't use the right side of the character as the boundary, they use the midway point.

### Steps to Reproduce the Behavior

Try to select text in the editor panel of the gui.

### Do you have an idea how to solve the issue?

no

### What is your configuration?

Windows 10, BaseX installed through the exe installer.

**Comment by ChristianGruen** [comment]
Curious – it was only a few days ago that I noticed this by myself for the very first time.
It has been fixed; a [new snapshot](https://files.basex.org/releases/latest/) is available.

**Comment by dt192** [comment]
Thanks for the quick fix.
