### ISSUE TITLE
Additional option for reading XQuery from file

### ISSUE THREAD

**Issue by brandes-pq** [BaseXdb/basex#2243]
This is a (very minor) feature proposal.

At the moment, unless I have overlooked something, the regular way to execute an XQuery script file on the command line is by giving it without any option:

```sh
basex foo.xq
```

If the file `foo.xq` does not exist, it is interpreted as an XQuery expression, yielding the somewhat surprising error message

```
[XPDY0002] foo.xq: Context is undeclared.
```
It would be nice to have an option to make clear that an XQuery script file is to be executed; this would enable a better error message.
Since `-f` is not yet used, it might be an intuitive choice. 

Hypothetical example:
```sh
> basex -f foo.xq
foo.xq: file could not be found
```

A related problem is that `-c` tries to decide whether its argument is a command or a command file. This leads to misleading behavior e.g. in the following case (where nothing is output by BaseX):

```sh
> touch list
> basex -c list
```

Especially when BaseX is being used in batch or shell scripts, it would be helpful to have the possibility to always explicitly state whether an argument is supposed to be an XQuery expression, an XQuery file, a literal command or a command file.

**Comment by ChristianGruen** [comment]
Thanks for the suggestion. I think I’ll change the behavior with BaseX 11 and…

* limit the input of `-c` to command strings,
* add `-C` for command script files, and
* add `-Q` for query files.

**Comment by brandes-pq** [comment]
I think that would be a great solution. I assume you are okay with the fact that this breaks CLI backwards compatibility?

**Comment by ChristianGruen** [comment]
I’ve just added `-C` and `-Q`: https://docs.basex.org/wiki/Command-Line_Options

A new snapshot is online. `-c` will be modified with BaseX 11.
