### ISSUE TITLE
Does basex support cluster deployment？ basex是否支持集群部署？

### ISSUE THREAD

**Issue by zhenfeii** [BaseXdb/basex#2306]
### Description of the Problem

The standalone version of the database carries the risk of data loss. Can basex support cluster deployment? Similar to master-slave replication, sharded storage, and so on??

I have reviewed the document in detail and did not find any description about the cluster.

单机版的数据库有数据丢失风险，basex能否支持集群部署？类似主从复制、分片存储等等？？
﻿
我详细查看文档，没有发现关于集群的描述。

### Expected Behavior

Capable of supporting clusters and providing corresponding configurations

能支持集群，并给出相应配置

### Steps to Reproduce the Behavior

none.

### What is your configuration?

none.

**Comment by ChristianGruen** [comment]
For general questions on BaseX, I recommend you to look into our [mailing list](https://www.mail-archive.com/basex-talk%40mailman.uni-konstanz.de/). Thanks in advance.
