### ISSUE TITLE
Issues with connections to localhost on MacOS Sequoia

### ISSUE THREAD

**Issue by s0rr0w** [BaseXdb/basex#2336]
### Description of the Problem

html:doc("http://localhost:3000/") gets connection timeout on MacOS Sequoia. BaseX version 11.3. Java version: openjdk 23 20024-09-17
Simple test that uses java.net.HttpURLConnection works fine. 

### Expected Behavior

HTTP connection to local host works as expected.

### Steps to Reproduce the Behavior

1. Run BaseXGUI from CLI on MacOS Sequoia using command: java -cp BaseX.jar org.basex.BaseXGUI
2. Create new xq file
3. Type doc("http://localhost:3000/")
4. Run script

### What is your configuration?

MacOS Sequoia. BaseX version 11.3. Java version: openjdk 23 20024-09-17

**Comment by s0rr0w** [comment]
The problem was in system/webserver configuration.
Webserver listened for both, ipv4 and ipv6 addresses on the same port. If you run the server using ipv4 protocol only then BaseX can connect the localhost perfectly without any errors.

Probably the behavior of protocol picking is changed in MacOS Sequoia.

**Comment by ChristianGruen** [comment]
Good to know. Feel free to close the issue.
