### ISSUE TITLE
"Bad escape" and duplicated path when it's not ascii

### ISSUE THREAD

**Issue by 2-www** [BaseXdb/basex#2355]
### Description of the Problem

while being in a folder that has unicode in the path, using any function that opens a file, "Bad escape" is printed and it can't open the file because it tries to open "[folder]/file:[folder]/[filename]" instead of "[folder]/[filename]"
```
$ ls 1.xml
1.xml
$ basex
BaseX 10.5 [Standalone]
Try 'help' to get more information.
> xquery doc("1.xml")
java.lang.IllegalArgumentException: Bad escape
java.lang.IllegalArgumentException: Bad escape
Stopped at /home/user/Код/x1/file:/home/user/Код/x1/, 1/4:
[FODC0002] Resource '/home/user/Код/x1/file:/home/user/Код/x1/1.xml' not found.
> 
```

### Expected Behavior

it opens the file

### Steps to Reproduce the Behavior

```
mkdir бульк
cd бульк
basex
```

### What is your configuration?

- LANG=uk_UA.UTF-8
- Debian GNU/Linux trixie/sid (testing)
- BaseX 10.5
- didn't change any configs

**Comment by ChristianGruen** [comment]
I remember a similar problem being reported in the past. Could you please check if the problem persists with the latest version of BaseX?
