### ISSUE TITLE
Replication

### ISSUE THREAD

**Issue by dubiousdavid** [BaseXdb/basex#581]
Replication is a really big deal for companies seeking to use BaseX as an alternative to something like MySQL.  There are some details on the xquery wikibook about an implementation in eXist (http://en.wikibooks.org/wiki/XQuery/eXist_Replication#How_Replication_Works).  

Replication obviously provides two critical features.  First, a reliable, up-to-date backup of the data.  Second, the ability to scale reads, and possibly writes, horizontally.  Systems like MarkLogic can do this, but there lack of standards compliance with newer features and lack of driver support is an issue for me.

Thanks for making such cool software.  I'm really excited I've rediscovered the joys of XML.

**Comment by ChristianGruen** [comment]
Closed for now (might be reopened if we have some more concrete ideas how to realize it for a wider audience).
