### ISSUE TITLE
Selective indexing

### ISSUE THREAD

**Issue by hutchkintoot** [BaseXdb/basex#59]
It would be nice to be able to restrict/select, by path or node name, the element that you want to add to the different indexes (text/attribute/full-text).  

e.g. you might store documents containing annual reports. They contain a lot of data but when it comes to indexing you might only be interested to add a full-text index on */annualReport/companyName* and a text-index on */annualReport/companyID*. 

I might have missed it, but you don't seem to be able to do this today.

**Comment by ChristianGruen** [comment]
Related: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg06176.html

**Comment by ChristianGruen** [comment]
I **finally** had a closer look at this issue (which is the oldest one in our tracker that's still open!), and I believe I'll implement this in BaseX 8.3:

I will introduce new options `TEXTINCLUDE`, `ATTRINCLUDE` and `FTINCLUDE`, which can be used to specify names of elements/attributes in the expanded QName notation. These will be considered when indexing the database contents. By default, no QNames are specfiied, and everything will be indexed as before.

This is what needs to be done (I will extend the list step by step; if anyone sees what's missing, feel free to contribute to the list):

**Indexing**
* [ ] Consider QNames when creating any of the three index structures
* [ ] Store current QName assignments in database meta data
* [ ] Updatable index, Insertions/deletions: consider QNames
* [ ] Updatable index, Rename operations: update index (new requirement)

**Querying**
* [ ] Only rewrite paths for index access if the addressed elements/attributes have been indexed.
* [ ] Check the following basic path patterns (obviously, there are many more):
  * Text index: `//*[x = 'TEXT']`, `//*[x/text() = 'TEXT']`, `//x[. = 'TEXT']`, `//x[text() = 'TEXT']`
  * Attribute index: `//*[*/@x = 'TEXT']`, `//*[@x = 'TEXT']`, `//@x[. = 'TEXT']`

**Commands**
* [ ] `OPTIMIZE`: consider original list of QNames when updating indexes
* [ ] `OPTIMIZE ALL`: adopt global options (see: handling of full-text options)
* [ ] `CREATE INDEX`: adopt global options
* [ ] `INFO INDEX`: include QNames in output

**Interfaces**
* [ ] GUI: Include text fields for new options in database creation and properties dialog
* [ ] DBA: Include text fields for new options

**Documentation to be updated**
* [ ] http://docs.basex.org/wiki/Options
* [ ] http://docs.basex.org/wiki/Commands
* [ ] http://docs.basex.org/wiki/Indexes
