### ISSUE TITLE
Hidden text for overflowing text

### ISSUE THREAD

**Issue by dirkk** [BaseXdb/basex#725]
When having overflowing text without breaks the editor hides the text using Linux (Fedora 19). I would expect either a scrollbar or automatic line breaks. See the attached screenshot for an example

![screenshot from 2013-07-11 23 10 00](https://f.cloud.github.com/assets/327759/784873/d6e91178-ea6e-11e2-8384-f56908413544.png)

**Comment by ChristianGruen** [comment]
…has been solved in the meanwhile.
