### ISSUE TITLE
Bounds checking for `xs:integer` is broken.

### ISSUE THREAD

**Issue by LeoWoerteler** [BaseXdb/basex#760]
BaseX uses `double` calculations in order to check if 64-bit `long` calculations overflow. As IEEE754 `double`s only have 53 significant binary digits but operations on `long` need up to 128, this is unsafe:

`-9223372036854775807 - 1024` silently underflows to `9223372036854774785` even though the boundary check in `org.basex.query.expr.Calc` is in place.

**Comment by ChristianGruen** [comment]
The bugs of the first two comments are resolved; the last observation could be resolved by introducing BigInt instances (the cast proposal leads to wrong error codes, `FORG0001` instead of `FOAR0002`).

**Comment by LeoWoerteler** [comment]
The original problems are fixed by GH-942, the last comment is not easy to address elegantly and essentially caused by the XQuery grammar not supporting negative integer literals. I will therefore close this issue.
