### ISSUE TITLE
XQuery: precompile modules

### ISSUE THREAD

**Issue by ChristianGruen** [BaseXdb/basex#874]
Precompilation should be applied to all modules with a static base URI that points to a local file…
1. Instead of repeatedly parsing a module, its parsed expression tree should be kept in main-memory.
2. The expression tree should additionally be statically compiled.
3. If a module is requested/imported, and if its timestamp has not changed, its expression tree will be copied and _dynamically_ compiled (only then, the context item and external variables will be bound, and external resources – documents , databases – will be opened).
4. Whenever the timestamp of the local file of a precompiled module changes, it will be reloaded (see Step 1).

In the RESTXQ context, variables should be bound to the called function before dynamically compiling it.

**Comment by alpheios** [comment]
Why not have a manual recompile like the "rest:init()" method? Wouldn't this be very similar?

**Comment by ChristianGruen** [comment]
Too ambitious for the foreseeable future.
