### ISSUE TITLE
Ancestor axis of DBNodes wrapped in FNodes

### ISSUE THREAD

**Issue by LeoWoerteler** [BaseXdb/basex#919]
#### Query:

``` xquery
let $a := (copy $a := <a><b/></a> modify () return $a)
return <x>{ $a }</x>//b/ancestor::node()/name()
```
#### Expected:

`x a`
#### Result:

`a`

**Comment by ChristianGruen** [comment]
Possibly related:

**input.xml:**

**Query:**

```xquery
let $doc := document { <a><b/></a> }
let $dbnode := ($doc update ())/*
return id("id", element { node-name($dbnode) } { $dbnode/node() }/*[1])
```

**Expected:** `FODC0001` (Specified node has no document node as root.)

**Result:** *empty sequence*

**Comment by ChristianGruen** [comment]
Related: https://www.mail-archive.com/basex-talk@mailman.uni-konstanz.de/msg13035.html
