### ISSUE TITLE
Don't use java.net.URI to validate URIs

### ISSUE THREAD

**Issue by dimitarp** [BaseXdb/basex#928]
BaseX uses java.net.URI for namespaces. However, java.net.URI is unfortunately not compliant with RFC 3986. Thus the following is considered invalid by BaseX:

```xml
<a xmlns="x:"/>
```

**Comment by ChristianGruen** [comment]
I think I'll close this (sounds like a lot of effort.. ;).

**Comment by ChristianGruen** [comment]
Copied from #1215:

> Consider the following query
> ```xquery
> resolve-uri("file:///b.xml"),
> resolve-uri("a.xml","file:///b.xml")
> ```
> the result is
> ``` 
> file:///b.xml
> file:/a.xml
> ```
> It would be nice if both results had the same number of slashes.
